/*******************************************************************************
 * Admin generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Admin extends PlayerController
    config(Game)
    notplaceable
    hidecategories(Mobile,Navigation,MovementReplication);

simulated event PostBeginPlay()
{
    super.PostBeginPlay();
    AddCheats();
    //return;    
}

exec function Admin(string CommandLine)
{
    ServerAdmin(CommandLine);
    //return;    
}

reliable server function ServerAdmin(string CommandLine)
{
    local string Result;

    Result = ConsoleCommand(CommandLine);
    // End:0x43
    if(Result != "")
    {
        ClientMessage(Result);
    }
    //return;    
}

exec function KickBan(string S)
{
    ServerKickBan(S);
    //return;    
}

reliable server function ServerKickBan(string S)
{
    WorldInfo.Game.KickBan(S);
    //return;    
}

exec function Kick(string S)
{
    ServerKick(S);
    //return;    
}

reliable server function ServerKick(string S)
{
    WorldInfo.Game.Kick(S);
    //return;    
}

exec function PlayerList()
{
    // End:0x16
    foreach DynamicActors(class'PlayerReplicationInfo', UnknownLocal_1)
    {        
    }    
    //return;    
}

exec function RestartMap()
{
    ServerRestartMap();
    //return;    
}

reliable server function ServerRestartMap()
{
    ClientTravel("?restart", 2);
    //return;    
}

exec function Switch(string URL)
{
    ServerSwitch(URL);
    //return;    
}

reliable server function ServerSwitch(string URL)
{
    WorldInfo.ServerTravel(URL);
    //return;    
}

defaultproperties
{
    CylinderComponent=CylinderComponent'Default__Admin.CollisionCylinder'
    Components(0)=CylinderComponent'Default__Admin.CollisionCylinder'
    CollisionComponent=CylinderComponent'Default__Admin.CollisionCylinder'
}