/*******************************************************************************
 * AnimNodeBlendByBase generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class AnimNodeBlendByBase extends AnimNodeBlendList
    native(Anim)
    hidecategories(Mobile,Object,Object,Object,Object);

enum EBaseBlendType
{
    BBT_ByActorTag,
    BBT_ByActorClass,
    BBT_MAX
};

var() AnimNodeBlendByBase.EBaseBlendType Type;
var() name ActorTag;
var() class<Actor> ActorClass;
var() float BlendTime;
var transient Actor CachedBase;

defaultproperties
{
    BlendTime=0.2
    Children(0)=(Name=Normal,Anim=none,Weight=0,BlendWeight=0,bMirrorSkeleton=false,bIsAdditive=false,DrawY=0,AdditiveWeightScale=0)
    Children(1)=(Name=Based,Anim=none,Weight=0,BlendWeight=0,bMirrorSkeleton=false,bIsAdditive=false,DrawY=0,AdditiveWeightScale=0)
    bFixNumChildren=true
}