/*******************************************************************************
 * BlurEffect generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class BlurEffect extends PostProcessEffect
    native
    hidecategories(Mobile,Object);

var() int BlurKernelSize;

defaultproperties
{
    BlurKernelSize=2
}