/*******************************************************************************
 * DrawLightConeComponent generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class DrawLightConeComponent extends DrawConeComponent
    native(Light)
    editinlinenew
    collapsecategories
    hidecategories(Mobile,Object,Physics,Collision,PrimitiveComponent,Rendering);

defaultproperties
{
    AlwaysLoadOnClient=false
    AlwaysLoadOnServer=false
    AbsoluteScale=true
}