/*******************************************************************************
 * FogVolumeSphericalDensityInfo generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class FogVolumeSphericalDensityInfo extends FogVolumeDensityInfo
    native(FogVolume)
    placeable
    hidecategories(Mobile,Navigation,MovementReplication,Collision)
    autoexpandcategories(FogVolumeDensityInfo);

defaultproperties
{
    DensityComponent=FogVolumeSphericalDensityComponent'Default__FogVolumeSphericalDensityInfo.FogVolumeComponent0'
    begin object name=AutomaticMeshComponent0 class=StaticMeshComponent
        StaticMesh=StaticMesh'EngineMeshes.Sphere'
        CollideActors=false
    object end
    // Reference: StaticMeshComponent'Default__FogVolumeSphericalDensityInfo.AutomaticMeshComponent0'
    AutomaticMeshComponent=AutomaticMeshComponent0
    Components(0)=none
    begin object name=AutomaticMeshComponent0 class=StaticMeshComponent
        StaticMesh=StaticMesh'EngineMeshes.Sphere'
        CollideActors=false
    object end
    // Reference: StaticMeshComponent'Default__FogVolumeSphericalDensityInfo.AutomaticMeshComponent0'
    Components(1)=AutomaticMeshComponent0
    Components(2)=none
    Components(3)=FogVolumeSphericalDensityComponent'Default__FogVolumeSphericalDensityInfo.FogVolumeComponent0'
}