/*******************************************************************************
 * InterpTrackFade generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class InterpTrackFade extends InterpTrackFloatBase
    native(Interpolation)
    collapsecategories
    hidecategories(Mobile,Object);

var() bool bPersistFade;
var() Color FadeColor;

defaultproperties
{
    TrackInstClass='InterpTrackInstFade'
    TrackTitle="Fade"
    bOnePerGroup=true
    bDirGroupOnly=true
}