/*******************************************************************************
 * KActor generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class KActor extends DynamicSMActor
    native(Physics)
    nativereplication
    placeable
    hidecategories(Mobile,MovementReplication)
    classgroup(Physics);

var() bool bDamageAppliesImpulse;
var() repnotify bool bWakeOnLevelStart;
var bool bCurrentSlide;
var bool bSlideActive;
var(StayUprightSpring) bool bEnableStayUprightSpring;
var() bool bLimitMaxPhysicsVelocity;
var transient bool bNeedsRBStateReplication;
var bool bDisableClientSidePawnInteractions;
var export editinline ParticleSystemComponent ImpactEffectComponent;
var export editinline AudioComponent ImpactSoundComponent;
var export editinline AudioComponent ImpactSoundComponent2;
var float LastImpactTime;
var PhysEffectInfo ImpactEffectInfo;
var export editinline ParticleSystemComponent SlideEffectComponent;
var export editinline AudioComponent SlideSoundComponent;
var float LastSlideTime;
var PhysEffectInfo SlideEffectInfo;
var(StayUprightSpring) float StayUprightTorqueFactor;
var(StayUprightSpring) float StayUprightMaxTorque;
var() float MaxPhysicsVelocity;
var() float NetRelevantDistanceSquared;
var native const RigidBodyState RBState;
var native const float AngErrorAccumulator;
var repnotify Vector ReplicatedDrawScale3D;
var transient Vector InitialLocation;
var transient Rotator InitialRotation;

replication
{
    // Pos:0x000
     if(bNeedsRBStateReplication && int(Role) == int(ROLE_Authority))
        RBState;

    // Pos:0x020
     if(bNetInitial && int(Role) == int(ROLE_Authority))
        ReplicatedDrawScale3D, bWakeOnLevelStart;
}

// Export UKActor::execGetKActorPhysMaterial(FFrame&, void* const)
native final function PhysicalMaterial GetKActorPhysMaterial();

// Export UKActor::execResolveRBState(FFrame&, void* const)
native final function ResolveRBState();

simulated event PostBeginPlay()
{
    super.PostBeginPlay();
    // End:0x4B
    if(bWakeOnLevelStart && StaticMeshComponent != none)
    {
        StaticMeshComponent.WakeRigidBody();        
    }
    else
    {
        bNeedsRBStateReplication = !bNoDelete;
    }
    ReplicatedDrawScale3D = DrawScale3D * 1000;
    // End:0xB9
    if((StaticMeshComponent != none) && StaticMeshComponent.bNotifyRigidBodyCollision)
    {
        SetPhysicalCollisionProperties();
    }
    InitialLocation = Location;
    InitialRotation = Rotation;
    // End:0x135
    if((bDisableClientSidePawnInteractions && int(Role) != int(ROLE_Authority)) && StaticMeshComponent != none)
    {
        StaticMeshComponent.SetRBCollidesWithChannel(2, false);
    }
    //return;    
}

simulated event FellOutOfWorld(class<DamageType> dmgType)
{
    ShutDown();
    super(Actor).FellOutOfWorld(dmgType);
    //return;    
}

simulated event Destroyed()
{
    // End:0x82
    if(ImpactEffectInfo.Sound != none)
    {
        // End:0x52
        if(ImpactSoundComponent != none)
        {
            ImpactSoundComponent.bAutoDestroy = true;
        }
        // End:0x82
        if(ImpactSoundComponent2 != none)
        {
            ImpactSoundComponent2.bAutoDestroy = true;
        }
    }
    // End:0xC5
    if(SlideEffectInfo.Sound != none)
    {
        SlideSoundComponent.bAutoDestroy = true;
    }
    super(Actor).Destroyed();
    //return;    
}

simulated function SetPhysicalCollisionProperties()
{
    UnknownLocal_1 = GetKActorPhysMaterial();
    ImpactEffectInfo = UnknownLocal_1.FindPhysEffectInfo(0);
    SlideEffectInfo = UnknownLocal_1.FindPhysEffectInfo(1);
    // End:0xF4
    if(ImpactEffectInfo.Effect != none)
    {
        ImpactEffectComponent = new (self) class'ParticleSystemComponent';
        ImpactEffectComponent.bAutoActivate = false;
        ImpactEffectComponent.SetTemplate(ImpactEffectInfo.Effect);
    }
    // End:0x1BC
    if(ImpactEffectInfo.Sound != none)
    {
        ImpactSoundComponent = new (self) class'AudioComponent';
        ImpactSoundComponent.SoundCue = ImpactEffectInfo.Sound;
        ImpactSoundComponent2 = new (self) class'AudioComponent';
        ImpactSoundComponent2.SoundCue = ImpactEffectInfo.Sound;
    }
    // End:0x252
    if(SlideEffectInfo.Effect != none)
    {
        SlideEffectComponent = new (self) class'ParticleSystemComponent';
        SlideEffectComponent.bAutoActivate = false;
        SlideEffectComponent.SetTemplate(SlideEffectInfo.Effect);
    }
    // End:0x2C7
    if(SlideEffectInfo.Sound != none)
    {
        SlideSoundComponent = new (self) class'AudioComponent';
        SlideSoundComponent.SoundCue = SlideEffectInfo.Sound;
    }
    //return;    
}

simulated event SpawnedByKismet()
{
    // End:0x2C
    if(StaticMeshComponent.bNotifyRigidBodyCollision)
    {
        SetPhysicalCollisionProperties();
    }
    InitialLocation = Location;
    InitialRotation = Rotation;
    //return;    
}

simulated event ReplicatedEvent(name VarName)
{
    local Vector NewDrawScale3D;

    // End:0x47
    if(VarName == 'bWakeOnLevelStart')
    {
        // End:0x44
        if(bWakeOnLevelStart)
        {
            StaticMeshComponent.WakeRigidBody();
        }        
    }
    else
    {
        // End:0x8E
        if(VarName == 'ReplicatedDrawScale3D')
        {
            NewDrawScale3D = ReplicatedDrawScale3D / 1000;
            SetDrawScale3D(NewDrawScale3D);            
        }
        else
        {
            super.ReplicatedEvent(VarName);
        }
    }
    //return;    
}

event ApplyImpulse(Vector ImpulseDir, float ImpulseMag, Vector HitLocation, optional TraceHitInfo HitInfo, optional class<DamageType> DamageType)
{
    local Vector AppliedImpulse;

    AppliedImpulse
    Normal(ImpulseDir) * ImpulseMag;
    // End:0xA8
    if(HitInfo.HitComponent != none)
    {
        HitInfo.HitComponent.AddImpulse(AppliedImpulse, HitLocation, HitInfo.BoneName);        
    }
    else
    {
        CollisionComponent.AddImpulse(AppliedImpulse, HitLocation);
    }
    //return;    
}

event TakeDamage(float Damage, Controller EventInstigator, Vector HitLocation, Vector Momentum, class<DamageType> DamageType, optional TraceHitInfo HitInfo, optional IDamageCauser DamageCauser, optional DamagePipeline Pipeline)
{
    Damage
    EventInstigator
    HitLocation
    Momentum
    DamageType
    HitInfo
    DamageCauser
    Pipeline    
    // End:0x172
    if(bDamageAppliesImpulse && DamageType.default.KDamageImpulse > float(0))
    {
        // End:0xA1
        if(VSize(Momentum) < 0.001)
        {
            return;
        }
        // End:0xF1
        if(GetPipelineDamageType(Pipeline) != none)
        {
            Momentum *= GetPipelineDamageType(Pipeline).GetRigidBodyMomentumScale();            
        }
        else
        {
            Momentum = Normal(Momentum) * DamageType.default.KDamageImpulse;
        }
        ApplyImpulse(Momentum, DamageType.default.KDamageImpulse, HitLocation, HitInfo, DamageType);
    }
    //return;    
}

simulated function TakeRadiusDamage(Controller InstigatedBy, float BaseDamage, float DamageRadius, class<DamageType> DamageType, float Momentum, Vector HurtOrigin, bool bFullDamage, IDamageCauser DamageCauser, optional float DamageFalloffExponent = 1, optional DamagePipeline Pipeline)
{
    UnknownLocal_1
    0
    J0x11:

    // End:0xA2 [Loop If]
    if(UnknownLocal_1 < GeneratedEvents.Length)
    {
        UnknownLocal_3 = SeqEvent_TakeDamage(GeneratedEvents[UnknownLocal_1]);
        // End:0x98
        if(UnknownLocal_3 != none)
        {
            UnknownLocal_3.HandleDamage(self, InstigatedBy, DamageType, GetPipelineDamageType(Pipeline), BaseDamage);
        }
        ++ UnknownLocal_1;
        // [Loop Continue]
        goto J0x11;
    }
    // End:0xF2
    if(GetPipelineDamageType(Pipeline) != none)
    {
        Momentum *= GetPipelineDamageType(Pipeline).GetRigidBodyMomentumScale();        
    }
    else
    {
        Momentum = DamageType.default.RadialDamageImpulse;
    }
    // End:0x1AB
    if((bDamageAppliesImpulse && Momentum > float(0)) && int(Role) == int(ROLE_Authority))
    {
        CollisionComponent.AddRadialImpulse(HurtOrigin, DamageRadius, Momentum, 1, DamageType.default.bRadialDamageVelChange);
    }
    //return;    
}

simulated function OnToggle(SeqAct_Toggle Action)
{
    // End:0x57
    if(Action.InputLinks[0].bHasImpulse)
    {
        StaticMeshComponent.WakeRigidBody();
    }
    //return;    
}

simulated function OnTeleport(SeqAct_Teleport inAction)
{
    local array<Object> objVars;

    inAction.GetObjectVars(objVars, "Destination");
    UnknownLocal_1 = 0;
    J0x3C:

    // End:0x85 [Loop If]
    if((UnknownLocal_1 < objVars.Length) && UnknownLocal_3 == none)
    {
        UnknownLocal_3 = Actor(objVars[UnknownLocal_1]);
        ++ UnknownLocal_1;
        // [Loop Continue]
        goto J0x3C;
    }
    // End:0x110
    if(UnknownLocal_3 != none)
    {
        StaticMeshComponent.SetRBPosition(UnknownLocal_3.Location);
        StaticMeshComponent.SetRBRotation(UnknownLocal_3.Rotation);
        PlayTeleportEffect(false, true);
    }
    //return;    
}

simulated function Reset()
{
    StaticMeshComponent.SetRBLinearVelocity(vect(0, 0, 0));
    StaticMeshComponent.SetRBAngularVelocity(vect(0, 0, 0));
    StaticMeshComponent.SetRBPosition(InitialLocation);
    StaticMeshComponent.SetRBRotation(InitialRotation);
    // End:0xDE
    if(!bWakeOnLevelStart)
    {
        StaticMeshComponent.PutRigidBodyToSleep();        
    }
    else
    {
        StaticMeshComponent.WakeRigidBody();
    }
    ResolveRBState();
    bForceNetUpdate = true;
    super(Actor).Reset();
    //return;    
}

defaultproperties
{
    bDamageAppliesImpulse=true
    bNeedsRBStateReplication=true
    bDisableClientSidePawnInteractions=true
    StayUprightTorqueFactor=1000
    StayUprightMaxTorque=1500
    MaxPhysicsVelocity=350
    NetRelevantDistanceSquared=1048576
    ReplicatedDrawScale3D=(X=1000,Y=1000,Z=1000)
    begin object name=StaticMeshComponent0 class=StaticMeshComponent
        WireframeColor=(B=128,G=255,R=0,A=255)
        LightEnvironment=DynamicLightEnvironmentComponent'Default__KActor.MyLightEnvironment'
        RBChannel=ERBCollisionChannel.RBCC_GameplayPhysics
        BlockRigidBody=true
        bBlockFootPlacement=false
        RBCollideWithChannels=(Default=true,GameplayPhysics=true,EffectPhysics=true,BlockingVolume=true)
    object end
    // Reference: StaticMeshComponent'Default__KActor.StaticMeshComponent0'
    StaticMeshComponent=StaticMeshComponent0
    LightEnvironment=DynamicLightEnvironmentComponent'Default__KActor.MyLightEnvironment'
    bPawnCanBaseOn=false
    bSafeBaseIfAsleep=true
    Components(0)=DynamicLightEnvironmentComponent'Default__KActor.MyLightEnvironment'
    begin object name=StaticMeshComponent0 class=StaticMeshComponent
        WireframeColor=(B=128,G=255,R=0,A=255)
        LightEnvironment=DynamicLightEnvironmentComponent'Default__KActor.MyLightEnvironment'
        RBChannel=ERBCollisionChannel.RBCC_GameplayPhysics
        BlockRigidBody=true
        bBlockFootPlacement=false
        RBCollideWithChannels=(Default=true,GameplayPhysics=true,EffectPhysics=true,BlockingVolume=true)
    object end
    // Reference: StaticMeshComponent'Default__KActor.StaticMeshComponent0'
    Components(1)=StaticMeshComponent0
    Physics=EPhysics.PHYS_RigidBody
    TickGroup=ETickingGroup.TG_PostAsyncWork
    bNoDelete=true
    bAlwaysRelevant=true
    bUpdateSimulatedPosition=true
    bNetInitialRotation=true
    bBlocksNavigation=true
    bCollideActors=true
    bBlockActors=true
    bProjTarget=true
    bBlocksTeleport=true
    bNoEncroachCheck=true
    begin object name=StaticMeshComponent0 class=StaticMeshComponent
        WireframeColor=(B=128,G=255,R=0,A=255)
        LightEnvironment=DynamicLightEnvironmentComponent'Default__KActor.MyLightEnvironment'
        RBChannel=ERBCollisionChannel.RBCC_GameplayPhysics
        BlockRigidBody=true
        bBlockFootPlacement=false
        RBCollideWithChannels=(Default=true,GameplayPhysics=true,EffectPhysics=true,BlockingVolume=true)
    object end
    // Reference: StaticMeshComponent'Default__KActor.StaticMeshComponent0'
    CollisionComponent=StaticMeshComponent0
}