/*******************************************************************************
 * LandscapeComponent generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class LandscapeComponent extends PrimitiveComponent
    native(Terrain)
    hidecategories(Mobile);

struct native WeightmapLayerAllocationInfo
{
    var name LayerName;
    var byte WeightmapTextureIndex;
    var byte WeightmapTextureChannel;

    structdefaultproperties
    {
        LayerName=None
        WeightmapTextureIndex=0
        WeightmapTextureChannel=0
    }
};

var const int SectionBaseX;
var const int SectionBaseY;
var const int ComponentSizeQuads;
var const int SubsectionSizeQuads;
var const int NumSubsections;
var MaterialInstanceConstant MaterialInstance;
var private const array<WeightmapLayerAllocationInfo> WeightmapLayerAllocations;
var private const array<Texture2D> WeightmapTextures;
var Vector4 WeightmapScaleBias;
var float WeightmapSubsectionOffset;
var Vector4 HeightmapScaleBias;
var private const Texture2D HeightmapTexture;
var const BoxSphereBounds CachedBoxSphereBounds;
var int StaticLightingResolution;
var private const array<ShadowMap2D> ShadowMaps;
var const array<Guid> IrrelevantLights;
var private native const LightMapRef LightMap;
var private native Pointer EditToolRenderData;
var const int CollisionMipLevel;
var private native Pointer PlatformData;
var native const int PlatformDataSize;

defaultproperties
{
    WeightmapScaleBias=(X=0,Y=0,Z=0,W=1)
    HeightmapScaleBias=(X=0,Y=0,Z=0,W=1)
    bAllowCullDistanceVolume=false
    bUseAsOccluder=true
    bAcceptsStaticDecals=true
    CastShadow=true
    bForceDirectLightMap=true
    bAcceptsLights=true
    bUsePrecomputedShadows=true
    CollideActors=true
    BlockActors=true
    BlockZeroExtent=true
    BlockNonZeroExtent=true
    BlockRigidBody=true
    LightingChannels=(bInitialized=true,Static=true)
}