/*******************************************************************************
 * MaterialExpressionBlendModeBase generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class MaterialExpressionBlendModeBase extends MaterialExpression within Material
    abstract
    native(Material)
    collapsecategories
    hidecategories(Mobile,Object,Object);

var ExpressionInput Base;
var ExpressionInput Blend;
