/*******************************************************************************
 * OnlineGameInterface generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
interface OnlineGameInterface extends Interface
    abstract
    hidecategories(Mobile);

var delegate<OnCreateOnlineGameComplete> __OnCreateOnlineGameComplete__Delegate;
var delegate<OnUpdateOnlineGameComplete> __OnUpdateOnlineGameComplete__Delegate;
var delegate<OnDestroyOnlineGameComplete> __OnDestroyOnlineGameComplete__Delegate;
var delegate<OnFindOnlineGamesComplete> __OnFindOnlineGamesComplete__Delegate;
var delegate<OnCancelFindOnlineGamesComplete> __OnCancelFindOnlineGamesComplete__Delegate;
var delegate<OnQosStatusChanged> __OnQosStatusChanged__Delegate;
var delegate<OnJoinOnlineGameComplete> __OnJoinOnlineGameComplete__Delegate;
var delegate<OnRegisterPlayerComplete> __OnRegisterPlayerComplete__Delegate;
var delegate<OnUnregisterPlayerComplete> __OnUnregisterPlayerComplete__Delegate;
var delegate<OnStartOnlineGameComplete> __OnStartOnlineGameComplete__Delegate;
var delegate<OnEndOnlineGameComplete> __OnEndOnlineGameComplete__Delegate;
var delegate<OnArbitrationRegistrationComplete> __OnArbitrationRegistrationComplete__Delegate;
var delegate<OnGameInviteAccepted> __OnGameInviteAccepted__Delegate;
var delegate<OnGameInviteProcessingStarted> __OnGameInviteProcessingStarted__Delegate;
var delegate<OnRecalculateSkillRatingComplete> __OnRecalculateSkillRatingComplete__Delegate;
var delegate<OnMigrateOnlineGameComplete> __OnMigrateOnlineGameComplete__Delegate;
var delegate<OnJoinMigratedOnlineGameComplete> __OnJoinMigratedOnlineGameComplete__Delegate;

function bool CreateOnlineGame(byte HostingPlayerNum, name SessionName, OnlineGameSettings NewGameSettings)
{
    //return ReturnValue;    
}

delegate OnCreateOnlineGameComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddCreateOnlineGameCompleteDelegate(delegate<OnCreateOnlineGameComplete> CreateOnlineGameCompleteDelegate)
{
    //return;    
}

function ClearCreateOnlineGameCompleteDelegate(delegate<OnCreateOnlineGameComplete> CreateOnlineGameCompleteDelegate)
{
    //return;    
}

function bool UpdateOnlineGame(name SessionName, OnlineGameSettings UpdatedGameSettings, optional bool bShouldRefreshOnlineData = false)
{
    ReturnValue    
}

delegate OnUpdateOnlineGameComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddUpdateOnlineGameCompleteDelegate(delegate<OnUpdateOnlineGameComplete> UpdateOnlineGameCompleteDelegate)
{
    //return;    
}

function ClearUpdateOnlineGameCompleteDelegate(delegate<OnUpdateOnlineGameComplete> UpdateOnlineGameCompleteDelegate)
{
    //return;    
}

function OnlineGameSettings GetGameSettings(name SessionName)
{
    //return ReturnValue;    
}

function bool DestroyOnlineGame(name SessionName)
{
    //return ReturnValue;    
}

delegate OnDestroyOnlineGameComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddDestroyOnlineGameCompleteDelegate(delegate<OnDestroyOnlineGameComplete> DestroyOnlineGameCompleteDelegate)
{
    //return;    
}

function ClearDestroyOnlineGameCompleteDelegate(delegate<OnDestroyOnlineGameComplete> DestroyOnlineGameCompleteDelegate)
{
    //return;    
}

function bool FindOnlineGames(byte SearchingPlayerNum, OnlineGameSearch SearchSettings)
{
    //return ReturnValue;    
}

delegate OnFindOnlineGamesComplete(bool bWasSuccessful)
{
    //return;    
}

function AddFindOnlineGamesCompleteDelegate(delegate<OnFindOnlineGamesComplete> FindOnlineGamesCompleteDelegate)
{
    //return;    
}

function ClearFindOnlineGamesCompleteDelegate(delegate<OnFindOnlineGamesComplete> FindOnlineGamesCompleteDelegate)
{
    //return;    
}

function bool CancelFindOnlineGames()
{
    //return ReturnValue;    
}

delegate OnCancelFindOnlineGamesComplete(bool bWasSuccessful)
{
    //return;    
}

function AddCancelFindOnlineGamesCompleteDelegate(delegate<OnCancelFindOnlineGamesComplete> CancelFindOnlineGamesCompleteDelegate)
{
    //return;    
}

function ClearCancelFindOnlineGamesCompleteDelegate(delegate<OnCancelFindOnlineGamesComplete> CancelFindOnlineGamesCompleteDelegate)
{
    //return;    
}

delegate OnQosStatusChanged(int NumComplete, int NumTotal)
{
    //return;    
}

function AddQosStatusChangedDelegate(delegate<OnQosStatusChanged> QosStatusChangedDelegate)
{
    //return;    
}

function ClearQosStatusChangedDelegate(delegate<OnQosStatusChanged> QosStatusChangedDelegate)
{
    //return;    
}

function bool ReadPlatformSpecificSessionInfo(const out OnlineGameSearchResult DesiredGame, out byte PlatformSpecificInfo[80])
{
    //return ReturnValue;    
}

function bool ReadPlatformSpecificSessionInfoBySessionName(name SessionName, out byte PlatformSpecificInfo[80])
{
    //return ReturnValue;    
}

function bool BindPlatformSpecificSessionToSearch(byte SearchingPlayerNum, OnlineGameSearch SearchSettings, byte PlatformSpecificInfo[80])
{
    //return ReturnValue;    
}

function OnlineGameSearch GetGameSearch()
{
    //return ReturnValue;    
}

function bool FreeSearchResults(optional OnlineGameSearch Search)
{
    ReturnValue    
}

function bool QueryNonAdvertisedData(int StartAt, int NumberToQuery)
{
    //return ReturnValue;    
}

function bool JoinOnlineGame(byte PlayerNum, name SessionName, const out OnlineGameSearchResult DesiredGame)
{
    //return ReturnValue;    
}

delegate OnJoinOnlineGameComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddJoinOnlineGameCompleteDelegate(delegate<OnJoinOnlineGameComplete> JoinOnlineGameCompleteDelegate)
{
    //return;    
}

function ClearJoinOnlineGameCompleteDelegate(delegate<OnJoinOnlineGameComplete> JoinOnlineGameCompleteDelegate)
{
    //return;    
}

function bool GetResolvedConnectString(name SessionName, out string ConnectInfo)
{
    //return ReturnValue;    
}

function bool RegisterPlayer(name SessionName, UniqueNetId PlayerID, bool bWasInvited)
{
    //return ReturnValue;    
}

function bool RegisterPlayers(name SessionName, const out array<UniqueNetId> Players)
{
    //return ReturnValue;    
}

delegate OnRegisterPlayerComplete(name SessionName, UniqueNetId PlayerID, bool bWasSuccessful)
{
    //return;    
}

function AddRegisterPlayerCompleteDelegate(delegate<OnRegisterPlayerComplete> RegisterPlayerCompleteDelegate)
{
    //return;    
}

function ClearRegisterPlayerCompleteDelegate(delegate<OnRegisterPlayerComplete> RegisterPlayerCompleteDelegate)
{
    //return;    
}

function bool UnregisterPlayer(name SessionName, UniqueNetId PlayerID)
{
    //return ReturnValue;    
}

function bool UnregisterPlayers(name SessionName, const out array<UniqueNetId> Players)
{
    //return ReturnValue;    
}

delegate OnUnregisterPlayerComplete(name SessionName, UniqueNetId PlayerID, bool bWasSuccessful)
{
    //return;    
}

function AddUnregisterPlayerCompleteDelegate(delegate<OnUnregisterPlayerComplete> UnregisterPlayerCompleteDelegate)
{
    //return;    
}

function ClearUnregisterPlayerCompleteDelegate(delegate<OnUnregisterPlayerComplete> UnregisterPlayerCompleteDelegate)
{
    //return;    
}

function bool StartOnlineGame(name SessionName)
{
    //return ReturnValue;    
}

delegate OnStartOnlineGameComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddStartOnlineGameCompleteDelegate(delegate<OnStartOnlineGameComplete> StartOnlineGameCompleteDelegate)
{
    //return;    
}

function ClearStartOnlineGameCompleteDelegate(delegate<OnStartOnlineGameComplete> StartOnlineGameCompleteDelegate)
{
    //return;    
}

function bool EndOnlineGame(name SessionName)
{
    //return ReturnValue;    
}

delegate OnEndOnlineGameComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddEndOnlineGameCompleteDelegate(delegate<OnEndOnlineGameComplete> EndOnlineGameCompleteDelegate)
{
    //return;    
}

function ClearEndOnlineGameCompleteDelegate(delegate<OnEndOnlineGameComplete> EndOnlineGameCompleteDelegate)
{
    //return;    
}

function bool RegisterForArbitration(name SessionName)
{
    //return ReturnValue;    
}

delegate OnArbitrationRegistrationComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddArbitrationRegistrationCompleteDelegate(delegate<OnArbitrationRegistrationComplete> ArbitrationRegistrationCompleteDelegate)
{
    //return;    
}

function ClearArbitrationRegistrationCompleteDelegate(delegate<OnArbitrationRegistrationComplete> ArbitrationRegistrationCompleteDelegate)
{
    //return;    
}

function array<OnlineArbitrationRegistrant> GetArbitratedPlayers(name SessionName)
{
    //return ReturnValue;    
}

delegate OnGameInviteAccepted(const out OnlineGameSearchResult InviteResult)
{
    //return;    
}

function AddGameInviteAcceptedDelegate(byte LocalUserNum, delegate<OnGameInviteAccepted> GameInviteAcceptedDelegate)
{
    //return;    
}

function ClearGameInviteAcceptedDelegate(byte LocalUserNum, delegate<OnGameInviteAccepted> GameInviteAcceptedDelegate)
{
    //return;    
}

function bool AcceptGameInvite(byte LocalUserNum, name SessionName)
{
    //return ReturnValue;    
}

delegate OnGameInviteProcessingStarted()
{
    //return;    
}

function AddGameInviteProcessingStartedDelegate(delegate<OnGameInviteProcessingStarted> GameInviteProcessingStartedDelegate)
{
    //return;    
}

function ClearGameInviteProcessingStartedDelegate(delegate<OnGameInviteProcessingStarted> GameInviteProcessingStartedDelegate)
{
    //return;    
}

function bool RecalculateSkillRating(name SessionName, const out array<UniqueNetId> Players)
{
    //return ReturnValue;    
}

delegate OnRecalculateSkillRatingComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddRecalculateSkillRatingCompleteDelegate(delegate<OnRecalculateSkillRatingComplete> RecalculateSkillRatingCompleteDelegate)
{
    //return;    
}

function ClearRecalculateSkillRatingCompleteDelegate(delegate<OnRecalculateSkillRatingComplete> RecalculateSkillRatingGameCompleteDelegate)
{
    //return;    
}

function bool MigrateOnlineGame(byte HostingPlayerNum, name SessionName)
{
    //return ReturnValue;    
}

delegate OnMigrateOnlineGameComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddMigrateOnlineGameCompleteDelegate(delegate<OnMigrateOnlineGameComplete> MigrateOnlineGameCompleteDelegate)
{
    //return;    
}

function ClearMigrateOnlineGameCompleteDelegate(delegate<OnMigrateOnlineGameComplete> MigrateOnlineGameCompleteDelegate)
{
    //return;    
}

function bool JoinMigratedOnlineGame(byte PlayerNum, name SessionName, const out OnlineGameSearchResult DesiredGame)
{
    //return ReturnValue;    
}

delegate OnJoinMigratedOnlineGameComplete(name SessionName, bool bWasSuccessful)
{
    //return;    
}

function AddJoinMigratedOnlineGameCompleteDelegate(delegate<OnJoinMigratedOnlineGameComplete> JoinMigratedOnlineGameCompleteDelegate)
{
    //return;    
}

function ClearJoinMigratedOnlineGameCompleteDelegate(delegate<OnJoinMigratedOnlineGameComplete> JoinMigratedOnlineGameCompleteDelegate)
{
    //return;    
}

function CancelNATNegotiation()
{
    //return;    
}

function bool HasPendingBootInvite()
{
    //return ReturnValue;    
}
