/*******************************************************************************
 * ParticleModuleSubUVMovie generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ParticleModuleSubUVMovie extends ParticleModuleSubUV
    native(Particle)
    editinlinenew
    hidecategories(Mobile,Object,Object,Object,Object,SubUV);

var(FlipBook) bool bUseEmitterTime;
var(FlipBook) RawDistributionFloat FrameRate;
var(FlipBook) int StartingFrame;

defaultproperties
{
    FrameRate=/*ERROR: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at UELib.Core.UDefaultProperty.DeserializeTagUE3()
   at UELib.Core.UDefaultProperty.Deserialize()
   at UELib.Core.UDefaultProperty.DeserializeDefaultPropertyValue(PropertyType type, DeserializeFlags& deserializeFlags)
   at UELib.Core.UDefaultProperty.TryDeserializeDefaultPropertyValue(PropertyType type, DeserializeFlags& deserializeFlags)*/
    StartingFrame=1
    SubImageIndex=(Distribution=DistributionFloatConstant'Default__ParticleModuleSubUVMovie.DistributionSubImage')
}