/*******************************************************************************
 * ParticleModuleParameterDynamic generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ParticleModuleParameterDynamic extends ParticleModuleParameterBase
    native(Particle)
    editinlinenew
    hidecategories(Mobile,Object,Object,Object);

enum EEmitterDynamicParameterValue
{
    EDPV_UserSet,
    EDPV_VelocityX,
    EDPV_VelocityY,
    EDPV_VelocityZ,
    EDPV_VelocityMag,
    EDPV_MAX
};

struct native EmitterDynamicParameter
{
    var() editconst name ParamName;
    var() bool bUseEmitterTime;
    var() bool bSpawnTimeOnly;
    var() ParticleModuleParameterDynamic.EEmitterDynamicParameterValue ValueMethod;
    var() bool bScaleVelocityByParamValue;
    var() RawDistributionFloat ParamValue;

    structdefaultproperties
    {
        ParamName=None
        bUseEmitterTime=false
        bSpawnTimeOnly=false
        ValueMethod=EEmitterDynamicParameterValue.EDPV_UserSet
        bScaleVelocityByParamValue=false
        ParamValue=(Distribution=none,Type=0,Op=0,LookupTableNumElements=0,LookupTableChunkSize=0,LookupTable=none,LookupTableTimeScale=0,LookupTableStartTime=0)
    }
};

var() editfixedsize array<EmitterDynamicParameter> DynamicParams;
var int UpdateFlags;
var bool bUsesVelocity;

defaultproperties
{
    DynamicParams(0)=(ParamName=None,bUseEmitterTime=false,bSpawnTimeOnly=false,ValueMethod=EEmitterDynamicParameterValue.EDPV_UserSet,bScaleVelocityByParamValue=false,ParamValue=/*ERROR: System.ArgumentException: Requested value '*' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at UELib.Core.UDefaultProperty.DeserializeTagUE3()
   at UELib.Core.UDefaultProperty.Deserialize()
   at UELib.Core.UDefaultProperty.DeserializeDefaultPropertyValue(PropertyType type, DeserializeFlags& deserializeFlags)
   at UELib.Core.UDefaultProperty.TryDeserializeDefaultPropertyValue(PropertyType type, DeserializeFlags& deserializeFlags)*/,LookupTableTimeScale=0,LookupTableStartTime=0)
    DynamicParams(1)=none
    DynamicParams(2)=(ParamName=None,bUseEmitterTime=false,bSpawnTimeOnly=false,ValueMethod=EEmitterDynamicParameterValue.EDPV_UserSet,bScaleVelocityByParamValue=false,ParamValue=/*ERROR: System.ArgumentException: Requested value '*' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at UELib.Core.UDefaultProperty.DeserializeTagUE3()
   at UELib.Core.UDefaultProperty.Deserialize()
   at UELib.Core.UDefaultProperty.DeserializeDefaultPropertyValue(PropertyType type, DeserializeFlags& deserializeFlags)
   at UELib.Core.UDefaultProperty.TryDeserializeDefaultPropertyValue(PropertyType type, DeserializeFlags& deserializeFlags)*/,LookupTableTimeScale=0,LookupTableStartTime=0)
    DynamicParams(3)=none
    bSpawnModule=true
    bUpdateModule=true
}