/*******************************************************************************
 * RB_PrismaticActor generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class RB_PrismaticActor extends RB_ConstraintActor
    placeable
    hidecategories(Mobile,Navigation,MovementReplication);

defaultproperties
{
    ConstraintSetup=RB_PrismaticSetup'Default__RB_PrismaticActor.MyPrismaticSetup'
    ConstraintInstance=RB_ConstraintInstance'Default__RB_PrismaticActor.MyConstraintInstance'
    Components(0)=none
    Components(1)=RB_ConstraintDrawComponent'Default__RB_PrismaticActor.MyConDrawComponent'
    Components(2)=none
}