/*******************************************************************************
 * SeqAct_FlyThroughHasEnded generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class SeqAct_FlyThroughHasEnded extends SequenceAction
    hidecategories(Mobile,Object);

defaultproperties
{
    ObjName="FlyThroughHasEnded"
    ObjCategory="Misc"
}