/*******************************************************************************
 * SeqAct_ToggleHUD generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class SeqAct_ToggleHUD extends SequenceAction
    hidecategories(Mobile,Object);

static event int GetObjClassVersion()
{
    return super(SequenceObject).GetObjClassVersion() + 2;
    //return ReturnValue;    
}

defaultproperties
{
    InputLinks(0)=(LinkDesc="Show",QueuedActivations=0,LinkedOp=none,DrawY=0,OverrideDelta=0,bHidden=false,bMoving=false,bClampedMax=false,bClampedMin=false,bDisabled=false,bDisabledPIE=false,bHasImpulse=false,ActivateDelay=0)
    InputLinks(1)=(LinkDesc="Hide",QueuedActivations=0,LinkedOp=none,DrawY=0,OverrideDelta=0,bHidden=false,bMoving=false,bClampedMax=false,bClampedMin=false,bDisabled=false,bDisabledPIE=false,bHasImpulse=false,ActivateDelay=0)
    InputLinks(2)=(LinkDesc="Toggle",QueuedActivations=0,LinkedOp=none,DrawY=0,OverrideDelta=0,bHidden=false,bMoving=false,bClampedMax=false,bClampedMin=false,bDisabled=false,bDisabledPIE=false,bHasImpulse=false,ActivateDelay=0)
    ObjName="Toggle HUD"
    ObjCategory="Toggle"
}