/*******************************************************************************
 * SeqAct_Switch generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class SeqAct_Switch extends SequenceAction
    native(Sequence)
    hidecategories(Mobile,Object);

var(Action) int LinkCount;
var(Action) int IncrementAmount;
var(Action) bool bLooping;
var(Action) bool bAutoDisableLinks;
var(Action) array<int> Indices;

defaultproperties
{
    LinkCount=1
    IncrementAmount=1
    Indices(0)=1
    OutputLinks(0)=(Links=none,LinkDesc="Link 1",bHasImpulse=false,bDisabled=false,bDisabledPIE=false,bClampedMax=false,bClampedMin=false,bHidden=false,bIsActivated=false,bMoving=false,LinkedOp=none,ActivateDelay=0,DrawY=0,OverrideDelta=0)
    VariableLinks(0)=(ExpectedType='SeqVar_Int',LinkedVariables=none,LinkDesc="Index",LinkVar=None,PropertyName=Indices,bWriteable=false,bSequenceNeverReadsOnlyWritesToThisVar=false,bModifiesLinkedObject=false,bHidden=false,bClampedMax=false,bClampedMin=false,bMoving=false,bAllowAnyType=false,MinVars=1,MaxVars=255,DrawX=0,CachedProperty=none,OverrideDelta=0)
    ObjName="Switch"
    ObjCategory="Switch"
}