/*******************************************************************************
 * SeqAct_MITV_Activate generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class SeqAct_MITV_Activate extends SequenceAction
    hidecategories(Mobile,Object);

var(Action) float DurationOfMITV;

static event int GetObjClassVersion()
{
    return super(SequenceObject).GetObjClassVersion() + 1;
    //return ReturnValue;    
}

event Activated()
{
    // End:0xB0
    foreach LinkedVariables(class'SeqVar_Object', UnknownLocal_1, "MITV")
    {
        UnknownLocal_3 = MaterialInstanceTimeVaryingActor(UnknownLocal_1.GetObjectValue());
        // End:0xAF
        if(UnknownLocal_3 != none)
        {
            // End:0xAF
            if(UnknownLocal_3.MatInst != none)
            {
                UnknownLocal_3.MatInst.SetDuration(DurationOfMITV);
            }
        }        
    }    
    //return;    
}

defaultproperties
{
    bCallHandler=false
    VariableLinks(0)=(ExpectedType='SeqVar_Object',LinkedVariables=none,LinkDesc="MITV",LinkVar=None,PropertyName=Targets,bWriteable=false,bSequenceNeverReadsOnlyWritesToThisVar=false,bModifiesLinkedObject=false,bHidden=false,bClampedMax=false,bClampedMin=false,bMoving=false,bAllowAnyType=false,MinVars=1,MaxVars=255,DrawX=0,CachedProperty=none,OverrideDelta=0)
    ObjName="MITV Activate"
    ObjCategory="Actor"
}