/*******************************************************************************
 * StaticMeshActor generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class StaticMeshActor extends StaticMeshActorBase
    native
    placeable
    hidecategories(Mobile,Navigation,MovementReplication);

var() const editconst export editinline StaticMeshComponent StaticMeshComponent;
var() editoronly bool bDisableAutoBaseOnProcBuilding;

defaultproperties
{
    begin object name=StaticMeshComponent0 class=StaticMeshComponent
        bForceDirectLightMap=true
        bUsePrecomputedShadows=true
    object end
    // Reference: StaticMeshComponent'Default__StaticMeshActor.StaticMeshComponent0'
    StaticMeshComponent=StaticMeshComponent0
    begin object name=StaticMeshComponent0 class=StaticMeshComponent
        bForceDirectLightMap=true
        bUsePrecomputedShadows=true
    object end
    // Reference: StaticMeshComponent'Default__StaticMeshActor.StaticMeshComponent0'
    Components(0)=StaticMeshComponent0
    begin object name=StaticMeshComponent0 class=StaticMeshComponent
        bForceDirectLightMap=true
        bUsePrecomputedShadows=true
    object end
    // Reference: StaticMeshComponent'Default__StaticMeshActor.StaticMeshComponent0'
    CollisionComponent=StaticMeshComponent0
}