/*******************************************************************************
 * TextureFlipBook generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class TextureFlipBook extends Texture2D
    native(Texture)
    forcescriptorder(true)
    hidecategories(Mobile,Object,Object);

enum TextureFlipBookMethod
{
    TFBM_UL_ROW,
    TFBM_UL_COL,
    TFBM_UR_ROW,
    TFBM_UR_COL,
    TFBM_LL_ROW,
    TFBM_LL_COL,
    TFBM_LR_ROW,
    TFBM_LR_COL,
    TFBM_RANDOM,
    TFBM_MAX
};

var private native const noexport Pointer VfTable_FTickableObject;
var const transient float TimeIntoMovie;
var const transient float TimeSinceLastFrame;
var const transient float HorizontalScale;
var const transient float VerticalScale;
var const bool bPaused;
var const bool bStopped;
var(FlipBook) bool bLooping;
var(FlipBook) bool bAutoPlay;
var(FlipBook) int HorizontalImages;
var(FlipBook) int VerticalImages;
var(FlipBook) TextureFlipBook.TextureFlipBookMethod FBMethod;
var(FlipBook) float FrameRate;
var private float FrameTime;
var const transient int CurrentRow;
var const transient int CurrentColumn;
var const transient float RenderOffsetU;
var const transient float RenderOffsetV;
var native const Pointer ReleaseResourcesFence;

// Export UTextureFlipBook::execPlay(FFrame&, void* const)
native function Play();

// Export UTextureFlipBook::execPause(FFrame&, void* const)
native function Pause();

// Export UTextureFlipBook::execStop(FFrame&, void* const)
native function Stop();

// Export UTextureFlipBook::execSetCurrentFrame(FFrame&, void* const)
native function SetCurrentFrame(int Row, int Col);

defaultproperties
{
    bLooping=true
    bAutoPlay=true
    HorizontalImages=1
    VerticalImages=1
    FrameRate=4
    FrameTime=0.25
    AddressX=TextureAddress.TA_Clamp
    AddressY=TextureAddress.TA_Clamp
}