/*******************************************************************************
 * UIDataStorePublisher generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class UIDataStorePublisher extends UIDataStoreSubscriber
    abstract
    native(UIPrivate)
    hidecategories(Mobile);

// Export UUIDataStorePublisher::execSaveSubscriberValue(FFrame&, void* const)
native function bool SaveSubscriberValue(out array<UIDataStore> out_BoundDataStores, optional int BindingIndex = -1);
