/*******************************************************************************
 * UIPropertyDataProvider generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class UIPropertyDataProvider extends UIDataProvider
    abstract
    transient
    native(UIPrivate)
    config(Engine)
    hidecategories(Mobile,Object,UIRoot);

var const array< class<Property> > ComplexPropertyTypes;
var delegate<CanSupportComplexPropertyType> __CanSupportComplexPropertyType__Delegate;

delegate bool CanSupportComplexPropertyType(Property UnsupportedProperty)
{
    //return ReturnValue;    
}

event bool GetCustomPropertyValue(out UIProviderScriptFieldValue PropertyValue, optional int ArrayIndex = -1)
{
    ReturnValue    
}

defaultproperties
{
    ComplexPropertyTypes(0)=class'StructProperty'
    ComplexPropertyTypes(1)=class'MapProperty'
    ComplexPropertyTypes(2)=class'ArrayProperty'
    ComplexPropertyTypes(3)=class'DelegateProperty'
}