/*******************************************************************************
 * WindPointSourceComponent generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WindPointSourceComponent extends WindDirectionalSourceComponent
    native
    editinlinenew
    collapsecategories
    hidecategories(Mobile,Object,Object);

var const export editinline DrawSphereComponent PreviewRadiusComponent;
var() interp float Radius;

defaultproperties
{
    Radius=1024
}