/*******************************************************************************
 * Action_SwoopAttack generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Action_SwoopAttack extends WillowActionSequencePawn
    native(AI)
    editinlinenew
    hidecategories(Mobile,Object,HideMe,ActionSequence,LoadBalance,Movement);

enum ESwoopOffset
{
    SwoopOffset_Left,
    SwoopOffset_Right,
    SwoopOffset_Random,
    SwoopOffset_MAX
};

struct native SwoopAttackData
{
    var bool bTriggered;
    var() const bool bCacheTargetLocation;
    var() const float Distance;

    structdefaultproperties
    {
        bTriggered=false
        bCacheTargetLocation=false
        Distance=0
    }
};

var(Swoop) const float SwoopFarDistance;
var(Swoop) const float SwoopFarHeight;
var(Swoop) const float SwoopCloseDistance;
var(Swoop) const float SwoopCloseHeight;
var(Swoop) const bool bShootTarget;
var(Offset) const bool bUseOffset;
var transient bool bFoundAttackOffset;
var transient bool bCacheTargetLoc;
var const float SwoopAttackDistance;
var(Swoop) array<SwoopAttackData> SwoopAttackDistances;
var(Offset) const float Offset;
var(Offset) const Action_SwoopAttack.ESwoopOffset OffsetDirection;
var transient Action_SwoopAttack.ESwoopOffset Direction;
var transient Vector AttackOffset;
var transient float ClosestAttackDist;
var transient Vector LastAttackLocation;
var transient Vector CachedTargetLoc;

event Init()
{
    super.Init();
    ClosestAttackDist = 999999;
    UnknownLocal_1 = 0;
    J0x20:

    // End:0x7B [Loop If]
    if(UnknownLocal_1 < SwoopAttackDistances.Length)
    {
        ClosestAttackDist = float(Min(int(SwoopAttackDistances[UnknownLocal_1].Distance), int(ClosestAttackDist)));
        ++ UnknownLocal_1;
        // [Loop Continue]
        goto J0x20;
    }
    //return;    
}

event name CanRun()
{
    local name SuperVal;

    SuperVal = super(ActionSequence).CanRun();
    // End:0x35
    if(SuperVal != 'None')
    {
        return SuperVal;
    }
    // End:0x4E
    if(Target == none)
    {
        return 'NoTarget';
    }
    // End:0x67
    if(!IsFlying())
    {
        return 'NotFlying';
    }
    return 'None';
    //return ReturnValue;    
}

event Start()
{
    super.Start();
    bCacheTargetLoc = false;
    SetAllTriggered(false);
    bFoundAttackOffset = false;
    GotoState('MoveFurther');
    SetPawnMovementSpeed(1);
    MyWillowMind.bWantsToFireWeapon = bShootTarget;
    // End:0xC4
    if(bUseOffset)
    {
        // End:0xB1
        if(int(OffsetDirection) == int(2))
        {
            Direction = ((FRand() > 0.5) ? 0 : 1);            
        }
        else
        {
            Direction = OffsetDirection;
        }
    }
    //return;    
}

event Stop()
{
    super.Stop();
    MyWillowMind.bWantsToFireWeapon = false;
    //return;    
}

event bool PathFind()
{
    return false;
    //return ReturnValue;    
}

function float GetDistToTarget()
{
    local Vector rslt;

    rslt = MyWillowPawn.Location - Target.Location;
    rslt.Z = 0;
    return VSize(rslt);
    //return ReturnValue;    
}

function SetAllTriggered(bool bTriggered)
{
    UnknownLocal_1 = 0;
    J0x07:

    // End:0x53 [Loop If]
    if(UnknownLocal_1 < SwoopAttackDistances.Length)
    {
        SwoopAttackDistances[UnknownLocal_1].bTriggered = bTriggered;
        ++ UnknownLocal_1;
        // [Loop Continue]
        goto J0x07;
    }
    //return;    
}

function Vector GetGoalLocation(optional bool bForce = false)
{
    local Vector ToLeft, ToTarget, TheOffset, TargetLoc;

    TargetLoc
    ((bCacheTargetLoc) ? CachedTargetLoc : Target.Location)
    // End:0x67
    if(bFoundAttackOffset)
    {
        return TargetLoc + AttackOffset;
    }
    AttackOffset = vect(0, 0, 0);
    // End:0xCE
    if(int(Target.Physics) != int(4))
    {
        AttackOffset.Z += SwoopCloseHeight;
    }
    // End:0x1DA
    if(bUseOffset)
    {
        ToTarget = Target.Location - MyWillowPawn.Location;
        ToTarget.Z = 0;
        ToTarget = Normal(ToTarget);
        ToLeft = ToTarget Cross vect(0, 0, 1);
        TheOffset = ((int(Direction) == int(0)) ? ToLeft * Offset : -ToLeft * Offset);
        AttackOffset += TheOffset;
    }
    bFoundAttackOffset = true;
    return TargetLoc + AttackOffset;
    //return ReturnValue;    
}

function float GetDistToGoal()
{
    local Vector rslt;

    rslt = MyWillowPawn.Location - (GetGoalLocation());
    rslt.Z = 0;
    return VSize(rslt);
    //return ReturnValue;    
}

state MoveFurther
{
    event Update()
    {
        UnknownLocal_1 = GetDistToTarget();
        // End:0x86
        if((UnknownLocal_1 > SwoopFarDistance) || MyNavHandle.bFlightFullyBlocked)
        {
            // End:0x65
            if(UnknownLocal_1 < ClosestAttackDist)
            {
                SetAllTriggered(true);
            }
            TriggerBehavior('Turn');
            GotoState('MoveCloser');
        }
        //return;        
    }

    event bool PathFind()
    {
        local Vector ToTarget, GoalLoc;

        ToTarget = Target.Location - MyWillowPawn.Location;
        ToTarget.Z = 0;
        ToTarget = Normal(ToTarget);
        GoalLoc = Target.Location - ((ToTarget * SwoopFarDistance) * 1.1);
        // End:0x114
        if(int(Target.Physics) != int(4))
        {
            GoalLoc.Z += SwoopFarHeight;
        }
        CreateVectorPath(GoalLoc);
        // End:0x1A8
        if((!PathIsValid() && MyNavHandle.WantsToFly()) && int(MyNavHandle.FlightMode) == int(4))
        {
            MyNavHandle.FlightMode = 1;
        }
        return true;
        //return ReturnValue;        
    }
    stop;    
}

state MoveCloser
{
    event Update()
    {
        UnknownLocal_1 = 0;
        UnknownLocal_3 = GetDistToGoal();
        UnknownLocal_5 = 0;
        J0x1E:

        // End:0x185 [Loop If]
        if(UnknownLocal_5 < SwoopAttackDistances.Length)
        {
            // End:0x14E
            if(!SwoopAttackDistances[UnknownLocal_5].bTriggered && UnknownLocal_3 < SwoopAttackDistances[UnknownLocal_5].Distance)
            {
                // End:0xD3
                if(!MyWillowPawn.ReachedPoint(LastAttackLocation, none))
                {
                    TriggerBehavior(BehaviorOutputs[UnknownLocal_5 + 2]);
                }
                SwoopAttackDistances[UnknownLocal_5].bTriggered = true;
                CachedTargetLoc = Target.Location;
                bCacheTargetLoc = SwoopAttackDistances[UnknownLocal_5].bCacheTargetLocation;
            }
            // End:0x17B
            if(SwoopAttackDistances[UnknownLocal_5].bTriggered)
            {
                ++ UnknownLocal_1;
            }
            ++ UnknownLocal_5;
            // [Loop Continue]
            goto J0x1E;
        }
        // End:0x1C1
        if(UnknownLocal_1 >= SwoopAttackDistances.Length)
        {
            LastAttackLocation = MyWillowPawn.Location;
        }
        // End:0x1DF
        if(UnknownLocal_3 < SwoopCloseDistance)
        {
            Finish();
        }
        //return;        
    }

    event bool PathFind()
    {
        CreateVectorPath(GetGoalLocation());
        return true;
        //return ReturnValue;        
    }
    stop;    
}

defaultproperties
{
    SwoopFarDistance=3000
    SwoopFarHeight=2000
    SwoopCloseDistance=500
    SwoopCloseHeight=300
    bShootTarget=true
    SwoopAttackDistances(0)=(bTriggered=false,bCacheTargetLocation=false,Distance=1500)
    BehaviorOutputs=/* Array type was not detected. */
}