/*******************************************************************************
 * AttackLocation_LineOfSight generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class AttackLocation_LineOfSight extends AttackLocation
    native(AI)
    editinlinenew
    collapsecategories
    hidecategories(Mobile,Object);

enum ELineOfSight
{
    ELOS_Keep,
    ELOS_Avoid,
    ELOS_Arc,
    ELOS_MAX
};

var(LineOfSight) const AttackLocation_LineOfSight.ELineOfSight LineOfSight;
var(LineOfSight) const float ValidTime;
var(LineOfSight) const bool bFullLineOfSight;
var(Arc) const bool bMustHaveNavMesh;
var(Arc) const float ArcAnglePct;
var(Arc) const float ArcSpeed;
var(Arc) const Vector ArcStartOffset;
var(Arc) const Vector ArcEndOffset;

// Export UAttackLocation_LineOfSight::execValidLocation(FFrame&, void* const)
native function bool ValidLocation(IAIInterface AI, const out Vector TestLoc);

defaultproperties
{
    ArcAnglePct=0.3
    ArcSpeed=1000
}