/*******************************************************************************
 * AvatarAwardUtility generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class AvatarAwardUtility extends Object
    native
    hidecategories(Mobile);

enum EWillowAvatarAwards
{
    WAA_Invalid,
    WAA_One,
    WAA_Two,
    WAA_Three,
    WAA_MAX
};
