/*******************************************************************************
 * Behavior_CompleteMission generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Behavior_CompleteMission extends BehaviorBase
    native
    editinlinenew
    hidecategories(Mobile,Object,Context)
    autoexpandcategories(Action);

// Export UBehavior_CompleteMission::execApplyBehaviorToContext(FFrame&, void* const)
protected native function ApplyBehaviorToContext(Object ContextObject, out BehaviorKernelInfo KernelInfo, Object SelfObject, Object MyInstigatorObject, Object OtherEventParticipantObject, BehaviorParameters EventData);
