/*******************************************************************************
 * Behavior_GetVelocity generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Behavior_GetVelocity extends BehaviorBase
    editinlinenew
    collapsecategories
    hidecategories(Mobile,Object)
    autoexpandcategories(Action);

var(Action) bool bLocalSpace;

protected function ApplyBehaviorToContext(Object ContextObject, out BehaviorKernelInfo KernelInfo, Object SelfObject, Object MyInstigatorObject, Object OtherEventParticipantObject, BehaviorParameters EventData)
{
    local IWorldBody ContextInterface;
    local Vector Velocity;

    ContextInterface = ContextObject.QueryInterface(class'IWorldBody');
    // End:0xDB
    if(NotEqual_InterfaceInterface(ContextInterface, IWorldBody(none)))
    {
        Velocity = ContextInterface.GetWorldBodyVelocity();
        // End:0xBF
        if(bLocalSpace)
        {
            Velocity = Velocity << ContextInterface.GetWorldBodyRotation();
        }
        PublishBehaviorOutput(KernelInfo, Velocity);
    }
    //return;    
}

protected function PublishBehaviorOutput(out BehaviorKernelInfo KernelInfo, Vector Velocity)
{
    UnknownLocal_1 = class'GearboxGlobals'.static.GetBehaviorKernel();
    UnknownLocal_1.PublishVectorOutputVariable(KernelInfo, Velocity);
    //return;    
}
