/*******************************************************************************
 * Behavior_SpawnFromPopulationSystem generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Behavior_SpawnFromPopulationSystem extends BehaviorBase
    native
    editinlinenew
    hidecategories(Mobile,Object)
    autoexpandcategories(Action);

enum SpawnLocationRotationInheritanceType
{
    SLRIT_Context,
    SLRIT_Attachment,
    SLRIT_Self,
    SLRIT_MAX
};

var(Action) const editinline PopulationFactory SpawnFactory;
var(Action) const bool bZeroPitchAndRollOnSpawnedActor;
var(Action) const bool bRelativeSpawnOffset;
var(Action) const bool bSpawnOnGround;
var const bool bInheritAttachment;
var(Action) const bool bInheritAttachmentBase;
var(SaveActorReference) const bool bSaveActorReference;
var(Action) const BehaviorContextData GameStageContext;
var(Action) const Vector SpawnLocOffset;
var(Action) const Behavior_SpawnFromPopulationSystem.SpawnLocationRotationInheritanceType InheritLocationRotationFrom;
var(Action) const Rotator SpawnRotationOffset;
var(Action) const Actor MyOwner;
var(PostSpawnOptions) const Vector StartingVelocity;
var(SaveActorReference) const BehaviorContextData InstanceDataContext;
var(SaveActorReference) const name SavedReferenceName;
var int FloorTestZDist;

protected function ApplyBehaviorToContext(Object ContextObject, out BehaviorKernelInfo KernelInfo, Object SelfObject, Object MyInstigatorObject, Object OtherEventParticipantObject, BehaviorParameters EventData)
{
    local IWorldBody WorldBody, SelfWorldBody;
    local IBalancedActor BalancedActor;
    local Vector SpawnLocation;
    local Rotator SpawnRotation;
    local InstanceDataUnion SavedActorData;
    local IInstanceData SaveReferenceContext;
    local Vector HitLoc, HitNormal, FloorCheck;
    local IAttachableActor AttachedContext;

    // End:0x803
    if((int(GetWorldInfo().NetMode) != int(NM_Client)) && SpawnFactory != none)
    {
        WorldBody = ContextObject.QueryInterface(class'IWorldBody');
        SelfWorldBody = SelfObject.QueryInterface(class'IWorldBody');
        AttachedContext = SelfObject.QueryInterface(class'IAttachableActor');
        UnknownLocal_1 = class'GearboxGlobals'.static.GetGearboxGlobals().GetPopulationMaster();
        UnknownLocal_3 = class'WillowGlobals'.static.GetWillowGlobals().GetGlobalsDefinition();
        // End:0x803
        if((NotEqual_InterfaceInterface(WorldBody, IWorldBody(none)) && UnknownLocal_1 != none) && UnknownLocal_3 != none)
        {
            BalancedActor = GetBehaviorContextInterface(class'IBalancedActor', GameStageContext, SelfObject, MyInstigatorObject, OtherEventParticipantObject, EventData);
            // End:0x238
            if(NotEqual_InterfaceInterface(BalancedActor, IBalancedActor(none)))
            {
                UnknownLocal_5 = BalancedActor.GetGameStage();
                UnknownLocal_7 = BalancedActor.GetAwesomeLevel();
            }
            // End:0x2EC
            if(((int(InheritLocationRotationFrom) == int(1)) && NotEqual_InterfaceInterface(AttachedContext, IAttachableActor(none))) && AttachedContext.IsAttached())
            {
                SpawnRotation = Rotator(AttachedContext.GetAttachmentNormal());
                SpawnLocation = SelfWorldBody.GetWorldBodyLocation();                
            }
            else
            {
                // End:0x357
                if(int(InheritLocationRotationFrom) == int(2))
                {
                    SpawnRotation = SelfWorldBody.GetWorldBodyRotation();
                    SpawnLocation = SelfWorldBody.GetWorldBodyLocation();                    
                }
                else
                {
                    SpawnRotation = WorldBody.GetWorldBodyRotation();
                    SpawnLocation = WorldBody.GetWorldBodyLocation();
                }
            }
            SpawnRotation += SpawnRotationOffset;
            // End:0x3F0
            if(bRelativeSpawnOffset)
            {
                SpawnLocation += (SpawnLocOffset >> SpawnRotation);                
            }
            else
            {
                SpawnLocation += SpawnLocOffset;
            }
            // End:0x44D
            if(bZeroPitchAndRollOnSpawnedActor)
            {
                SpawnRotation.Pitch = 0;
                SpawnRotation.Roll = 0;
            }
            UnknownLocal_9 = Actor(SelfObject);
            // End:0x540
            if(bSpawnOnGround && UnknownLocal_9 != none)
            {
                FloorCheck.Z = float(FloorTestZDist);
                // End:0x4D3
                if(bRelativeSpawnOffset)
                {
                    FloorCheck = FloorCheck >> SpawnRotation;
                }
                UnknownLocal_11 = UnknownLocal_9.Trace(HitLoc, HitNormal, SpawnLocation - FloorCheck, SpawnLocation);
                // End:0x540
                if(UnknownLocal_11 != none)
                {
                    SpawnLocation = HitLoc;
                }
            }
            UnknownLocal_13 = UnknownLocal_1.SpawnActor(SpawnFactory.GetSpawnFactory(none, UnknownLocal_5, UnknownLocal_7), ContextObject, SpawnLocation, SpawnRotation, UnknownLocal_5, UnknownLocal_7);
            UnknownLocal_13.Velocity = StartingVelocity >> SelfWorldBody.GetWorldBodyRotation();
            // End:0x6B4
            if((bInheritAttachmentBase && NotEqual_InterfaceInterface(AttachedContext, IAttachableActor(none))) && AttachedContext.IsAttached())
            {
                UnknownLocal_13.SetPhysics(14);
                UnknownLocal_13.SetHardAttach(true);
                UnknownLocal_13.SetBase(AttachedContext.GetAttachedToActor());
            }
            // End:0x6E0
            if(MyOwner != none)
            {
                UnknownLocal_13.SetOwner(MyOwner);
            }
            SaveReferenceContext = GetBehaviorContextInterface(class'IInstanceData', InstanceDataContext, SelfObject, MyInstigatorObject, OtherEventParticipantObject, EventData);
            // End:0x7EB
            if(bSaveActorReference && NotEqual_InterfaceInterface(SaveReferenceContext, IInstanceData(none)))
            {
                SavedActorData.Name = SavedReferenceName;
                SavedActorData.Type = 6;
                SavedActorData.Object = UnknownLocal_13;
                SaveReferenceContext.SetInstanceData(SavedActorData, true);
            }
            PublishBehaviorOutput(KernelInfo, UnknownLocal_13);
        }
    }
    //return;    
}

protected function PublishBehaviorOutput(out BehaviorKernelInfo KernelInfo, Actor SpawnedActor)
{
    UnknownLocal_1 = class'WillowGlobals'.static.GetBehaviorKernel();
    UnknownLocal_1.PublishObjectOutputVariable(KernelInfo, SpawnedActor);
    //return;    
}

defaultproperties
{
    bZeroPitchAndRollOnSpawnedActor=true
    FloorTestZDist=1024
}