/*******************************************************************************
 * Behavior_GetPlayerStat generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Behavior_GetPlayerStat extends BehaviorBase
    editinlinenew
    hidecategories(Mobile,Object)
    autoexpandcategories(Action);

var(Action) const name StatId;

protected function ApplyBehaviorToContext(Object ContextObject, out BehaviorKernelInfo KernelInfo, Object SelfObject, Object MyInstigatorObject, Object OtherEventParticipantObject, BehaviorParameters EventData)
{
    local IControllerLocator ControllerLocator;

    ControllerLocator = ContextObject.QueryInterface(class'IControllerLocator');
    // End:0xED
    if(NotEqual_InterfaceInterface(ControllerLocator, IControllerLocator(none)) && ControllerLocator.GetAWillowPlayerController() != none)
    {
        UnknownLocal_1 = ControllerLocator.GetAWillowPlayerController().PlayerStats.GetIntStat(StatId);
        PublishBehaviorOutput(KernelInfo, UnknownLocal_1);
    }
    //return;    
}

protected function PublishBehaviorOutput(out BehaviorKernelInfo KernelInfo, int Result)
{
    class'BehaviorKernel'.static.PublishIntOutputVariable(KernelInfo, Result);
    //return;    
}
