/*******************************************************************************
 * ColiseumRuleDefinition generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ColiseumRuleDefinition extends GBXDefinition
    hidecategories(Mobile);

var() const localized string RuleTitle;
var() const localized string RuleDescription;
var() string FrameLabel;
