/*******************************************************************************
 * CustomizationGFxMovie generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class CustomizationGFxMovie extends WillowGFxThirdPersonMovie
    native(GFx)
    config(UI)
    hidecategories(Mobile);

const ENTRY_IDX_HEADS = 0;
const ENTRY_IDX_SKINS = 1;
const ENTRY_IDX_NAME = 2;
const ENTRY_IDX_RESPEC = 3;

var transient CharacterCustomizationMenuGFxObject CharacterCustomizationMenu;
var transient CharacterCustomizationInfoCardGFxObject CharacterCustomizationInfoCard;
var transient string SkillBranchDescriptions[3];
var transient array<CustomizationDefinition> HeadCustomizations;
var transient array<CustomizationDefinition> SeenHeadCustomizations;
var transient array<CustomizationDefinition> SkinCustomizations;
var transient array<CustomizationDefinition> SeenSkinCustomizations;
var transient CustomizationDefinition EquippedHeadCustomization;
var transient CustomizationDefinition EquippedSkinCustomization;
var transient CustomizationDefinition PreviewHeadCustomization;
var transient CustomizationDefinition PreviewSkinCustomization;
var transient bool bSelectingFromList;
var transient bool bHasSpentSkillPoints;
var transient int SelectedEntryIdx;
var transient string StringPreKeyboardUI;
var int MaxNameLength;
var const localized string HeaderText;
var const localized string NoValidHeadCaption;
var const localized string NoValidSkinCaption;
var const localized string UnlockedText;
var transient string UnlockedHeadsNumbersText;
var transient string UnlockedSkinsNumbersText;
var transient string TooltipsPath;
var transient int PreviewIndex;
var transient string PreviewType;
var transient array<CustomizationDefinition> UnauthorizedHeadCustomizations;
var transient array<CustomizationDefinition> UnauthorizedSkinCustomizations;
var transient CustomizationDefinition PotentialCustomizationForPurchase;

// Export UCustomizationGFxMovie::execGetSonyTitleID(FFrame&, void* const)
native static function string GetSonyTitleID();

event bool Start(optional bool StartPaused)
{
    UnknownLocal_1
    super.Start(StartPaused);
    // End:0x13C
    if(UnknownLocal_1)
    {
        WPCOwner.RegisterSkillTreeResetDelegate(OnSkillTreeReset);
        UnknownLocal_3 = WillowPlayerReplicationInfo(WPCOwner.PlayerReplicationInfo);
        UnknownLocal_3.RegisterCurrencyChangedDelegate(OnCurrencyChanged);
        CacheSkillBranchDescriptions();
        CacheCustomizations();
        SetUnlockedText_Heads();
        SetUnlockedText_Skins();
        SetVariableString("customization.menu.caption.text", HeaderText);
        WPCOwner.bUsingVendingMachine = true;
        PlayUISound('MenuOpen');
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

function BeginClosing()
{
    UnknownLocal_1 = class'GameEngine'.static.GetDLCManager();
    // End:0x5C
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.ClearRefreshCompleteDelegate(MarketplaceDownloadComplete);
    }
    CancelHeadCustomization();
    CancelSkinCustomization();
    GotoAndStop("outro");
    ValidatePlayerName(CharacterCustomizationMenu.GetEntryLabel(2));
    WPCOwner.SetPlayerUINamePreference(CharacterCustomizationMenu.GetEntryLabel(2));
    WPCOwner.bUsingVendingMachine = false;
    PlayUISound('MenuClose');
    super.BeginClosing();
    //return;    
}

function OnClose()
{
    UnknownLocal_1 = class'GameEngine'.static.GetDLCManager();
    // End:0x5C
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.ClearRefreshCompleteDelegate(MarketplaceDownloadComplete);
    }
    HeadCustomizations.Length = 0;
    SeenHeadCustomizations.Length = 0;
    SkinCustomizations.Length = 0;
    SeenSkinCustomizations.Length = 0;
    EquippedHeadCustomization = none;
    EquippedSkinCustomization = none;
    PreviewHeadCustomization = none;
    PreviewSkinCustomization = none;
    CharacterCustomizationMenu = none;
    CharacterCustomizationInfoCard = none;
    WPCOwner.UnregisterSkillTreeResetDelegate();
    UnauthorizedHeadCustomizations.Length = 0;
    UnauthorizedSkinCustomizations.Length = 0;
    super.OnClose();
    //return;    
}

function bool MainInputKey(int ControllerId, name ukey, Core.Object.EInputEvent uevent)
{
    switch(ukey)
    {
        // End:0x1F
        case 'Gamepad_LeftStick_Left':
        // End:0x2B
        case 'XboxTypeS_DPad_Left':
        // End:0x37
        case 'Left':
        // End:0x43
        case 'Gamepad_LeftStick_Right':
        // End:0x4F
        case 'XboxTypeS_DPad_Right':
        // End:0x5D
        case 'Right':
            return true;
        // End:0x69
        case 'XboxTypeS_B':
        // End:0xD7
        case 'Escape':
            // End:0xD4
            if(bSelectingFromList)
            {
                // End:0xD2
                if(int(uevent) == int(1))
                {
                    CancelHeadCustomization();
                    CancelSkinCustomization();
                    CharacterCustomizationMenu.SetSelectedEntry(SelectedEntryIdx);
                }
                return true;
            }
            // End:0x420
            break;
        // End:0xE3
        case 'Gamepad_LeftStick_Up':
        // End:0xEF
        case 'XboxTypeS_DPad_Up':
        // End:0x1D4
        case 'Up':
            // End:0x158
            if(!bSelectingFromList)
            {
                // End:0x153
                if((int(uevent) == int(1)) || int(uevent) == int(2))
                {
                    CharacterCustomizationMenu.FocusPreviousEntry();
                }
                return true;                
            }
            else
            {
                // End:0x1D1
                if(int(uevent) == int(1))
                {
                    // End:0x1A0
                    if(PreviewType == "head")
                    {
                        UpdateHeadPreview(HeadCustomizations[PreviewIndex]);                        
                    }
                    else
                    {
                        // End:0x1D1
                        if(PreviewType == "skin")
                        {
                            UpdateSkinPreview(SkinCustomizations[PreviewIndex]);
                        }
                    }
                }
            }
            // End:0x420
            break;
        // End:0x1E0
        case 'Gamepad_LeftStick_Down':
        // End:0x1EC
        case 'XboxTypeS_DPad_Down':
        // End:0x2D1
        case 'Down':
            // End:0x255
            if(!bSelectingFromList)
            {
                // End:0x250
                if((int(uevent) == int(1)) || int(uevent) == int(2))
                {
                    CharacterCustomizationMenu.FocusNextEntry();
                }
                return true;                
            }
            else
            {
                // End:0x2CE
                if(int(uevent) == int(1))
                {
                    // End:0x29D
                    if(PreviewType == "head")
                    {
                        UpdateHeadPreview(HeadCustomizations[PreviewIndex]);                        
                    }
                    else
                    {
                        // End:0x2CE
                        if(PreviewType == "skin")
                        {
                            UpdateSkinPreview(SkinCustomizations[PreviewIndex]);
                        }
                    }
                }
            }
            // End:0x420
            break;
        // End:0x2DD
        case 'XboxTypeS_LeftTrigger':
        // End:0x2E9
        case 'PageUp':
        // End:0x2F5
        case 'XboxTypeS_RightTrigger':
        // End:0x301
        case 'PageDown':
        // End:0x30D
        case 'Home':
        // End:0x3A4
        case 'End':
            // End:0x3A1
            if(bSelectingFromList && int(uevent) == int(1))
            {
                // End:0x370
                if(PreviewType == "head")
                {
                    UpdateHeadPreview(HeadCustomizations[PreviewIndex]);                    
                }
                else
                {
                    // End:0x3A1
                    if(PreviewType == "skin")
                    {
                        UpdateSkinPreview(SkinCustomizations[PreviewIndex]);
                    }
                }
            }
            // End:0x420
            break;
        // End:0x3DE
        case 'Enter':
            ValidatePlayerName(CharacterCustomizationMenu.GetEntryLabel(2));
            // End:0x420
            break;
        // End:0x41D
        case 'XboxTypeS_A':
            // End:0x41A
            if((int(uevent) == int(1)) && SelectedEntryIdx == 2)
            {
                InputName();
            }
            // End:0x420
            break;
        // End:0xFFFF
        default:
            break;
    }
    return HandleKeyDefaults(ControllerId, ukey, uevent);
    //return ReturnValue;    
}

final function CacheSkillBranchDescriptions()
{
    local SkillTreeBranchStateData BranchState;
    local string SkillBranchDescription;

    // End:0x35C
    if((WPCOwner != none) && WPCOwner.PlayerClass != none)
    {
        UnknownLocal_1 = class'WillowGlobals'.static.GetWillowGlobals().GetPlayerPawnDataManager().LoadSkillTreeDefinition(WPCOwner.PlayerClass.SkillTreePath, WPCOwner);
        // End:0x35C
        if(UnknownLocal_1 != none)
        {
            // End:0x30C
            if(UnknownLocal_1.Root != none)
            {
                // End:0x30C
                if(UnknownLocal_1.Root.Children.Length == 3)
                {
                    UnknownLocal_3 = 0;
                    J0x12B:

                    // End:0x30C [Loop If]
                    if(UnknownLocal_3 < 3)
                    {
                        UnknownLocal_5 = UnknownLocal_1.Root.Children[UnknownLocal_3];
                        // End:0x302
                        if(UnknownLocal_5 != none)
                        {
                            // End:0x302
                            if(WPCOwner.PlayerSkillTree.GetBranchState(UnknownLocal_5, BranchState))
                            {
                                SkillBranchDescription = Localize("CharacterCustomization", "SkillTreeDisplay", "WillowMenu");
                                SkillBranchDescription = Repl(SkillBranchDescription, "%1", UnknownLocal_5.BranchName);
                                SkillBranchDescription = Repl(SkillBranchDescription, "%2", string(BranchState.PointsSpentInBranch));
                                SkillBranchDescription = Repl(SkillBranchDescription, "%3", string(BranchState.MaxPointsForBranch));
                                SkillBranchDescriptions[UnknownLocal_3] = SkillBranchDescription;
                                bHasSpentSkillPoints = bHasSpentSkillPoints || BranchState.PointsSpentInBranch > 0;
                            }
                        }
                        ++ UnknownLocal_3;
                        // [Loop Continue]
                        goto J0x12B;
                    }
                }
            }
            class'WillowGlobals'.static.GetWillowGlobals().GetPlayerPawnDataManager().ReferenceHasBeenApplied(UnknownLocal_1);
        }
    }
    //return;    
}

final function CacheCustomizations()
{
    local array<CustomizationDefinition> AvailableCustomizations, UnauthorizedCustomizations;
    local array<int> AvailableCustomizationsSeen;

    HeadCustomizations.Length = 0;
    SeenHeadCustomizations.Length = 0;
    SkinCustomizations.Length = 0;
    SeenSkinCustomizations.Length = 0;
    UnauthorizedHeadCustomizations.Length = 0;
    UnauthorizedSkinCustomizations.Length = 0;
    class'CustomizationDefinition'.static.GetAvailableAndUnauthorizedCustomizationsForPlayer(WPCOwner, AvailableCustomizations, AvailableCustomizationsSeen, UnauthorizedCustomizations, UnknownLocal_1, class'CustomizationType_Skin');
    UnknownLocal_3 = 0;
    J0xA2:

    // End:0x10E [Loop If]
    if(UnknownLocal_3 < AvailableCustomizations.Length)
    {
        UnknownLocal_5 = AvailableCustomizations[UnknownLocal_3];
        SkinCustomizations.AddItem(UnknownLocal_5;
        // End:0x104
        if(AvailableCustomizationsSeen[UnknownLocal_3] == 1)
        {
            SeenSkinCustomizations.AddItem(UnknownLocal_5;
        }
        ++ UnknownLocal_3;
        // [Loop Continue]
        goto J0xA2;
    }
    UnknownLocal_3 = 0;
    J0x115:

    // End:0x1A7 [Loop If]
    if(UnknownLocal_3 < UnauthorizedCustomizations.Length)
    {
        UnknownLocal_5 = UnauthorizedCustomizations[UnknownLocal_3];
        // End:0x19D
        if(UnknownLocal_5.ProfileEntryIndex == -1)
        {
            // End:0x19D
            if(GetOfferIdForCustomization(UnknownLocal_5, UnknownLocal_7))
            {
                UnauthorizedSkinCustomizations.AddItem(UnknownLocal_5;
                SkinCustomizations.AddItem(UnknownLocal_5;
            }
        }
        ++ UnknownLocal_3;
        // [Loop Continue]
        goto J0x115;
    }
    UnlockedSkinsNumbersText = (string(AvailableCustomizations.Length) $ "/") $ string(UnknownLocal_1 + AvailableCustomizations.Length);
    class'CustomizationDefinition'.static.GetAvailableAndUnauthorizedCustomizationsForPlayer(WPCOwner, AvailableCustomizations, AvailableCustomizationsSeen, UnauthorizedCustomizations, UnknownLocal_1, class'CustomizationType_Head');
    UnknownLocal_3 = 0;
    J0x231:

    // End:0x29D [Loop If]
    if(UnknownLocal_3 < AvailableCustomizations.Length)
    {
        UnknownLocal_5 = AvailableCustomizations[UnknownLocal_3];
        HeadCustomizations.AddItem(UnknownLocal_5;
        // End:0x293
        if(AvailableCustomizationsSeen[UnknownLocal_3] == 1)
        {
            SeenHeadCustomizations.AddItem(UnknownLocal_5;
        }
        ++ UnknownLocal_3;
        // [Loop Continue]
        goto J0x231;
    }
    UnknownLocal_3 = 0;
    J0x2A4:

    // End:0x336 [Loop If]
    if(UnknownLocal_3 < UnauthorizedCustomizations.Length)
    {
        UnknownLocal_5 = UnauthorizedCustomizations[UnknownLocal_3];
        // End:0x32C
        if(UnknownLocal_5.ProfileEntryIndex == -1)
        {
            // End:0x32C
            if(GetOfferIdForCustomization(UnknownLocal_5, UnknownLocal_7))
            {
                UnauthorizedHeadCustomizations.AddItem(UnknownLocal_5;
                HeadCustomizations.AddItem(UnknownLocal_5;
            }
        }
        ++ UnknownLocal_3;
        // [Loop Continue]
        goto J0x2A4;
    }
    class'CustomizationDefinition'.static.SortCustomizationList(SkinCustomizations);
    class'CustomizationDefinition'.static.SortCustomizationList(HeadCustomizations);
    UnlockedHeadsNumbersText = (string(AvailableCustomizations.Length) $ "/") $ string(UnknownLocal_1 + AvailableCustomizations.Length);
    //return;    
}

function HandleMenuEntryClick(int EntryIndex)
{
    local GearboxFramework.GearboxGlobals.EGBXPlatform Platform;

    Platform = class'GearboxGlobals'.static.GetPlatform();
    SelectedEntryIdx = EntryIndex;
    CancelHeadCustomization();
    CancelSkinCustomization();
    switch(EntryIndex)
    {
        // End:0x9F
        case 2:
            bSelectingFromList = false;
            SetTooltips();
            // End:0x9C
            if(int(Platform) != int(0))
            {
                InputName();
            }
            // End:0x16B
            break;
        // End:0xE5
        case 0:
            CharacterCustomizationInfoCard.DisplayHeadCard();
            SetUnlockedText_Heads();
            bSelectingFromList = true;
            SetTooltips();
            // End:0x16B
            break;
        // End:0x12B
        case 1:
            CharacterCustomizationInfoCard.DisplaySkinCard();
            SetUnlockedText_Skins();
            bSelectingFromList = true;
            SetTooltips();
            // End:0x16B
            break;
        // End:0x168
        case 3:
            bSelectingFromList = false;
            SetTooltips();
            WPCOwner.VerifySkillRespec();
            // End:0x16B
            break;
        // End:0xFFFF
        default:
            break;
    }
    UpdateDesiredCameraPosition();
    //return;    
}

function HandleMenuEntryFocus(int EntryIndex)
{
    SelectedEntryIdx = EntryIndex;
    bSelectingFromList = false;
    SetTooltips();
    ValidatePlayerName(CharacterCustomizationMenu.GetEntryLabel(2));
    UpdateInfoCard(EntryIndex);
    UpdateDesiredCameraPosition();
    //return;    
}

function HandleMenuEntryRollOver(int EntryIndex)
{
    // End:0x22
    if(!bSelectingFromList)
    {
        UpdateInfoCard(EntryIndex);
    }
    //return;    
}

function bool UsingGamepad()
{
    return (int(class'GearboxGlobals'.static.GetPlatform()) != int(0)) || WPCOwner.PlayerInput.bUsingGamepad;
    //return ReturnValue;    
}

function HandleCustomizationEvent(string CustomizationType, string EventName, int ItemIndex)
{
    UnknownLocal_1 = EventName == "change";
    UnknownLocal_3 = EventName == "rollover";
    UnknownLocal_5 = EventName == "click";
    // End:0x110
    if(UnknownLocal_3 || UnknownLocal_5)
    {
        // End:0xB7
        if(CustomizationType == "head")
        {
            UpdateHeadPreview(HeadCustomizations[ItemIndex]);
            // End:0xB4
            if(UnknownLocal_5)
            {
                CommitHeadCustomization(HeadCustomizations[ItemIndex]);
            }            
        }
        else
        {
            // End:0x10D
            if(CustomizationType == "skin")
            {
                UpdateSkinPreview(SkinCustomizations[ItemIndex]);
                // End:0x10D
                if(UnknownLocal_5)
                {
                    CommitSkinCustomization(SkinCustomizations[ItemIndex]);
                }
            }
        }        
    }
    else
    {
        // End:0x13E
        if(UnknownLocal_1)
        {
            PreviewIndex = ItemIndex;
            PreviewType = CustomizationType;
        }
    }
    //return;    
}

function CommitHeadCustomization(CustomizationDefinition TargetCustomization)
{
    // End:0x9A
    if(UnauthorizedHeadCustomizations.Find(TargetCustomization != -1)
    {
        PotentialCustomizationForPurchase = TargetCustomization;
        // End:0x98
        if(ShowPurchaseDialog(WPCOwner, OnPurchaseRequest, OnPurchaseCanceled))
        {
            OnPurchaseRequest(none, int(WPCOwner.GetMyControllerId()));
        }
        return;
    }
    EquippedHeadCustomization = TargetCustomization;
    CharacterCustomizationMenu.ConfigureMenuEntry(0, false, EquippedHeadCustomization.CustomizationName);
    CharacterCustomizationMenu.SetSelectedEntry(SelectedEntryIdx);
    UnknownLocal_1 = class'WillowGlobals'.static.GetWillowGlobals();
    UnknownLocal_1.GetCustomizationManager().SetCustomizationSeen(EquippedHeadCustomization, WPCOwner, true);
    // End:0x1B3
    if(SeenHeadCustomizations.Find(EquippedHeadCustomization == -1)
    {
        SeenHeadCustomizations.AddItem(EquippedHeadCustomization;
    }
    class'WillowLeviathanService'.static.RecordCustomizeCharacterEventForPlayer(WPCOwner, EquippedHeadCustomization.Name, 2);
    //return;    
}

function CommitSkinCustomization(CustomizationDefinition TargetCustomization)
{
    // End:0x9A
    if(UnauthorizedSkinCustomizations.Find(TargetCustomization != -1)
    {
        PotentialCustomizationForPurchase = TargetCustomization;
        // End:0x98
        if(ShowPurchaseDialog(WPCOwner, OnPurchaseRequest, OnPurchaseCanceled))
        {
            OnPurchaseRequest(none, int(WPCOwner.GetMyControllerId()));
        }
        return;
    }
    EquippedSkinCustomization = TargetCustomization;
    CharacterCustomizationMenu.ConfigureMenuEntry(1, false, EquippedSkinCustomization.CustomizationName);
    CharacterCustomizationMenu.SetSelectedEntry(SelectedEntryIdx);
    UnknownLocal_1 = class'WillowGlobals'.static.GetWillowGlobals();
    UnknownLocal_1.GetCustomizationManager().SetCustomizationSeen(EquippedSkinCustomization, WPCOwner, true);
    // End:0x1B3
    if(SeenSkinCustomizations.Find(EquippedSkinCustomization == -1)
    {
        SeenSkinCustomizations.AddItem(EquippedSkinCustomization;
    }
    class'WillowLeviathanService'.static.RecordCustomizeCharacterEventForPlayer(WPCOwner, EquippedSkinCustomization.Name, 2);
    //return;    
}

static function bool ShowPurchaseDialog(WillowPlayerController WPC, delegate<OnButtonClicked> PurchaseRequested, optional delegate<OnButtonClicked> PurchaseCanceled, optional out WillowGFxDialogBox DialogOwner)
{
    local GearboxFramework.GearboxGlobals.EGBXPlatform Platform;

    Platform
    class'GearboxGlobals'.static.GetPlatform();
    switch(Platform)
    {
        // End:0x43
        case 0:
        // End:0x4A
        case 1:
            return true;
        // End:0x229
        case 2:
            UnknownLocal_1 = WPC.GetPrimaryPlayer().GFxUIManager.ShowDialog();
            UnknownLocal_1.AutoLocEnable("WillowMenu", "CharacterCustomizationPurchase");
            UnknownLocal_1.AutoAppendButton('Purchase', PurchaseRequested);
            UnknownLocal_1.AutoAppendButton('Cancel', PurchaseCanceled);
            UnknownLocal_1.CancelButtonTag = 'Cancel';
            UnknownLocal_1.AutoLocEnableCaption("WillowMenu", "CharacterSelect", "TooltipPurchase");
            UnknownLocal_1.AutoLocEnablePrompt("WillowMenu", "CharacterCustomizationPurchase", "Prompt");
            UnknownLocal_1.ApplyLayout();
            DialogOwner = UnknownLocal_1;
            return false;
        // End:0xFFFF
        default:
            return false;
            break;
    }
    //return ReturnValue;    
}

static function bool ShowMarketplaceOfferFor(WillowPlayerController WPC, int OfferId)
{
    UnknownLocal_1 = WPC.GetMyControllerId();
    // End:0xD2
    if((int(class'GearboxGlobals'.static.GetPlatform()) == int(2)) && int(class'UIInteraction'.static.GetLoginStatus(int(UnknownLocal_1))) < int(2))
    {
        WPC.OnlineSub.PlayerInterface.ShowLoginUI();        
    }
    else
    {
        // End:0x1C6
        if((int(class'GearboxGlobals'.static.GetPlatform()) == int(2)) && int(WPC.OnlineSub.PlayerInterface.CanPlayOnline(UnknownLocal_1)) != int(2))
        {
            WPC.GFxUIManager.ShowDialog().DisplayOkBox("WillowMenu", "dlgNoPSNPrivilege");            
        }
        else
        {
            WPC.OnlineSub.PlayerInterfaceEx.ShowContentMarketplaceUI(UnknownLocal_1, -1, OfferId);
            return true;
        }
    }
    return false;
    //return ReturnValue;    
}

function bool OnPurchaseRequest(WillowGFxDialogBox Dlg, int ControllerId)
{
    // End:0xDD
    if(GetOfferIdForCustomization(PotentialCustomizationForPurchase, UnknownLocal_1))
    {
        // End:0xDD
        if(ShowMarketplaceOfferFor(((int(class'GearboxGlobals'.static.GetPlatform()) == int(2)) ? WPCOwner.GetPrimaryPlayer() : WPCOwner), UnknownLocal_1))
        {
            UnknownLocal_3 = class'GameEngine'.static.GetDLCManager();
            // End:0xDD
            if(UnknownLocal_3 != none)
            {
                UnknownLocal_3.AddRefreshCompleteDelegate(MarketplaceDownloadComplete);
            }
        }
    }
    // End:0x10C
    if(Dlg != none)
    {
        Dlg.Close();
    }
    return true;
    //return ReturnValue;    
}

function bool OnPurchaseCanceled(WillowGFxDialogBox Dlg, int ControllerId)
{
    PotentialCustomizationForPurchase = none;
    // End:0x3A
    if(Dlg != none)
    {
        Dlg.Close();
    }
    return true;
    //return ReturnValue;    
}

function CancelHeadCustomization()
{
    UpdateHeadPreview(EquippedHeadCustomization);
    //return;    
}

function CancelSkinCustomization()
{
    UpdateSkinPreview(EquippedSkinCustomization);
    //return;    
}

function UpdateHeadPreview(CustomizationDefinition CustomDef)
{
    // End:0x1B7
    if(PreviewHeadCustomization != CustomDef)
    {
        PreviewHeadCustomization = CustomDef;
        UnknownLocal_1 = WillowPlayerReplicationInfo(WPCOwner.PlayerReplicationInfo);
        // End:0x1B7
        if((PreviewHeadCustomization != none) && UnknownLocal_1 != none)
        {
            PlayUISound('ApplyCustomization');
            UnknownLocal_3 = class'WillowGlobals'.static.GetWillowGlobals();
            UnknownLocal_5 = UnknownLocal_3.GetGlobalsDefinition();
            UnknownLocal_7 = WillowPlayerPawn(WPCOwner.MyWillowPawn);
            // End:0x193
            if(((UnknownLocal_7 != none) && UnknownLocal_5 != none) && UnknownLocal_5.CustomizationApplicationStartEffect != none)
            {
                UnknownLocal_9 = UnknownLocal_3.GetEffectCoordinator();
                UnknownLocal_9.PushEffect(UnknownLocal_7, UnknownLocal_5.CustomizationApplicationStartEffect, none);
            }
            UnknownLocal_1.InitiateCustomizationRequest(PreviewHeadCustomization);
        }
    }
    // End:0x1E4
    if(UnauthorizedHeadCustomizations.Find(CustomDef != -1)
    {
        SetToolTipsForPurchase();        
    }
    else
    {
        SetTooltips();
    }
    //return;    
}

function UpdateSkinPreview(CustomizationDefinition CustomDef)
{
    // End:0x1B7
    if(PreviewSkinCustomization != CustomDef)
    {
        PreviewSkinCustomization = CustomDef;
        UnknownLocal_1 = WillowPlayerReplicationInfo(WPCOwner.PlayerReplicationInfo);
        // End:0x1B7
        if((PreviewSkinCustomization != none) && UnknownLocal_1 != none)
        {
            PlayUISound('ApplyCustomization');
            UnknownLocal_3 = class'WillowGlobals'.static.GetWillowGlobals();
            UnknownLocal_5 = UnknownLocal_3.GetGlobalsDefinition();
            UnknownLocal_7 = WillowPlayerPawn(WPCOwner.MyWillowPawn);
            // End:0x193
            if(((UnknownLocal_7 != none) && UnknownLocal_5 != none) && UnknownLocal_5.CustomizationApplicationStartEffect != none)
            {
                UnknownLocal_9 = UnknownLocal_3.GetEffectCoordinator();
                UnknownLocal_9.PushEffect(UnknownLocal_7, UnknownLocal_5.CustomizationApplicationStartEffect, none);
            }
            UnknownLocal_1.InitiateCustomizationRequest(PreviewSkinCustomization);
        }
    }
    // End:0x1E4
    if(UnauthorizedSkinCustomizations.Find(CustomDef != -1)
    {
        SetToolTipsForPurchase();        
    }
    else
    {
        SetTooltips();
    }
    //return;    
}

function UpdateInfoCard(int EntryIndex)
{
    switch(EntryIndex)
    {
        // End:0x3A
        case 2:
            CharacterCustomizationInfoCard.DisplayNameCard();
            // End:0xB0
            break;
        // End:0x60
        case 0:
            CharacterCustomizationInfoCard.Hide();
            // End:0xB0
            break;
        // End:0x86
        case 1:
            CharacterCustomizationInfoCard.Hide();
            // End:0xB0
            break;
        // End:0xAD
        case 3:
            CharacterCustomizationInfoCard.DisplayRespecCard();
            // End:0xB0
            break;
        // End:0xFFFF
        default:
            break;
    }
    //return;    
}

function SetUnlockedText_Heads()
{
    SetVariableString("customization.infoCard.collectedCount.countText.text", UnlockedHeadsNumbersText);
    SetVariableString("customization.infoCard.collectedCount.unlockedText.text", UnlockedText);
    //return;    
}

function SetUnlockedText_Skins()
{
    SetVariableString("customization.infoCard.collectedCount.countText.text", UnlockedSkinsNumbersText);
    SetVariableString("customization.infoCard.collectedCount.unlockedText.text", UnlockedText);
    //return;    
}

function OnSkillTreeReset(int NewPoints)
{
    PlayUISound('SkillPointReset');
    CacheSkillBranchDescriptions();
    extInitRespecInfoCard();
    CharacterCustomizationMenu.ConfigureMenuEntry(3, true, "$WillowMenu.CharacterCustomization.RespecButtonLabel");
    CharacterCustomizationMenu.FocusBestEntry();
    //return;    
}

function OnCurrencyChanged(const CurrencyState ChangedCurrency)
{
    extInitRespecInfoCard();
    //return;    
}

function InputName()
{
    UnknownLocal_1 = LocalPlayer(WPCOwner.Player);
    // End:0x200
    if(((WPCOwner.OnlineSub != none) && NotEqual_InterfaceInterface(WPCOwner.OnlineSub.PlayerInterface, OnlinePlayerInterface(none))) && UnknownLocal_1 != none)
    {
        StringPreKeyboardUI = CharacterCustomizationMenu.GetEntryLabel(2);
        WPCOwner.OnlineSub.PlayerInterface.AddKeyboardInputDoneDelegate(OnPlayerNameInputFinished);
        WPCOwner.OnlineSub.PlayerInterface.ShowKeyboardUI(byte(UnknownLocal_1.ControllerId), Localize("pname", "NameEntryTitle", "WillowMenu"), Localize("pname", "NamePrompt", "WillowMenu"),, false, StringPreKeyboardUI, MaxNameLength);
    }
    //return;    
}

function OnPlayerNameInputFinished(bool bSuccessful)
{
    local string resultString;

    // End:0x7C
    if(bSuccessful)
    {
        resultString = WPCOwner.OnlineSub.PlayerInterface.GetKeyboardInputResults(UnknownLocal_1);
        ValidatePlayerName(resultString);        
    }
    else
    {
        SetPlayerName(StringPreKeyboardUI);
    }
    WPCOwner.OnlineSub.PlayerInterface.ClearKeyboardInputDoneDelegate(OnPlayerNameInputFinished);
    //return;    
}

function SetPlayerName(string PlayerName)
{
    CharacterCustomizationMenu.ConfigureMenuEntry(2, false, PlayerName);
    //return;    
}

function ValidatePlayerName(string PlayerName)
{
    // End:0x27
    if(Len(PlayerName) == 0)
    {
        SetPlayerName(StringPreKeyboardUI);        
    }
    else
    {
        SetPlayerName(PlayerName);
    }
    //return;    
}

function extCharacterCustomizationOnLoad(string InfoCardTargetPath, string MenuTargetPath, string TooltipsTargetPath)
{
    CharacterCustomizationInfoCard = CharacterCustomizationInfoCardGFxObject(GetVariableObject(InfoCardTargetPath, class'CharacterCustomizationInfoCardGFxObject'));
    // End:0x81
    if(CharacterCustomizationInfoCard != none)
    {
        CharacterCustomizationInfoCard.SetFunction("handleCustomizationEvent", self, 'HandleCustomizationEvent');
    }
    CharacterCustomizationMenu = CharacterCustomizationMenuGFxObject(GetVariableObject(MenuTargetPath, class'CharacterCustomizationMenuGFxObject'));
    // End:0x4EE
    if(CharacterCustomizationMenu != none)
    {
        WPCOwner.GetPlayerUINamePreference(StringPreKeyboardUI);
        CharacterCustomizationMenu.InitMenuEntry(2, true, false, int(class'GearboxGlobals'.static.GetPlatform()) == int(0), MaxNameLength, "$WillowMenu.CharacterCustomization.NameCaption", StringPreKeyboardUI, "characterName");
        UnknownLocal_1 = WillowPlayerPawn(WPCOwner.MyWillowPawn);
        EquippedHeadCustomization = UnknownLocal_1.GetDesiredCustomizationOfType(class'CustomizationType_Head');
        PreviewHeadCustomization = EquippedHeadCustomization;
        CharacterCustomizationMenu.InitMenuEntry(0, true, HeadCustomizations.Length < 2, false, 0, "$WillowMenu.CharacterCustomization.HeadCaption", ((EquippedHeadCustomization != none) ? EquippedHeadCustomization.CustomizationName : NoValidHeadCaption), "head");
        EquippedSkinCustomization = UnknownLocal_1.GetDesiredCustomizationOfType(class'CustomizationType_Skin');
        PreviewSkinCustomization = EquippedSkinCustomization;
        CharacterCustomizationMenu.InitMenuEntry(1, true, SkinCustomizations.Length < 2, false, 0, "$WillowMenu.CharacterCustomization.SkinCaption", ((EquippedSkinCustomization != none) ? EquippedSkinCustomization.CustomizationName : NoValidSkinCaption), "skin");
        CharacterCustomizationMenu.InitMenuEntry(3, true, !bHasSpentSkillPoints, false, 0, "$WillowMenu.CharacterCustomization.RespecCaption", "$WillowMenu.CharacterCustomization.RespecButtonLabel", "respec");
        CharacterCustomizationMenu.SetFunction("HandleMenuEntryClick", self, 'HandleMenuEntryClick');
        CharacterCustomizationMenu.SetFunction("HandleMenuEntryFocus", self, 'HandleMenuEntryFocus');
        CharacterCustomizationMenu.SetFunction("HandleMenuEntryRollOver", self, 'HandleMenuEntryRollOver');
        CharacterCustomizationMenu.FocusBestEntry();
    }
    TooltipsPath = TooltipsTargetPath;
    SetTooltips();
    __OnInputKey__Delegate = MainInputKey;
    //return;    
}

function SetTooltips()
{
    UnknownLocal_1 = GetVariableObject(TooltipsPath);
    // End:0xE6
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.SetString("htmlText", ((bSelectingFromList) ? ResolveDataStoreMarkup(Localize("CharacterCustomization", "Tooltips_SubMenu", "WillowMenu")) : ResolveDataStoreMarkup(Localize("CharacterCustomization", "Tooltips", "WillowMenu"))));
    }
    //return;    
}

function SetToolTipsForPurchase()
{
    UnknownLocal_1 = GetVariableObject(TooltipsPath);
    // End:0xEF
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.SetString("htmlText", ((bSelectingFromList) ? ResolveDataStoreMarkup(Localize("CharacterCustomization", "Tooltips_SubMenu_Purchase", "WillowMenu")) : ResolveDataStoreMarkup(Localize("CharacterCustomization", "Tooltips", "WillowMenu"))));
    }
    //return;    
}

function extInitPlayerClassDisplay(string TextFieldTargetPath)
{
    UnknownLocal_1 = GetVariableObject(TextFieldTargetPath);
    // End:0xA4
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.SetString("text", WPCOwner.PlayerClass.CharacterNameId.CharacterClassId.LocalizedClassName);
    }
    //return;    
}

function extInitNameInfoCard()
{
    local GearboxFramework.GearboxGlobals.EGBXPlatform Platform;
    local string LocKey;

    Platform = class'GearboxGlobals'.static.GetPlatform();
    switch(Platform)
    {
        // End:0x9E
        case 0:
            CharacterCustomizationInfoCard.SetNameInfo(Localize("CharacterCustomization", "NameInfo_PC", "WillowMenu"));
            // End:0x167
            break;
        // End:0x101
        case 1:
            CharacterCustomizationInfoCard.SetNameInfo(Localize("CharacterCustomization", "NameInfo_360", "WillowMenu"));
            // End:0x167
            break;
        // End:0x164
        case 2:
            CharacterCustomizationInfoCard.SetNameInfo(Localize("CharacterCustomization", "NameInfo_PS3", "WillowMenu"));
            // End:0x167
            break;
        // End:0xFFFF
        default:
            break;
    }
    //return;    
}

function extInitRespecInfoCard()
{
    local string RespecInfo;

    UnknownLocal_1 = WillowPlayerReplicationInfo(WPCOwner.PlayerReplicationInfo);
    // End:0x5B
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_3 = UnknownLocal_1.GetCurrencyOnHand(0);
    }
    RespecInfo = Repl(Localize("CharacterCustomization", "RespecInfo", "WillowMenu"), "%1", string(WPCOwner.GetSkillTreeResetCost()));
    CharacterCustomizationInfoCard.SetRespecInfo(RespecInfo, SkillBranchDescriptions[0], SkillBranchDescriptions[1], SkillBranchDescriptions[2], UnknownLocal_3);
    //return;    
}

function extInitHeadInfoCard()
{
    local array<string> ListItems;
    local string DisplayName;

    PreviewType = "head";
    UnknownLocal_1 = 0;
    J0x17:

    // End:0x12B [Loop If]
    if(UnknownLocal_1 < HeadCustomizations.Length)
    {
        UnknownLocal_3 = HeadCustomizations[UnknownLocal_1];
        DisplayName = UnknownLocal_3.CustomizationName;
        // End:0x9B
        if(UnauthorizedHeadCustomizations.Find(UnknownLocal_3 != -1)
        {
            DisplayName = "*" $ DisplayName;            
        }
        else
        {
            // End:0xD5
            if(SeenHeadCustomizations.Find(UnknownLocal_3 == -1)
            {
                DisplayName = DisplayName $ "####NEW";
            }
        }
        // End:0x10B
        if(UnknownLocal_3 == EquippedHeadCustomization)
        {
            DisplayName = DisplayName $ "####EQUIPPED";
        }
        ListItems.AddItem(DisplayName;
        ++ UnknownLocal_1;
        // [Loop Continue]
        goto J0x17;
    }
    CharacterCustomizationInfoCard.PopulateScrollingList(ListItems, HeadCustomizations.Find(PreviewHeadCustomization);
    CharacterCustomizationInfoCard.TryFocusList();
    //return;    
}

function extInitSkinInfoCard()
{
    local array<string> ListItems;
    local string DisplayName;

    PreviewType = "skin";
    UnknownLocal_1 = 0;
    J0x17:

    // End:0x12B [Loop If]
    if(UnknownLocal_1 < SkinCustomizations.Length)
    {
        UnknownLocal_3 = SkinCustomizations[UnknownLocal_1];
        DisplayName = UnknownLocal_3.CustomizationName;
        // End:0x9B
        if(UnauthorizedSkinCustomizations.Find(UnknownLocal_3 != -1)
        {
            DisplayName = "*" $ DisplayName;            
        }
        else
        {
            // End:0xD5
            if(SeenSkinCustomizations.Find(UnknownLocal_3 == -1)
            {
                DisplayName = DisplayName $ "####NEW";
            }
        }
        // End:0x10B
        if(UnknownLocal_3 == EquippedSkinCustomization)
        {
            DisplayName = DisplayName $ "####EQUIPPED";
        }
        ListItems.AddItem(DisplayName;
        ++ UnknownLocal_1;
        // [Loop Continue]
        goto J0x17;
    }
    CharacterCustomizationInfoCard.PopulateScrollingList(ListItems, SkinCustomizations.Find(PreviewSkinCustomization);
    CharacterCustomizationInfoCard.TryFocusList();
    //return;    
}

event int GetCurrentTab()
{
    return SelectedEntryIdx;
    //return ReturnValue;    
}

function InitForPC()
{
    SetVariableBool("customization.pcCloseButton._visible", true);
    //return;    
}

function InitForConsole()
{
    SetVariableBool("customization.pcCloseButton._visible", false);
    //return;    
}

function extGenericButtonClicked(string ActionName)
{
    local name Action;

    Action = name(ActionName);
    switch(Action)
    {
        // End:0x41
        case 'Close':
            BeginClosing();
            // End:0x44
            break;
        // End:0xFFFF
        default:
            break;
    }
    //return;    
}

function bool GetOfferIdForCustomization(CustomizationDefinition Customization, out int OfferIdForCustomization)
{
    local GearboxFramework.GearboxGlobals.EGBXPlatform Platform;

    Platform = class'GearboxGlobals'.static.GetPlatform();
    UnknownLocal_1 = Customization.DlcCustomizationSetDef;
    UnknownLocal_3 = WillowDownloadableContentManager(class'GameEngine'.static.GetDLCManager());
    // End:0x230
    if((UnknownLocal_1 != none) && UnknownLocal_1.PackageDef != none)
    {
        UnknownLocal_5 = 0;
        J0xAF:

        // End:0x230 [Loop If]
        if(UnknownLocal_5 < UnknownLocal_3.TaggedDLC.Length)
        {
            // End:0x226
            if((UnknownLocal_3.TaggedDLC[UnknownLocal_5].PackageId == UnknownLocal_1.PackageDef.PackageId) && UnknownLocal_3.TaggedDLC[UnknownLocal_5].ContentId == UnknownLocal_1.ContentId)
            {
                // End:0x226
                if((int(Platform) != int(2)) || UnknownLocal_3.TaggedDLC[UnknownLocal_5].Tag ~= (GetSonyTitleID()))
                {
                    OfferIdForCustomization = UnknownLocal_3.TaggedDLC[UnknownLocal_5].OfferId;
                    return true;
                }
            }
            ++ UnknownLocal_5;
            // [Loop Continue]
            goto J0xAF;
        }
    }
    return false;
    //return ReturnValue;    
}

exec function MarketplaceDownloadComplete()
{
    // End:0x49
    if(bSelectingFromList)
    {
        CancelHeadCustomization();
        CancelSkinCustomization();
        CharacterCustomizationMenu.SetSelectedEntry(SelectedEntryIdx);
    }
    CacheCustomizations();
    //return;    
}

defaultproperties
{
    MaxNameLength=15
    HeaderText="QUICK CHANGE"
    NoValidHeadCaption="Choose Head!"
    NoValidSkinCaption="Choose Skin!"
    UnlockedText="Unlocked:"
    bDoCameraCollision=false
    bHideMeshInVertSplit=false
    bDoMenuSpring=false
}