/*******************************************************************************
 * InputActionDefinition generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class InputActionDefinition extends GBXDefinition
    native
    hidecategories(Mobile);

enum EInputActionEvent
{
    INPUT_ACTION_Begin,
    INPUT_ACTION_End,
    INPUT_ACTION_MAX
};

var(Actions) const editinline array<editinline BehaviorBase> OnBegin;
var(Actions) const editinline array<editinline BehaviorBase> OnEnd;
var() const bool bAlwaysAvailable;
var(Display) const name ActionName;
