/*******************************************************************************
 * IProtectionTimer generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
interface IProtectionTimer extends Interface
    abstract
    native
    hidecategories(Mobile);

// Export UIProtectionTimer::execIsProtectionTimerActive(FFrame&, void* const)
native function bool IsProtectionTimerActive();

// Export UIProtectionTimer::execEnableProtectionTimer(FFrame&, void* const)
native function EnableProtectionTimer();

// Export UIProtectionTimer::execGetMinimumHealthMaintainedByProtectionTimer(FFrame&, void* const)
native function float GetMinimumHealthMaintainedByProtectionTimer();
