/*******************************************************************************
 * ItemInspectionGFxMovie generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ItemInspectionGFxMovie extends WillowGFxMovie3D
    native(GFx)
    config(Game)
    hidecategories(Mobile);

var transient ItemInspectionGFxMovieDefinition MyInspDef;
var transient float StartTime;
var export editinline transient MeshComponent MyInspectionMesh;
var transient WillowInventoryDefinition InvDef;
var transient Rotator MeshRotation;
var transient Quat MeshRotationQuat;
var transient Quat MeshRotationPitchQuat;
var transient Quat MeshRotationYawQuat;
var transient float CurrentItemScale;
var transient Vector CurrentOffset;
var transient float StartFOV;
var transient float OffsetBounds;
var transient bool bDraggingMouse_LMB;
var transient bool bDraggingMouse_RMB;
var transient bool bReverseIntroRotation;
var transient bool bInvertIntroAlphaPower;
var transient bool CachedWidescreen;
var transient bool bCtrl;
var transient bool bLBDown;
var transient bool bRBDown;
var transient bool bXDown;
var transient bool bRequestInFlight;
var transient IntPoint DragMouseLoc;
var config float MouseDragScale_Rotate;
var config float MouseDragScale_Pan;
var config float MouseWheelScale;
var config float KeyPanScale;
var const localized string TooltipsText_Pan_Mouse;
var const localized string TooltipsText_Pan_Controller;
var const localized string TooltipsText_Rotate_Mouse;
var const localized string TooltipsText_Rotate_Controller;
var const localized string TooltipsText_Zoom_Mouse;
var const localized string TooltipsText_Zoom_Controller;
var const localized string TooltipsText_Screenshot_Keyboard;
var const localized string TooltipsText_Screenshot_Controller;
var const localized string TooltipsText_Close;
var transient Rotator RandomIntroRotation;
var transient float RandomIntroAlphaPower;
var transient ItemCardGFxObject ItemCard;
var CellContentData CardContents;
var int ScreenShotCounter;
var string SerialNumberString;
var string DemoPerkCode;

event bool Start(optional bool StartPaused = false)
{
    UnknownLocal_1
    super.Start(StartPaused);
    // End:0x2B3
    if(UnknownLocal_1)
    {
        MyInspDef = ItemInspectionGFxMovieDefinition(MyDefinition);
        Advance(0);
        __OnInputKey__Delegate = HandleInputKey;
        __OnInputAxis__Delegate = HandleInputAxis;
        CurrentItemScale = MyInspDef.ItemScale;
        StartTime = WPCOwner.WorldInfo.RealTimeSeconds;
        UpdateFrameForAspectRatio(WPCOwner.GetPlayerViewportClient().IsWidescreen());
        StopMouseDrag(false);
        StopMouseDrag(true);
        UpdateTooltips();
        bReverseIntroRotation = FRand() > 0.5;
        bInvertIntroAlphaPower = FRand() > 0.5;
        RandomIntroRotation = MyInspDef.IntroRotationRandomness;
        RandomIntroRotation.Yaw = int(float(RandomIntroRotation.Yaw) * (FRand() - 0.5));
        RandomIntroRotation.Pitch = int(float(RandomIntroRotation.Pitch) * (FRand() - 0.5));
        RandomIntroRotation.Roll = int(float(RandomIntroRotation.Roll) * (FRand() - 0.5));
        RandomIntroAlphaPower = MyInspDef.IntroRotationAlphaPowerRandomness * FRand();
        PlayUISound('ItemInspect_Begin');
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

event UpdateFrameForAspectRatio(bool bWidescreen)
{
    CachedWidescreen = bWidescreen;
    // End:0x4E
    if(CachedWidescreen)
    {
        SingleArgInvokeS("itemInspect.gotoAndStop", "16x9");        
    }
    else
    {
        SingleArgInvokeS("itemInspect.gotoAndStop", "4x3");
    }
    Advance(0);
    ItemCard = ItemCardGFxObject(GetVariableObject("itemInspect.itemCard", class'ItemCardGFxObject'));
    ItemCard.Init();
    SingleArgInvokeF("itemInspect.itemCard.ConfigureForPlayer", float(((WPCOwner.IsPrimaryPlayer()) ? 0 : 1)));
    SingleArgInvokeB("itemInspect.itemCard.SetBottomGlowVisible", false);
    //return;    
}

function bool HandleInputKey(int ControllerId, name ukey, Core.Object.EInputEvent uevent)
{
    // End:0x538
    if(!PlayingIntro())
    {
        switch(ukey)
        {
            // End:0x2E
            case 'XboxTypeS_B':
            // End:0x3A
            case 'Escape':
            // End:0x46
            case 'XboxTypeS_RightThumbStick':
            // End:0x7B
            case 'F':
                // End:0x78
                if(int(uevent) == int(1))
                {
                    Close();
                    UnknownLocal_1 = true;
                }
                // End:0x42D
                break;
            // End:0xD2
            case 'LeftMouseButton':
                // End:0xA9
                if(int(uevent) == int(0))
                {
                    StartMouseDrag(false);                    
                }
                else
                {
                    // End:0xC8
                    if(int(uevent) == int(1))
                    {
                        StopMouseDrag(false);
                    }
                }
                UnknownLocal_1 = true;
                // End:0x42D
                break;
            // End:0x129
            case 'RightMouseButton':
                // End:0x100
                if(int(uevent) == int(0))
                {
                    StartMouseDrag(true);                    
                }
                else
                {
                    // End:0x11F
                    if(int(uevent) == int(1))
                    {
                        StopMouseDrag(true);
                    }
                }
                UnknownLocal_1 = true;
                // End:0x42D
                break;
            // End:0x166
            case 'MouseScrollUp':
                // End:0x163
                if(int(uevent) == int(1))
                {
                    ScaleMesh(MouseWheelScale);
                    UnknownLocal_1 = true;
                }
                // End:0x42D
                break;
            // End:0x1A5
            case 'MouseScrollDown':
                // End:0x1A2
                if(int(uevent) == int(1))
                {
                    ScaleMesh(-MouseWheelScale);
                    UnknownLocal_1 = true;
                }
                // End:0x42D
                break;
            // End:0x1B1
            case 'XboxTypeS_Y':
            // End:0x23D
            case 'P':
                // End:0x23A
                if((int(class'GearboxGlobals'.static.GetPlatform()) == int(0)) && int(uevent) == int(1))
                {
                    SetVariableBool("itemInspect.tooltips._visible", false);
                    ScreenShotCounter = 3;
                    UnknownLocal_1 = true;
                }
                // End:0x42D
                break;
            // End:0x249
            case 'LeftControl':
            // End:0x2A9
            case 'RightControl':
                // End:0x27F
                if(int(uevent) == int(0))
                {
                    bCtrl = true;
                    UnknownLocal_1 = true;                    
                }
                else
                {
                    // End:0x2A6
                    if(int(uevent) == int(1))
                    {
                        bCtrl = false;
                        UnknownLocal_1 = true;
                    }
                }
                // End:0x42D
                break;
            // End:0x2EC
            case 'S':
                // End:0x2E9
                if(bCtrl && int(uevent) == int(1))
                {
                    SaveDemoPerk();
                    UnknownLocal_1 = true;
                }
                // End:0x42D
                break;
            // End:0x356
            case 'XboxTypeS_LeftShoulder':
                // End:0x32C
                if(int(uevent) == int(0))
                {
                    bLBDown = true;
                    UnknownLocal_1 = true;
                    TrySaveDemoPerk();                    
                }
                else
                {
                    // End:0x353
                    if(int(uevent) == int(1))
                    {
                        bLBDown = false;
                        UnknownLocal_1 = true;
                    }
                }
                // End:0x42D
                break;
            // End:0x3C0
            case 'XboxTypeS_RightShoulder':
                // End:0x396
                if(int(uevent) == int(0))
                {
                    bRBDown = true;
                    UnknownLocal_1 = true;
                    TrySaveDemoPerk();                    
                }
                else
                {
                    // End:0x3BD
                    if(int(uevent) == int(1))
                    {
                        bRBDown = false;
                        UnknownLocal_1 = true;
                    }
                }
                // End:0x42D
                break;
            // End:0x42A
            case 'XboxTypes_X':
                // End:0x400
                if(int(uevent) == int(0))
                {
                    bXDown = true;
                    UnknownLocal_1 = true;
                    TrySaveDemoPerk();                    
                }
                else
                {
                    // End:0x427
                    if(int(uevent) == int(1))
                    {
                        bXDown = false;
                        UnknownLocal_1 = true;
                    }
                }
                // End:0x42D
                break;
            // End:0xFFFF
            default:
                break;
        }
        // End:0x535
        if(!UnknownLocal_1 && (int(uevent) == int(0)) || int(uevent) == int(2))
        {
            switch(ukey)
            {
                // End:0x4A4
                case 'Up':
                    PanMesh(0, KeyPanScale);
                    UnknownLocal_1 = true;
                    // End:0x535
                    break;
                // End:0x4D4
                case 'Down':
                    PanMesh(0, -KeyPanScale);
                    UnknownLocal_1 = true;
                    // End:0x535
                    break;
                // End:0x504
                case 'Left':
                    PanMesh(-KeyPanScale, 0);
                    UnknownLocal_1 = true;
                    // End:0x535
                    break;
                // End:0x532
                case 'Right':
                    PanMesh(KeyPanScale, 0);
                    UnknownLocal_1 = true;
                    // End:0x535
                    break;
                // End:0xFFFF
                default:
                    break;
            }
        }
        else
        {            
        }/* !MISMATCHING REMOVE, tried If got Type:Else Position:0x535! */
        else
        {
            UnknownLocal_1 = true;
        }
        return UnknownLocal_1;
        //return ReturnValue;        
    }/* !MISMATCHING REMOVE, tried Else got Type:If Position:0x000! */
}

function bool HandleInputAxis(int ControllerId, name ukey, float Delta, float DeltaTime)
{
    UnknownLocal_1 = false;
    // End:0x24B
    if(!PlayingIntro())
    {
        switch(ukey)
        {
            // End:0x82
            case 'XboxTypeS_LeftX':
                PanMesh((MyInspDef.ItemScale * Delta) * DeltaTime, 0);
                UnknownLocal_1 = true;
                // End:0x248
                break;
            // End:0xDB
            case 'XboxTypeS_LeftY':
                PanMesh(0, (MyInspDef.ItemScale * Delta) * DeltaTime);
                UnknownLocal_1 = true;
                // End:0x248
                break;
            // End:0x13B
            case 'XboxTypeS_RightX':
                RotateMesh(((0.01745329 * MyInspDef.RotationSpeed) * Delta) * DeltaTime, 0);
                UnknownLocal_1 = true;
                // End:0x248
                break;
            // End:0x19B
            case 'XboxTypeS_RightY':
                RotateMesh(0, ((0.01745329 * MyInspDef.RotationSpeed) * Delta) * DeltaTime);
                UnknownLocal_1 = true;
                // End:0x248
                break;
            // End:0x1F1
            case 'XboxTypeS_LeftTriggerAxis':
                ScaleMesh((-MyInspDef.ScaleSpeed * Delta) * DeltaTime);
                UnknownLocal_1 = true;
                // End:0x248
                break;
            // End:0x245
            case 'XboxTypeS_RightTriggerAxis':
                ScaleMesh((MyInspDef.ScaleSpeed * Delta) * DeltaTime);
                UnknownLocal_1 = true;
                // End:0x248
                break;
            // End:0xFFFF
            default:
                break;
        }        
    }
    else
    {
        UnknownLocal_1 = true;
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

function InspectItem(WillowInventory Thing, optional int OverrideValue = -1, optional Engine.WillowInventoryDefinition.ECurrencyType CurrencyType = 0)
{
    local string ControllerPrefix;

    WPCOwner.bViewingThirdPersonMenu && !WillowPlayerPawn(WPCOwner.Pawn).bLastMenuMeshHidden;
    WillowPlayerPawn(WPCOwner.Pawn).SetMenuMeshVisibility(true, true);
    StartFOV = WPCOwner.GetFOVAngle();
    MyInspectionMesh = Thing.ClonePrimaryMeshForUI();
    MyInspectionMesh.SetLightEnvironment(WPCOwner.Pawn.Mesh.LightEnvironment);
    MyInspectionMesh.SetOnlyOwnerSee(true);
    MyInspectionMesh.SetDepthPriorityGroup(2);
    MyInspectionMesh.SetAbsolute(true, true, true);
    MyInspectionMesh.SetRotation(rot(0, 0, 0));
    MyInspectionMesh.SetScale3D(vect(1, 1, 1));
    // End:0x26A
    if(SkeletalMeshComponent(MyInspectionMesh) != none)
    {
        SkeletalMeshComponent(MyInspectionMesh).bIgnoredByFXCoordinator = true;
    }
    // End:0x2AC
    if(StaticMeshComponent(MyInspectionMesh) != none)
    {
        StaticMeshComponent(MyInspectionMesh).bIgnoredByFXCoordinator = true;
    }
    WPCOwner.Pawn.AttachComponent(MyInspectionMesh);
    InvDef = Thing.GetInventoryDefinition();
    MeshRotation = InvDef.UIMeshRotation;
    MeshRotationQuat = QuatFromRotator(MeshRotation);
    MeshRotationPitchQuat = QuatFromRotator(rot(0, 0, 0));
    MeshRotationYawQuat = QuatFromRotator(rot(0, 0, 0));
    // End:0x3CA
    if(WPCOwner.IsPrimaryPlayer())
    {
        ControllerPrefix = "";        
    }
    else
    {
        ControllerPrefix = "p2_";
    }
    CardContents.Tex = GetRecommendedThumbnail(3, 2, Class.Name);
    SetExternalTexture(ControllerPrefix $ "weaptex23", CardContents.Tex);
    CardContents.Inv = Thing;
    CardContents.Mesh = Thing.ClonePrimaryMeshForUI();
    UnknownLocal_1 = class'GearboxGlobals'.static.GetGearboxGlobals().GetRenderTextureManager();
    UnknownLocal_1.SetThumbnailMesh(CardContents.Tex, CardContents.Mesh);
    ItemCard.SetItemCardEx(WPCOwner, IItemCardable(Thing), none, CurrencyType, OverrideValue);
    SingleArgInvokeF("itemInspect.itemCard.ConfigureForPlayer", float(((WPCOwner.IsPrimaryPlayer()) ? 0 : 1)));
    SingleArgInvokeB("itemInspect.itemCard.SetBottomGlowVisible", false);
    OnTick();
    SerialNumberString = Thing.GetSerialNumberString();
    DemoPerkCode = "";
    //return;    
}

event OnClose()
{
    PlayUISound('ItemInspect_End');
    WPCOwner.Pawn.DetachComponent(MyInspectionMesh);
    MyInspectionMesh = none;
    // End:0x100
    if(WPCOwner.bViewingThirdPersonMenu && !WillowPlayerPawn(WPCOwner.Pawn).bLastMenuMeshHidden)
    {
        WillowPlayerPawn(WPCOwner.Pawn).SetMenuMeshVisibility(true, false);
    }
    // End:0x1A2
    if(CardContents.Tex != none)
    {
        FreeGFxThumbnail(CardContents.Tex);
        CardContents.Tex = none;
        CardContents.Mesh = none;
        CardContents.Inv = none;
    }
    super(WillowGFxMovie).OnClose();
    MyInspDef = none;
    bCtrl = false;
    bLBDown = false;
    bRBDown = false;
    bXDown = false;
    bRequestInFlight = false;
    SerialNumberString = "";
    DemoPerkCode = "";
    //return;    
}

// Export UItemInspectionGFxMovie::execRotateMesh(FFrame&, void* const)
native function RotateMesh(float dYaw, float dPitch);

// Export UItemInspectionGFxMovie::execPanMesh(FFrame&, void* const)
native function PanMesh(float dx, float DY);

// Export UItemInspectionGFxMovie::execScaleMesh(FFrame&, void* const)
native function ScaleMesh(float dz);

// Export UItemInspectionGFxMovie::execPlayingIntro(FFrame&, void* const)
native function bool PlayingIntro();

// Export UItemInspectionGFxMovie::execIntroAlpha(FFrame&, void* const)
native function float IntroAlpha();

// Export UItemInspectionGFxMovie::execGetCurrentMeshRotation(FFrame&, void* const)
native function Rotator GetCurrentMeshRotation();

// Export UItemInspectionGFxMovie::execGetCurrentMeshScale(FFrame&, void* const)
native function float GetCurrentMeshScale();

// Export UItemInspectionGFxMovie::execGetBoundsFor(FFrame&, void* const)
native function BoxSphereBounds GetBoundsFor(MeshComponent MeshComponent);

// Export UItemInspectionGFxMovie::execStartMouseDrag(FFrame&, void* const)
native function StartMouseDrag(bool bRMB);

// Export UItemInspectionGFxMovie::execStopMouseDrag(FFrame&, void* const)
native function StopMouseDrag(bool bRMB);

// Export UItemInspectionGFxMovie::execHandleMouseDrag(FFrame&, void* const)
native function HandleMouseDrag(int dx, int DY);

// Export UItemInspectionGFxMovie::execMakeQuatFromAxisAndAngle(FFrame&, void* const)
native function Quat MakeQuatFromAxisAndAngle(Vector Axis, float Angle);

event UpdateTooltips()
{
    local string Tips, PanString, RotateString, ZoomString, ScreenshotString;

    // End:0x11
    if(ScreenShotCounter > 0)
    {
        return;
    }
    UnknownLocal_1 = OffsetBounds > 0.0001;
    // End:0xD9
    if((int(class'GearboxGlobals'.static.GetPlatform()) != int(0)) || WPCOwner.PlayerInput.bUsingGamepad)
    {
        PanString = TooltipsText_Pan_Controller;
        RotateString = TooltipsText_Rotate_Controller;
        ZoomString = TooltipsText_Zoom_Controller;
        ScreenshotString = TooltipsText_Screenshot_Controller;        
    }
    else
    {
        PanString = TooltipsText_Pan_Mouse;
        RotateString = TooltipsText_Rotate_Mouse;
        ZoomString = TooltipsText_Zoom_Mouse;
        ScreenshotString = TooltipsText_Screenshot_Keyboard;
    }
    // End:0x167
    if(!UnknownLocal_1)
    {
        PanString = ("<font color='#666666'>" $ PanString) $ "</font>";
    }
    // End:0x1F3
    if(int(class'GearboxGlobals'.static.GetPlatform()) == int(0))
    {
        Tips = (((((((RotateString $ "    ") $ PanString) $ "    ") $ ZoomString) $ "    ") $ ScreenshotString) $ "    ") $ TooltipsText_Close;        
    }
    else
    {
        Tips = (((((RotateString $ "    ") $ PanString) $ "    ") $ ZoomString) $ "    ") $ TooltipsText_Close;
    }
    SetVariableBool("itemInspect.tooltips._visible", true);
    SetVariableString("itemInspect.tooltips.tooltips.htmlText", ResolveDataStoreMarkup(Tips));
    SetVariableNumber("itemInspect.tooltips.bkgd._width", GetVariableNumber("itemInspect.tooltips.tooltips.textWidth") * 1.15);
    //return;    
}

function TrySaveDemoPerk()
{
    // End:0x35
    if((bLBDown && bRBDown) && bXDown)
    {
        SaveDemoPerk();
    }
    //return;    
}

function SaveDemoPerk()
{
    local SparkInterface Spark;
    local string JsonString, URL;
    local HttpParameters HttpParameters;

    // End:0x0F
    if(bRequestInFlight)
    {
        return;
    }
    UnknownLocal_1 = false;
    // End:0x3E
    if(Len(DemoPerkCode) > 0)
    {
        ShowDemoPerkCreatedDialog(true, DemoPerkCode);        
    }
    else
    {
        Spark = class'GearboxEngine'.static.GetSparkInterface();
        UnknownLocal_3 = Spark.GetGearboxAccountData(WPCOwner.GetMyControllerId());
        // End:0x328
        if((UnknownLocal_3 != none) && UnknownLocal_3.RequestId != "")
        {
            UnknownLocal_5 = UnknownLocal_3.GetService('DemoPerk');
            // End:0x31E
            if(UnknownLocal_5 != none)
            {
                UnknownLocal_7 = new class'JsonObject';
                UnknownLocal_7.SetStringValue("serialnumber", SerialNumberString);
                UnknownLocal_7.SetStringValue("request_id", UnknownLocal_3.RequestId);
                UnknownLocal_7.SetStringValue("language", Locs(GetLanguage()));
                JsonString = UnknownLocal_7.EncodeJson(UnknownLocal_7);
                URL = UnknownLocal_5.GetParameter("EndpointUrl") $ "/v1/demoperk";
                HttpParameters.ServiceConfiguration = UnknownLocal_5;
                HttpParameters.Method = 0;
                HttpParameters.ContentType = 2;
                HttpParameters.AcceptsType = 2;
                UnknownLocal_9 = Spark.IssueSparkStringRequest(HttpParameters, URL, JsonString, HandleCreateDemoPerkResponse);
                // End:0x31B
                if(UnknownLocal_9 != 0)
                {
                    bRequestInFlight = true;
                }                
            }
            else
            {
                UnknownLocal_1 = true;
            }            
        }
        else
        {
            UnknownLocal_1 = true;
        }
        // End:0x357
        if(!bRequestInFlight && !UnknownLocal_1)
        {
            ShowDemoPerkCreatedDialog(false, "");
        }
    }
    bCtrl = false;
    bLBDown = false;
    bRBDown = false;
    bXDown = false;
    //return;    
}

function HandleCreateDemoPerkResponse(const out SparkResult Result)
{
    local ArchwayResult Archway;

    bRequestInFlight = false;
    // End:0xC6
    if((class'GearboxAccountData'.static.ExtractArchwayResultJson(Result.ResponseBody, Archway) && Archway.Success) && Archway.Messages.Length > 0)
    {
        ShowDemoPerkCreatedDialog(true, Archway.Messages[0]);        
    }
    else
    {
        ShowDemoPerkCreatedDialog(false, "");
    }
    //return;    
}

function ShowDemoPerkCreatedDialog(bool Success, string Code)
{
    local string DemoPerkCodeMarkup;

    DemoPerkCode = Code;
    UnknownLocal_1 = WPCOwner.GFxUIManager.ShowDialog();
    UnknownLocal_1.AutoLocEnable("WillowMenu", "dlg");
    UnknownLocal_1.AutoAppendButton('OK');
    UnknownLocal_1.DlgCaptionMarkup = "Thank You For Playing Borderlands 2!";
    DemoPerkCodeMarkup = "<font size='30' color='#00BDF3' letterspacing='6'>CODE</font>";
    // End:0x21C
    if(Success)
    {
        UnknownLocal_1.DlgTextMarkup = "Write this Loot Code on your card. Remember to give it to your Demo Supervisor before you leave.

Collect your loot when Borderlands 2 is released!

Your Loot Code:     " $ Repl(DemoPerkCodeMarkup, "CODE", DemoPerkCode);        
    }
    else
    {
        UnknownLocal_1.DlgTextMarkup = "Your Loot Code could not be created.
Please try again or contact your Demo Supervisor.";
    }
    UnknownLocal_1.ApplyLayout();
    //return;    
}

defaultproperties
{
    MouseDragScale_Rotate=0.005
    MouseDragScale_Pan=0.1
    MouseWheelScale=0.1
    KeyPanScale=10
    TooltipsText_Pan_Mouse="[<Strings:WillowGame.GameMappedStrings.GMS_RightMouseButton>] Pan"
    TooltipsText_Pan_Controller="<StringAliasMap:XboxTypeS_LeftX> Pan"
    TooltipsText_Rotate_Mouse="[<Strings:WillowGame.GameMappedStrings.GMS_LeftMouseButton>] Rotate"
    TooltipsText_Rotate_Controller="<StringAliasMap:XboxTypeS_RightX> Rotate"
    TooltipsText_Zoom_Mouse="[<Strings:WillowGame.GameMappedStrings.GMS_MouseScrollUp>/<Strings:WillowGame.GameMappedStrings.GMS_MouseScrollDown>] Zoom"
    TooltipsText_Zoom_Controller="<StringAliasMap:XboxTypeS_LeftTrigger><StringAliasMap:XboxTypeS_RightTrigger> Zoom"
    TooltipsText_Screenshot_Keyboard="[<Strings:WillowGame.GameMappedStrings.GMS_P>] Screenshot"
    TooltipsText_Screenshot_Controller="<StringAliasMap:XboxTypeS_Y> Screenshot"
    TooltipsText_Close="<StringAliasMap:GFx_Cancel> Close"
    CardContents=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    TickRateSeconds=0.01
    bCloseOnDeath=true
    bOnlyOwnerFocusable=true
    bDiscardNonOwnerInput=true
    SceneDPG=ESceneDepthPriorityGroup.SDPG_World
}