/*******************************************************************************
 * ItemPartDefinition generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ItemPartDefinition extends WillowInventoryPartDefinition
    native
    hidecategories(Mobile)
    autoexpandcategories(PartType)
    implements(IBehaviorProvider);

var private native const noexport Pointer VfTable_IIBehaviorProvider;
var(PartType) const WillowItemTypes.EItemPartType PartType;
var(NamingTitles) const array<ItemNamePartDefinition> TitleList;
var(NamingPrefixes) const array<ItemNamePartDefinition> PrefixList;
var BehaviorProviderDefinition BehaviorProviderDefinition;
var(ItemAttributeEffects) const array<AttributeEffectData> ExternalAttributeEffects;
var(ItemAttributeEffects) const array<AttributeEffectData> ItemAttributeEffects;
var(ItemCard) const array<AttributePriorityData> ItemCardAttributes;
var(ItemCard) const export editinline array<export editinline AttributePresentationDefinition> CustomPresentations;

// Export UItemPartDefinition::execGetBehaviorProviderDefinition(FFrame&, void* const)
native function BehaviorProviderDefinition GetBehaviorProviderDefinition();

// Export UItemPartDefinition::execSetBehaviorProviderDefinition(FFrame&, void* const)
native function SetBehaviorProviderDefinition(BehaviorProviderDefinition NewBehaviorProviderDefinition);

// Export UItemPartDefinition::execOnCreate(FFrame&, void* const)
native final function OnCreate(const out BehaviorConsumerHandle ConsumerHandle);

// Export UItemPartDefinition::execOnPickupAssociated(FFrame&, void* const)
native final function OnPickupAssociated(const out BehaviorConsumerHandle ConsumerHandle, Object Pickup);

// Export UItemPartDefinition::execOnPickupDisassociated(FFrame&, void* const)
native final function OnPickupDisassociated(const out BehaviorConsumerHandle ConsumerHandle, Object Pickup);
