/*******************************************************************************
 * LANServerBrowserGFxObject generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class LANServerBrowserGFxObject extends GFxObject within GFxMoviePlayer
    hidecategories(Mobile);

function AddServerListEntry(string ServerName, int CurrentPlayers, int MaxPlayers, string CharInfo, string MissionInfo, string ConnectionStength, string Ping)
{
    ActionScriptVoid("AddServerListEntry");
    //return;    
}

function BeginConfigureServerList()
{
    ActionScriptVoid("BeginConfigureServerList");
    //return;    
}

function EndConfigureServerList()
{
    ActionScriptVoid("EndConfigureServerList");
    //return;    
}

function SetGameCountString(string GameCountString)
{
    ActionScriptVoid("SetGameCountString");
    //return;    
}

function SetSearchingForGames(bool bSearching)
{
    ActionScriptVoid("SetSearchingForGames");
    //return;    
}

function SetSelectedServerIndex(int SelectedIndex)
{
    ActionScriptVoid("SetSelectedServerIndex");
    //return;    
}

function int GetSelectedServerIndex()
{
    return ActionScriptInt("GetSelectedServerIndex");
    //return ReturnValue;    
}

function SetSortTypeButtonLabel(string Label)
{
    ActionScriptVoid("SetSortTypeButtonLabel");
    //return;    
}

function SetSortDirectionButtonLabel(string Label)
{
    ActionScriptVoid("SetSortDirectionButtonLabel");
    //return;    
}
