/*******************************************************************************
 * MissionItemDefinition generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class MissionItemDefinition extends UsableItemDefinition
    native
    hidecategories(Mobile,AttributeSlot,AttributeSlot_Effects,AttributeSlot_Upgrades);

var(Missions) const bool bAlwaysDropMissionPickup;
var(Missions) const bool bUpdateMissionObjectiveWhenUsed;
var(Missions) const bool bMissionWaypoint;
var(MissionDirector) const bool bUniqueMissionDirector;
var(Missions) const MissionObjectiveDefinition AssociatedMissionObjective;
var(MissionDirector) const MissionDefinition MissionDirective;
var(MissionDirector) const GFxMovieDefinition DirectiveMovieDefinition;

function bool ShouldPlayerAutomaticallyPickup(PlayerController PC)
{
    // End:0x3E
    if((MissionDirective == none) && PC.IsUsingVehicle(false))
    {
        UnknownLocal_1 = true;        
    }
    else
    {
        UnknownLocal_1 = super(WillowInventoryDefinition).ShouldPlayerAutomaticallyPickup(PC);
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

function bool CanPickupInBulk()
{
    return (MissionDirective == none) && bPickupInBulk;
    //return ReturnValue;    
}

defaultproperties
{
    bMissionWaypoint=true
    bUniqueMissionDirector=true
    bPlayerUseItemOnPickup=true
    bItemNameIsFullName=true
    InventoryClass='WillowMissionItem'
    bPickupInBulk=true
}