/*******************************************************************************
 * PsychoInputContextSelector generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class PsychoInputContextSelector extends DefaultInputContextSelector within WillowPlayerController
    hidecategories(Mobile);

function name SelectContext()
{
    UnknownLocal_1 = WillowPlayerPawn(Outer.Pawn);
    // End:0x126
    if(UnknownLocal_1 != none)
    {
        // End:0x85
        if(UnknownLocal_1.IsInjured() && UnknownLocal_1.UseInjuredDefinitionOverride > 0)
        {
            return 'SuicidalAttack';            
        }
        else
        {
            // End:0x126
            if(UnknownLocal_1.IsActionSkillRunning())
            {
                // End:0x11C
                if(Outer.IsUsingVehicleEx(true, UnknownLocal_3))
                {
                    // End:0x11C
                    if(UnknownLocal_3.IsA('WillowWeaponPawn'))
                    {
                        // End:0x11C
                        if(Outer.Pawn != UnknownLocal_3)
                        {
                            return 'DefaultVehicleAttachedRider';
                        }
                    }
                }
                return 'Buzzaxe';
            }
        }
    }
    return super.SelectContext();
    //return ReturnValue;    
}
