/*******************************************************************************
 * ReferenceSet generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ReferenceSet extends Object
    hidecategories(Mobile);

struct ObjectReference
{
    var() Object Obj;

    structdefaultproperties
    {
        Obj=none
    }
};

var() array<ObjectReference> References;
