/*******************************************************************************
 * SeqEvent_WorldDiscoveryArea generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class SeqEvent_WorldDiscoveryArea extends SequenceEvent
    native(Sequence)
    forcescriptorder(true)
    hidecategories(Mobile,Object);

defaultproperties
{
    MaxTriggerCount=0
    bClientSideOnly=true
    bAutoActivateOutputLinks=true
    VariableLinks(0)=(ExpectedType='Engine.SeqVar_Object',LinkedVariables=none,LinkDesc="Instigator",LinkVar=None,PropertyName=None,bWriteable=true,bSequenceNeverReadsOnlyWritesToThisVar=false,bModifiesLinkedObject=false,bHidden=false,bClampedMax=false,bClampedMin=false,bMoving=false,bAllowAnyType=false,MinVars=1,MaxVars=255,DrawX=0,CachedProperty=none,OverrideDelta=0)
    ObjName="WorldDiscoveryArea"
    ObjCategory="WorldDiscoveryArea"
}