/*******************************************************************************
 * SpecialMove_Perch generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class SpecialMove_Perch extends WillowAnimDefinition
    native
    editinlinenew
    hidecategories(Mobile,Object,SearchOrder,Expressions,HandIK,Bone,Chain);

defaultproperties
{
    EndingCondition=EEndingCondition.EC_OnAnimEnd
}