/*******************************************************************************
 * TradingGFxMovie generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class TradingGFxMovie extends WillowInventoryGFxMovie
    native(GFx)
    config(UI)
    hidecategories(Mobile);

var const localized string OfferingString;
var const localized string ReceivingString;
var const localized string TooltipString;
var const localized string ToolTipString_Split;
var const localized string ReadyString;
var const localized string TradeString;
var const localized string DuelString;
var const localized string CancelDuelString;
var const localized string CancelTradeString;
var const localized string WinnerTakeAllString;
var const localized string NoRoomForItemsString;
var transient int MyMoneyOffer;
var transient int CachedPartnerMoneyOffer;
var transient WillowTradeManager.PlayerTradingStance CachedMyStance;
var transient WillowTradeManager.PlayerTradingStance CachedPartnerStance;
var CellContentData OfferedContents[8];
var array<WillowInventory> BackpackThings;
var TradingPanelGFxObject TradingPanel;
var TradingGFxDefinition TradingDef;
var SortFilterConfiguration CompareConfiguration;
var array<SortFilterConfiguration> GenericSortConfigurations;
var int GenericSortConfigIndex;
var bool bDoDuelingCheck;
var bool bDuelingAllowed;
var bool bUseTextboxForMoney;
var transient string LastMoneyOfferString;

event bool Start(optional bool StartPaused = false)
{
    UnknownLocal_1
    super.Start(StartPaused);
    // End:0x72
    if(UnknownLocal_1)
    {
        Advance(0);
        TradingDef = TradingGFxDefinition(MyDefinition);
        CardContents.Length = 1;
        InitTradingScreen();
        RefreshContents();
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

function InitForPC()
{
    SetVariableBool("trading.offers.PCPlayerMoneyOffer.disabled", false);
    SetVariableBool("trading.offers.PCPlayerMoneyOffer._visible", true);
    SetVariableBool("trading.offers.PCPlayerMoneyOffer.visible", true);
    SetVariableBool("trading.offers.playerMoneyOffer._visible", false);
    SetVariableBool("trading.pcCloseButton._visible", true);
    bUseTextboxForMoney = true;
    //return;    
}

function InitForConsole()
{
    SetVariableBool("trading.offers.PCPlayerMoneyOffer.disabled", true);
    SetVariableBool("trading.offers.PCPlayerMoneyOffer._visible", false);
    SetVariableBool("trading.offers.PCPlayerMoneyOffer.visible", false);
    SetVariableBool("trading.offers.playerMoneyOffer._visible", true);
    SetVariableBool("trading.pcCloseButton._visible", false);
    bUseTextboxForMoney = false;
    //return;    
}

function RefreshContents()
{
    FreeCellData();
    PrepareListOfAllInventory();
    // End:0x52
    if(TradingPanel == none)
    {
        TradingPanel = TradingPanelGFxObject(GetVariableObject("trading", class'TradingPanelGFxObject'));
    }
    TradingPanel.Init(self);
    InitCellData();
    __OnInputKey__Delegate = TradingPanel.PanelOnInputKey;
    TradingPanel.ConfigureForPlayer(float(((WPCOwner.IsPrimaryPlayer()) ? 0 : 1)));
    TradingPanel.SetBackpackList(BackpackThings);
    TradingPanel.Refresh();
    //return;    
}

function PrepareListOfAllInventory()
{
    local array<WillowWeapon> ReadiedWeapons, UnReadiedWeapons;
    local array<WillowItem> AllItems;

    BackpackThings.Length = 0;
    WPCOwner.GetInventoryLists(ReadiedWeapons, UnReadiedWeapons, AllItems, 0);
    // End:0x6B
    foreach UnReadiedWeapons(UnknownLocal_1,)
    {
        AddInventory(UnknownLocal_1);        
    }    
    // End:0x8F
    foreach ReadiedWeapons(UnknownLocal_1,)
    {
        AddInventory(UnknownLocal_1);        
    }    
    // End:0xB3
    foreach AllItems(UnknownLocal_3,)
    {
        AddInventory(UnknownLocal_3);        
    }    
    UnknownLocal_5 = false;
    UnknownLocal_7 = GetTradeManager();
    UnknownLocal_9 = 0;
    J0xD2:

    // End:0x1BD [Loop If]
    if(UnknownLocal_9 < (8 / 2))
    {
        OfferedContents[UnknownLocal_9].Inv = GetLocalInvForTradeSlot(UnknownLocal_7.MyInvOffered[UnknownLocal_9]);
        OfferedContents[UnknownLocal_9 + (8 / 2)].Inv = GetLocalInvForTradeSlot(UnknownLocal_7.PartnerInvOffered[UnknownLocal_9]);
        // End:0x1B3
        if(OfferedContents[UnknownLocal_9].Inv != none)
        {
            UnknownLocal_5 = true;
        }
        ++ UnknownLocal_9;
        // [Loop Continue]
        goto J0xD2;
    }
    // End:0x1D3
    if(UnknownLocal_5)
    {
        BackpackThings.AddItem(none;
    }
    //return;    
}

function AddInventory(WillowInventory WInv)
{
    // End:0x2F
    if(!IsOffering(WInv, false))
    {
        BackpackThings.AddItem(WInv;
    }
    //return;    
}

function bool IsOffering(WillowInventory WInv, bool bPartner)
{
    UnknownLocal_1 = GetTradeManager();
    return (UnknownLocal_1 != none) && UnknownLocal_1.FindInventorySlot(WInv, bPartner) != -1;
    //return ReturnValue;    
}

function InitCellData()
{
    local string ControllerPrefix;

    ControllerPrefix = ((GetPC().IsPrimaryPlayer()) ? "" : "p2_");
    // End:0x49
    if(!RTM != none)
    {
        return;
    }
    UnknownLocal_1 = 0;
    J0x50:

    // End:0x204 [Loop If]
    if(UnknownLocal_1 < 8)
    {
        // End:0x197
        if(OfferedContents[UnknownLocal_1].Tex == none)
        {
            OfferedContents[UnknownLocal_1].Tex = GetRecommendedThumbnail(0, 0);
            OfferedContents[UnknownLocal_1].Mesh = ((OfferedContents[UnknownLocal_1].Inv != none) ? OfferedContents[UnknownLocal_1].Inv.ClonePrimaryMeshForUI() : none);
            SetExternalTexture(ControllerPrefix $ TradingDef.ExternalTextureMap[UnknownLocal_1], OfferedContents[UnknownLocal_1].Tex);
        }
        RTM.SetThumbnailMesh(OfferedContents[UnknownLocal_1].Tex, OfferedContents[UnknownLocal_1].Mesh);
        ++ UnknownLocal_1;
        // [Loop Continue]
        goto J0x50;
    }
    // End:0x2A9
    if(CardContents[0].Tex == none)
    {
        CardContents[0].Tex = GetRecommendedThumbnail(3, 2);
        SetExternalTexture(ControllerPrefix $ TradingDef.CardExternalTextureMap[0], CardContents[0].Tex);
    }
    //return;    
}

// Export UTradingGFxMovie::execGetTradeManager(FFrame&, void* const)
native simulated function WillowTradeManager GetTradeManager();

function SetTooltips()
{
    local string S;

    // End:0x117
    if(!class'Engine'.static.IsSplitScreen())
    {
        S = TooltipString;
        S = Repl(S, "%1", ColorizeTooltipText(Localize("InvBar", "SortBar", "WillowMenu"), TradingPanel.GetSelectedThing() == none));
        S = Repl(S, "%2", ColorizeTooltipText(Localize("InvBar", "InspectBar", "WillowMenu"), TradingPanel.GetSelectedThing() == none));        
    }
    else
    {
        S = ToolTipString_Split;
        S = Repl(S, "%1", ColorizeTooltipText(Localize("InvBar", "SortBar", "WillowMenu"), TradingPanel.GetSelectedThing() == none));
    }
    SetVariableString("tooltips.tooltips.htmlText", ResolveDataStoreMarkup(S));
    //return;    
}

function InitTradingScreen()
{
    UnknownLocal_1 = WillowPlayerReplicationInfo(GetPC().PlayerReplicationInfo);
    // End:0x60
    if(UnknownLocal_1 != none)
    {
        SetPlayerInventoryMoney(UnknownLocal_1.GetCurrencyOnHand(0));
    }
    SetVariableString("trading.offers.offeringText.text", OfferingString);
    SetVariableString("trading.offers.receivingText.text", ReceivingString);
    SetTooltips();
    SetVariableString("trading.offers.partnerTrade.partnerTradeStatus.TradeDuelText.text", TradeString);
    SetVariableString("trading.offers.partnerDuel.partnerDuelStatus.TradeDuelText.text", DuelString);
    SetVariableString("trading.offers.playerTradeButton.playerReadyStatus.readyText.text", TradeString);
    SetVariableString("trading.offers.playerDuelButton.playerDuelStatus.TradeDuelText.text", DuelString);
    SetPlayerMoneyOffer(0);
    SetPartnerMoneyOffer(0);
    SetVariableBool("trading.offers.popup._visible", false);
    SingleArgInvokeS("trading.offers.readyPlayer.gotoAndStop", "notReady");
    SingleArgInvokeS("trading.offers.readyPartner.gotoAndStop", "notReady");
    SetVariableBool("trading.offers.playerDuelButton.disabled", true);
    SetVariableBool("trading.offers.playerDuelButton._visible", false);
    //return;    
}

event BeginClosing()
{
    TweenOut();
    super(WillowGFxThirdPersonMovie).BeginClosing();
    //return;    
}

function TweenOut()
{
    ActionScript("TweenOut");
    //return;    
}

function extExitMoneyWidget(float fMoney)
{
    UpdateMoneyOffer(int(fMoney));
    //return;    
}

function UpdateMoneyOffer(int iMoney)
{
    MyMoneyOffer = Max(iMoney, 0);
    UnknownLocal_1 = WillowPlayerReplicationInfo(GetPC().PlayerReplicationInfo);
    // End:0xA7
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_3 = UnknownLocal_1.GetCurrencyOnHand(0);
        // End:0xA7
        if(MyMoneyOffer > UnknownLocal_3)
        {
            MyMoneyOffer = UnknownLocal_3;
            SetPlayerMoneyOffer(MyMoneyOffer);
        }
    }
    GetTradeManager().UpdateCashOffered(MyMoneyOffer);
    SetVariableString("trading.offers.PCPlayerMoneyOffer.text", "" $ string(MyMoneyOffer));
    //return;    
}

event OnClose()
{
    FreeCellData();
    // End:0x3A
    if((GetTradeManager()) != none)
    {
        GetTradeManager().OnUIClosed();
    }
    WPCOwner.GFxUIManager.CloseMovie(WPCOwner.GetWillowGlobals().GetGlobalsDefinition().ItemInspectionMovieDefinition);
    super.OnClose();
    //return;    
}

simulated event SetPlayerMoneyOffer(int PlayerMoneyOffer)
{
    ActionScript("trading.offers.playerMoneyOffer.SetValue");
    //return;    
}

simulated event SetPartnerMoneyOffer(int PartnerMoneyOffer)
{
    ActionScript("trading.offers.partnerMoneyOffer.SetValue");
    //return;    
}

simulated event SetPlayerInventoryMoney(int Money)
{
    ActionScript("trading.playerMoney.SetValue");
    //return;    
}

simulated event UnselectActionButtons()
{
    ActionScript("UnselectActionButtons");
    SingleArgInvokeS("trading.offers.readyPlayer.gotoAndStop", "notReady");
    TradingPanel.OffersPanel.bSelectedTradeAction = false;
    TradingPanel.OffersPanel.bSelectedDuelAction = false;
    GetTradeManager().UpdateStance(0);
    CachedMyStance = 0;
    UpdateTimer();
    //return;    
}

simulated function extSetTrade(bool bNewTrade)
{
    UpdateMoneyOfferFromTextbox();
    // End:0x48
    if(bNewTrade)
    {
        GetTradeManager().UpdateStance(1);
        CachedMyStance = 1;        
    }
    else
    {
        GetTradeManager().UpdateStance(0);
        CachedMyStance = 0;
    }
    SingleArgInvokeS("trading.offers.readyPlayer.gotoAndStop", ((bNewTrade) ? "ready" : "notReady"));
    UpdateTimer();
    TradingPanel.OffersPanel.bSelectedTradeAction = bNewTrade;
    //return;    
}

simulated function extSetDuel(bool bNewDuel)
{
    // End:0x22
    if(!!bNewDuel || bDuelingAllowed)
    {
        return;
    }
    UpdateMoneyOfferFromTextbox();
    // End:0x6A
    if(bNewDuel)
    {
        GetTradeManager().UpdateStance(2);
        CachedMyStance = 2;        
    }
    else
    {
        GetTradeManager().UpdateStance(0);
        CachedMyStance = 0;
    }
    SingleArgInvokeS("trading.offers.readyPlayer.gotoAndStop", ((bNewDuel) ? "ready" : "notReady"));
    UpdateTimer();
    TradingPanel.OffersPanel.bSelectedDuelAction = bNewDuel;
    //return;    
}

// Export UTradingGFxMovie::execUpdateTimer(FFrame&, void* const)
native simulated function UpdateTimer();

function WillowInventory GetOfferedCellInventory(int CellIndex)
{
    return OfferedContents[CellIndex].Inv;
    //return ReturnValue;    
}

function OnPartnerInvChanged()
{
    UnselectActionButtons();
    RefreshContents();
    //return;    
}

function WillowInventory GetLocalInvForTradeSlot(TradeSlot Slot)
{
    // End:0x68
    if((Slot.WInv != none) && int(Slot.Status) != int(0))
    {
        return Slot.WInv;
    }
    return none;
    //return ReturnValue;    
}

function FreeCellData()
{
    UnknownLocal_1 = 0;
    J0x07:

    // End:0xDD [Loop If]
    if(UnknownLocal_1 < 8)
    {
        // End:0x67
        if(OfferedContents[UnknownLocal_1].Tex != none)
        {
            FreeGFxThumbnail(OfferedContents[UnknownLocal_1].Tex);
        }
        OfferedContents[UnknownLocal_1].Tex = none;
        OfferedContents[UnknownLocal_1].Mesh = none;
        OfferedContents[UnknownLocal_1].Inv = none;
        ++ UnknownLocal_1;
        // [Loop Continue]
        goto J0x07;
    }
    // End:0x129
    if(CardContents[0].Tex != none)
    {
        FreeGFxThumbnail(CardContents[0].Tex);
    }
    CardContents[0].Tex = none;
    CardContents[0].Mesh = none;
    CardContents[0].Inv = none;
    //return;    
}

function extMoneyWidgetActivated(bool bActivated)
{
    TradingPanel.OffersPanel.bUsingMoneyWidget = bActivated;
    //return;    
}

function extGenericButtonClicked(string ActionName)
{
    local name Action;

    Action = name(ActionName);
    switch(Action)
    {
        // End:0x41
        case 'Close':
            BeginClosing();
            // End:0xA4
            break;
        // End:0x71
        case 'arrowleft':
            TradingPanel.SwitchFocus(0);
            // End:0xA4
            break;
        // End:0xA1
        case 'arrowright':
            TradingPanel.SwitchFocus(1);
            // End:0xA4
            break;
        // End:0xFFFF
        default:
            break;
    }
    //return;    
}

function bool UpdateMoneyOfferFromTextbox()
{
    local string MoneyOfferString;

    UnknownLocal_1 = false;
    // End:0xD3
    if(bUseTextboxForMoney)
    {
        MoneyOfferString = GetVariableString("trading.offers.PCPlayerMoneyOffer.textField.text");
        // End:0xD3
        if(LastMoneyOfferString != MoneyOfferString)
        {
            UpdateMoneyOffer(int(MoneyOfferString));
            LastMoneyOfferString = GetVariableString("trading.offers.PCPlayerMoneyOffer.textField.text");
            UnknownLocal_1 = true;
        }
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

defaultproperties
{
    OfferingString="OFFERING"
    ReceivingString="RECEIVING"
    TooltipString="<StringAliasMap:GFx_Accept> Select    %1    %2    <StringAliasMap:GFx_Cancel> Cancel"
    ToolTipString_Split="<StringAliasMap:GFx_Accept> Select    %1    <StringAliasMap:GFx_Cancel> Cancel"
    ReadyString="READY!"
    TradeString="TRADE!"
    DuelString="DUEL!"
    CancelTradeString="<StringAliasMap:GFx_Cancel> Cancel Trade"
    WinnerTakeAllString="Winner Takes All!"
    NoRoomForItemsString="INVENTORY FULL"
    OfferedContents[0]=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    OfferedContents[1]=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    OfferedContents[2]=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    OfferedContents[3]=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    OfferedContents[4]=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    OfferedContents[5]=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    OfferedContents[6]=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    OfferedContents[7]=(Tex=none,Mesh=none,Inv=none,ExtArrayIndex=-1)
    GenericSortConfigurations(0)=(SortType=EInventorySortType.IST_MajorTypeThenRarityThenSubtype,FilterType=EInventoryFilterType.IFT_NoFilter,CategoryType=ECategoryAssignmentType.CAType_InventoryType,SortTitleLookupKey="all")
    GenericSortConfigurations(1)=(SortType=EInventorySortType.IST_MajorTypeThenSubtypeThenRarity,FilterType=EInventoryFilterType.IFT_FilterNonWeapons,CategoryType=ECategoryAssignmentType.CAType_WeaponType,SortTitleLookupKey="types")
    GenericSortConfigurations(2)=(SortType=EInventorySortType.IST_Manufacturer,FilterType=EInventoryFilterType.IFT_FilterNonWeapons,CategoryType=ECategoryAssignmentType.CAType_Manufacturers,SortTitleLookupKey="manufacturers")
    GenericSortConfigurations(3)=(SortType=EInventorySortType.IST_MajorTypeThenRarityThenSubtype,FilterType=EInventoryFilterType.IFT_FilterWeapons,CategoryType=ECategoryAssignmentType.CAType_InventoryType,SortTitleLookupKey="items")
    bDoDuelingCheck=true
}