/*******************************************************************************
 * WeaponShotDebug generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WeaponShotDebug extends Actor
    notplaceable
    hidecategories(Mobile,Navigation,MovementReplication);

var() export editinline ArrowComponent AimArrow;
var() export editinline ArrowComponent ShotArrow;
var() export editinline ArrowComponent SpreadShotArrow;

function FinalizeComponentInitialization(optional bool bHideAimArrow, optional bool bHideShotArrow, optional bool bHideSpreadArrow)
{
    !bHideAimArrow;
    AttachComponent(AimArrow);
    // End:0x47
    if(!bHideShotArrow)
    {
        AttachComponent(ShotArrow);
    }
    // End:0x69
    if(!bHideSpreadArrow)
    {
        AttachComponent(SpreadShotArrow);
    }
    //return;    
}

defaultproperties
{
    begin object name=AimArrowComponent class=DebugArrowComponent
        ArrowColor=(B=0,G=255,R=0,A=255)
        ArrowSize=64
    object end
    // Reference: DebugArrowComponent'Default__WeaponShotDebug.AimArrowComponent'
    AimArrow=AimArrowComponent
    begin object name=ShotArrowComponent class=DebugArrowComponent
        ArrowColor=(B=255,G=0,R=0,A=255)
        ArrowSize=64
        AbsoluteRotation=true
    object end
    // Reference: DebugArrowComponent'Default__WeaponShotDebug.ShotArrowComponent'
    ShotArrow=ShotArrowComponent
    begin object name=SpreadShotArrowComponent class=DebugArrowComponent
        ArrowSize=64
        AbsoluteRotation=true
    object end
    // Reference: DebugArrowComponent'Default__WeaponShotDebug.SpreadShotArrowComponent'
    SpreadShotArrow=SpreadShotArrowComponent
    CollisionType=ECollisionType.COLLIDE_CustomDefault
    LifeSpan=30
}