/*******************************************************************************
 * WillowPickup generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowPickup extends DroppedPickup
    native
    nativereplication
    hidecategories(Mobile,Navigation,MovementReplication)
    implements(IChangeUsabilityBehavior,IMission,IMissionDirector,IFocusable);

const PICKUP_SHRINK_STEP_TIME = 0.1f;

struct native PickupMemento
{
    var Rotator Rotation;
    var bool bIsAttachedToSomething;

    structdefaultproperties
    {
        Rotation=(Pitch=0,Yaw=0,Roll=0)
        bIsAttachedToSomething=false
    }
};

var private native const noexport Pointer VfTable_IIMission;
var private native const noexport Pointer VfTable_IIMissionDirector;
var private native const noexport Pointer VfTable_IIFocusable;
var export editinline transient ParticleSystemComponent PickupParticleComponent;
var repnotify transient ParticleSystem PickupParticles;
var native const RigidBodyState RBState;
var native const float AngErrorAccumulator;
var private repnotify bool bPickupable;
var repnotify bool bPickupAtRest;
var bool bIsPickupAttachedToSomething;
var bool bIsPopulationSystemAwareOfPickup;
var bool bCanBeSavedAcrossLevelTransition;
var transient bool bForceRBToSleep;
var repnotify bool bIsMissionItem;
var bool bIsMissionDirector;
var bool bHasPickupParticleOffset;
var transient bool bCostsToPickUp;
var GlobalsDefinition.EDropLifeSpanType LifeSpanType;
var transient Engine.WillowInventoryDefinition.ECurrencyType CostsToPickUpType;
var float VeryShortLivedDropLifeSpan;
var float ShortLivedDropLifeSpan;
var float LongLivedDropLifeSpan;
var float PickupShrinkDuration;
var float MaxRBAwakeTime;
var transient int ImpactEffectPlayCount;
var transient float LastImpactEffectTime;
var transient int MaxImpactEffectPlayCount;
var transient float ImpactEffectDelay;
var transient AkRtpc ImpactVelocityAkRtpc;
var export editinline transient ParticleSystemComponent MissionDirectorParticle;
var int InventoryRarityLevel;
var const float AlwaysRelevantDistanceSquared;
var() export editinline DynamicLightEnvironmentComponent DynamicLightEnvironment;
var transient InteractionIconDefinition InteractionIconOverride;
var transient int CostsToPickUpAmount;
var transient Actor PickedUpByActor;

replication
{
    // Pos:0x000
     if(int(Role) == int(ROLE_Authority))
        CostsToPickUpAmount, CostsToPickUpType, 
        InteractionIconOverride, PickupParticles, 
        RBState, bCostsToPickUp, 
        bPickupAtRest, bPickupable;

    // Pos:0x011
     if(bNetInitial)
        InventoryRarityLevel, bIsMissionItem;
}

simulated function PostBeginPlay()
{
    super(Actor).PostBeginPlay();
    class'WillowGlobals'.static.GetWillowGlobals().AddPickup(self);
    // End:0xBF
    foreach LocalPlayerControllers(class'PlayerController', UnknownLocal_1)
    {
        // End:0xBE
        if(WillowHUD(UnknownLocal_1.myHUD) != none)
        {
            WillowHUD(UnknownLocal_1.myHUD).AddPostRenderedActor(self);
        }        
    }    
    //return;    
}

simulated event Destroyed()
{
    UnknownLocal_1 = WillowItem(Inventory);
    // End:0x3F
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.PickupDisassociated(self);
    }
    class'WillowGlobals'.static.GetWillowGlobals().RemovePickup(self);
    super.Destroyed();
    // End:0xFE
    foreach LocalPlayerControllers(class'PlayerController', UnknownLocal_3)
    {
        // End:0xFD
        if(WillowHUD(UnknownLocal_3.myHUD) != none)
        {
            WillowHUD(UnknownLocal_3.myHUD).RemovePostRenderedActor(self);
        }        
    }    
    UnknownLocal_5 = class'GearboxGlobals'.static.GetGearboxGlobals().GetPopulationMaster();
    // End:0x163
    if(UnknownLocal_5 != none)
    {
        UnknownLocal_5.RemoveSpawnedActor(self, false);
    }
    //return;    
}

simulated event ReplicatedEvent(name VarName)
{
    super.ReplicatedEvent(VarName);
    // End:0x37
    if(VarName == 'PickupParticles')
    {
        SpawnPickupParticles();        
    }
    else
    {
        // End:0x5B
        if(VarName == 'bPickupAtRest')
        {
            WaitingForDefinitionForRegisterMissionDirector();            
        }
        else
        {
            // End:0x7F
            if(VarName == 'bPickupable')
            {
                WaitingForDefinitionForRegisterMissionDirector();                
            }
            else
            {
                // End:0xAD
                if(VarName == 'Inventory')
                {
                    InventoryAssociated();
                    SetMissionMaterialParameter();                    
                }
                else
                {
                    // End:0xD1
                    if(VarName == 'bIsMissionItem')
                    {
                        SetMissionMaterialParameter();                        
                    }
                    else
                    {
                        // End:0xFF
                        if(VarName == 'bUseRBPhysics')
                        {
                            // End:0xFF
                            if(bUseRBPhysics)
                            {
                                InitializePickupForRBPhysics();
                            }
                        }
                    }
                }
            }
        }
    }
    //return;    
}

simulated function WaitingForDefinitionForRegisterMissionDirector()
{
    // End:0x4D
    if((Inventory != none) && Inventory.GetInventoryDefinition() != none)
    {
        RegisterMissionDirector();
        SetMissionMaterialParameter();        
    }
    else
    {
        SetTimer(0.1, false, 'WaitingForDefinitionForRegisterMissionDirector');
    }
    //return;    
}

function InitializeFromInventory(WillowInventory InInv, Pawn InInstigator, bool bEnablePickup)
{
    local editinline MissionObjectiveWaypointComponent Waypoint;

    InventoryRarityLevel = InInv.RarityLevel;
    Inventory = InInv;
    Instigator = InInstigator;
    Manufacturer = Inventory.GetManufacturer();
    UnknownLocal_1 = MissionItemDefinition(Inventory.GetInventoryDefinition());
    // End:0x3AB
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_3 = UnknownLocal_1.MissionDirective;
        UnknownLocal_5 = UnknownLocal_1.AssociatedMissionObjective;
        bIsMissionDirector = UnknownLocal_3 != none;
        bIsMissionItem = bIsMissionDirector || UnknownLocal_5 != none;
        UnknownLocal_7 = WillowGameReplicationInfo(WorldInfo.GRI).MissionTracker;
        // End:0x267
        if(bIsMissionDirector)
        {
            UnknownLocal_7.RegisterMissionObserver(IMission(self), UnknownLocal_3);
            // End:0x222
            if(!UnknownLocal_7.MissionDependenciesMet(UnknownLocal_3))
            {
                bEnablePickup = false;
                // End:0x21E
                foreach UnknownLocal_3.Dependencies(UnknownLocal_9,)
                {
                    UnknownLocal_7.RegisterMissionObserver(IMission(self), UnknownLocal_9);                    
                }                                
            }
            else
            {
                bEnablePickup = bEnablePickup && int(UnknownLocal_7.GetMissionStatus(UnknownLocal_3)) == int(0);
            }            
        }
        else
        {
            // End:0x3AB
            if(bIsMissionItem)
            {
                UnknownLocal_7.RegisterMissionObserver(IMission(self), UnknownLocal_5.Outer);
                bEnablePickup = bEnablePickup && UnknownLocal_7.IsMissionObjectiveActive(UnknownLocal_5);
                // End:0x3AB
                if(UnknownLocal_1.bMissionWaypoint)
                {
                    Waypoint = new (self) class'MissionObjectiveWaypointComponent';
                    Waypoint.WaypointInfo.LinkedObjective = UnknownLocal_5;
                    AttachComponent(Waypoint);
                    UnknownLocal_7.RegisterWaypoint(Waypoint, UnknownLocal_5.Outer);
                }
            }
        }
    }
    InitializeDropLifespan();
    InventoryAssociated();
    SetPickupability(bEnablePickup);
    //return;    
}

function SetPickupStatusFromMissionTracker(MissionTracker Tracker)
{
    UnknownLocal_1 = MissionItemDefinition(Inventory.GetInventoryDefinition());
    UnknownLocal_3 = UnknownLocal_1.AssociatedMissionObjective;
    // End:0x86
    if(UnknownLocal_3 != none)
    {
        UnknownLocal_5 = Tracker.IsMissionObjectiveActive(UnknownLocal_3);        
    }
    else
    {
        UnknownLocal_7 = UnknownLocal_1.MissionDirective;
        UnknownLocal_5 = (int(Tracker.GetMissionStatus(UnknownLocal_7)) == int(0)) && Tracker.MissionDependenciesMet(UnknownLocal_7);
    }
    // End:0x124
    if(bPickupable != UnknownLocal_5)
    {
        SetPickupability(UnknownLocal_5);
    }
    //return;    
}

function CheckRemoveWaypoint(MissionDefinition Mission, IMission.EMissionStatus NewStatus)
{
    local editinline MissionObjectiveWaypointComponent Waypoint;

    // End:0x91
    if((int(NewStatus) == int(5)) || (int(NewStatus) == int(4)) && Mission.bRepeatable)
    {
        // End:0x90
        foreach ComponentList(class'MissionObjectiveWaypointComponent', Waypoint)
        {
            Waypoint.RemoveWaypoint();
            // End:0x90
            break;            
        }        
    }
    //return;    
}

event MissionReactionLevelLoad(MissionTracker Tracker, MissionDefinition Mission)
{
    SetPickupStatusFromMissionTracker(Tracker);
    //return;    
}

event MissionReactionStatusChanged(MissionTracker Tracker, MissionDefinition Mission, IMission.EMissionStatus NewStatus)
{
    CheckRemoveWaypoint(Mission, NewStatus);
    SetPickupStatusFromMissionTracker(Tracker);
    //return;    
}

event MissionReactionObjectiveSetChanged(MissionTracker Tracker, MissionObjectiveSetDefinition NewSet, MissionObjectiveSetDefinition PreviousSet)
{
    SetPickupStatusFromMissionTracker(Tracker);
    //return;    
}

event MissionReactionObjectiveUpdated(MissionTracker Tracker, MissionObjectiveDefinition UpdatedObjective)
{
    //return;    
}

event MissionReactionObjectiveCleared(MissionTracker Tracker, MissionObjectiveDefinition ClearedObjective)
{
    // End:0x5E
    if(ClearedObjective == MissionItemDefinition(Inventory.GetInventoryDefinition()).AssociatedMissionObjective)
    {
        SetPickupStatusFromMissionTracker(Tracker);
    }
    //return;    
}

event MissionReactionObjectiveComplete(MissionTracker Tracker, MissionObjectiveDefinition CompletedObjective)
{
    // End:0x63
    if(CompletedObjective == MissionItemDefinition(Inventory.GetInventoryDefinition()).AssociatedMissionObjective)
    {
        // End:0x63
        if(bPickupable)
        {
            SetPickupability(false);
        }
    }
    //return;    
}

simulated function bool DenyPickupAttempt(PlayerController PC)
{
    UnknownLocal_1 = Inventory.GetInventoryDefinition();
    UnknownLocal_3 = MissionItemDefinition(UnknownLocal_1);
    UnknownLocal_5 = (UnknownLocal_3 != none) && UnknownLocal_3.MissionDirective != none;
    // End:0x13B
    if(UnknownLocal_5)
    {
        // End:0xE4
        if(UnknownLocal_3.DirectiveMovieDefinition == none)
        {
            UnknownLocal_7 = class'WillowGlobals'.static.GetWillowGlobals().GetGlobalsDefinition().MissionAcceptDefinition;            
        }
        else
        {
            UnknownLocal_7 = UnknownLocal_3.DirectiveMovieDefinition;
        }
        WillowPlayerController(PC).ClientGFxPlayMovie(UnknownLocal_7, self, 'None');
    }
    return UnknownLocal_5;
    //return ReturnValue;    
}

simulated function RegisterMissionDirector()
{
    local editinline SocketComponent MissionDirectorSocket;
    local editinline MeshComponent Mesh;
    local Vector IconOffset;

    // End:0x3D
    if(Inventory != none)
    {
        UnknownLocal_1 = MissionItemDefinition(Inventory.GetInventoryDefinition());
    }
    // End:0x316
    if((UnknownLocal_1 != none) && UnknownLocal_1.MissionDirective != none)
    {
        UnknownLocal_3 = WillowGameReplicationInfo(WorldInfo.GRI).MissionTracker;
        // End:0x303
        if((UnknownLocal_3 != none) && UnknownLocal_3.IsDataValid())
        {
            // End:0x300
            if(((bPickupable && bPickupAtRest) && int(UnknownLocal_3.GetMissionStatus(UnknownLocal_1.MissionDirective)) == int(0)) && UnknownLocal_3.MissionDependenciesMet(UnknownLocal_1.MissionDirective))
            {
                Mesh = MeshComponent(CollisionComponent);
                UnknownLocal_5 = class'WillowGlobals'.static.GetWillowGlobals().GetGlobalsDefinition();
                IconOffset.Z = Mesh.Bounds.SphereRadius + UnknownLocal_5.PickupDirectorIconOffset;
                IconOffset = IconOffset << Rotation;
                MissionDirectorSocket = new (self) class'SocketComponent';
                MissionDirectorSocket.SocketName = UnknownLocal_5.MissionDirectorParticleSocket;
                MissionDirectorSocket.SetTranslation(IconOffset);
                AttachComponent(MissionDirectorSocket);
                UnknownLocal_3.super(WillowPickup).RegisterMissionDirector(IMissionDirector(self));
            }            
        }
        else
        {
            SetTimer(0.1, false, 'RegisterMissionDirector');
        }
    }
    //return;    
}

simulated event AddMissionDirective(const out MissionDirectorData NewDirective, optional bool bRegisterDirector = true);

simulated function int GetRedeemableMissions(out array<MissionDefinition> RedeemableMissions)
{
    //return ReturnValue;    
}

simulated function int GetInProgressMissions(out array<MissionDefinition> InProgressMissions)
{
    //return ReturnValue;    
}

simulated function int GetEligibleMissions(out array<MissionDefinition> EligibleMissions)
{
    UnknownLocal_1 = 0;
    UnknownLocal_3 = MissionItemDefinition(Inventory.GetInventoryDefinition());
    // End:0x44
    if(!UnknownLocal_3 != none)
    {
        return 0;
    }
    UnknownLocal_5 = UnknownLocal_3.MissionDirective;
    // End:0x73
    if(!UnknownLocal_5 != none)
    {
        return 0;
    }
    UnknownLocal_7 = WillowGameReplicationInfo(WorldInfo.GRI).MissionTracker;
    // End:0xF1
    if(UnknownLocal_7.CanStartMission(UnknownLocal_5))
    {
        EligibleMissions.AddItem(UnknownLocal_5;
        ++ UnknownLocal_1;
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

function OnPlayerAcceptedMission(WillowPlayerController PlayerAccepting, MissionDefinition MissionAccepted)
{
    PlayerAccepting.ServerPickupSpecific(IPickupable(self));
    //return;    
}

function OnPlayerTurnedInMission(WillowPlayerController PlayerTurningIn, MissionDefinition MissionTurnedIn)
{
    //return;    
}

event MissionStatusChanged()
{
    //return;    
}

simulated event SetMissionDirectorParticle()
{
    // End:0x3B
    if(WorldInfo.GetALocalPlayerController() == none)
    {
        SetTimer(0.1, false, 'SetMissionDirectorParticle');        
    }
    else
    {
        class'MissionTracker'.static.StaticSetMissionDirectorParticle(self, MissionDirectorParticle);
    }
    //return;    
}

simulated event DeactivateMissionDirectorParticle()
{
    // End:0x30
    if(MissionDirectorParticle != none)
    {
        MissionDirectorParticle.SetActive(false);
    }
    //return;    
}

function InitializeDropLifespan()
{
    // End:0x1C
    if(bIsMissionItem)
    {
        LifeSpanType = 3;        
    }
    else
    {
        LifeSpanType = class'WillowGlobals'.static.GetWillowGlobals().GetGlobalsDefinition().GetDropLifeSpanType(InventoryRarityLevel);
    }
    // End:0x104
    if(!bIsMissionItem && Inventory.GetInventoryDefinition().PickupLifeSpan > float(0))
    {
        UnknownLocal_1 = Inventory.GetInventoryDefinition().PickupLifeSpan;        
    }
    else
    {
        switch(LifeSpanType)
        {
            // End:0x12E
            case 0:
                UnknownLocal_1 = VeryShortLivedDropLifeSpan;
                // End:0x177
                break;
            // End:0x145
            case 1:
                UnknownLocal_1 = ShortLivedDropLifeSpan;
                // End:0x177
                break;
            // End:0x15C
            case 2:
                UnknownLocal_1 = LongLivedDropLifeSpan;
                // End:0x177
                break;
            // End:0x161
            case 4:
            // End:0x174
            case 3:
                UnknownLocal_1 = 0;
                // End:0x177
                break;
            // End:0xFFFF
            default:
                break;
        }
    }
    LifeSpan = UnknownLocal_1;
    // End:0x1BB
    if(LifeSpan > 0)
    {
        SetTimer(LifeSpan - PickupShrinkDuration, false, 'ShrinkPickupBeforeDestruction');
    }
    //return;    
}

function ShrinkPickupBeforeDestruction()
{
    UnknownLocal_1 = 0.1 * (1 / PickupShrinkDuration);
    UnknownLocal_3 = DrawScale - UnknownLocal_1;
    UnknownLocal_3 = FMax(UnknownLocal_3, 0);
    SetDrawScale(UnknownLocal_3);
    SetTimer(0.1, false, 'ShrinkPickupBeforeDestruction');
    //return;    
}

function bool ShouldSaveInPopulationSystem()
{
    // End:0x4F
    if((Inventory != none) && bCanBeSavedAcrossLevelTransition)
    {
        // End:0x4F
        if((int(LifeSpanType) == int(2)) || int(LifeSpanType) == int(3))
        {
            UnknownLocal_1 = true;
        }
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

// Export UWillowPickup::execCanBeGrabbedByTheAI(FFrame&, void* const)
native final function bool CanBeGrabbedByTheAI();

// Export UWillowPickup::execInitializeRBPhysics(FFrame&, void* const)
native function InitializeRBPhysics();

simulated function UpdateTouchRadiusForAutomaticallyPickedUpInventory()
{
    local editinline CylinderComponent TouchCylinder;

    // End:0x108
    if(((IsPickupableInventoryAutomaticallyPickedUp()) || bIsMissionItem && !bIsMissionDirector) && CollisionComponent != none)
    {
        TouchCylinder = CylinderComponent(CollisionComponent);
        UnknownLocal_1 = class'WillowGlobals'.static.GetWillowGlobals().GetGlobalsDefinition();
        // End:0x108
        if((TouchCylinder != none) && UnknownLocal_1 != none)
        {
            TouchCylinder.SetCylinderSize(UnknownLocal_1.PlayerInteractionDistance, TouchCylinder.CollisionHeight);
        }
    }
    //return;    
}

simulated function InventoryAssociated()
{
    local editinline MeshComponent Mesh;

    UpdateTouchRadiusForAutomaticallyPickedUpInventory();
    // End:0x5C
    if((CollisionComponent != none) && CollisionComponent.IsA('MeshComponent'))
    {
        DetachComponent(CollisionComponent);
        CollisionComponent = none;
    }
    Inventory.AttachMeshToPickup(self);
    Mesh = MeshComponent(CollisionComponent);
    Mesh.SetLightEnvironment(DynamicLightEnvironment);
    InitializePickupForRBPhysics();
    Inventory.PickupAssociated(self);
    //return;    
}

// Export UWillowPickup::execInitializePickupForRBPhysics(FFrame&, void* const)
native final simulated function InitializePickupForRBPhysics();

function EnableRagdollCollision()
{
    local editinline MeshComponent Mesh;

    Mesh = MeshComponent(CollisionComponent);
    // End:0x6F
    if(Mesh != none)
    {
        Mesh.SetRBCollidesWithChannel(24, true);
        Mesh.SetRBCollidesWithChannel(16, true);
    }
    //return;    
}

simulated event RigidBodyCollision(PrimitiveComponent HitComponent, PrimitiveComponent OtherComponent, const out CollisionImpactData RigidCollisionData, int ContactIndex)
{
    local ImpactResponseParameters ImpactResponseParams;

    UnknownLocal_1 = WillowImpactDefinition(Inventory.GetDroppedImpactDefinition());
    // End:0x21D
    if((UnknownLocal_1 != none) && (WorldInfo.TimeSeconds - LastImpactEffectTime) >= ImpactEffectDelay)
    {
        // End:0x1DD
        if(ImpactEffectPlayCount < MaxImpactEffectPlayCount)
        {
            ImpactResponseParams = class'WillowPhysicalMaterialProperty'.default.DefaultResponseParameters;
            // End:0x157
            if(ImpactVelocityAkRtpc != none)
            {
                ImpactResponseParams.RtpcParameterValues.Add(1;
                ImpactResponseParams.RtpcParameterValues[0].AkRtpc = ImpactVelocityAkRtpc;
                ImpactResponseParams.RtpcParameterValues[0].Value = VSize(Velocity);
            }
            LastImpactEffectTime = WorldInfo.TimeSeconds;
            ++ ImpactEffectPlayCount;
            class'WillowPhysicalMaterialProperty'.static.StaticRigidBodyImpact(UnknownLocal_1, self, HitComponent, OtherComponent, RigidCollisionData, ContactIndex, ImpactResponseParams);
        }
        // End:0x21D
        if(ImpactEffectPlayCount >= MaxImpactEffectPlayCount)
        {
            MeshComponent(CollisionComponent).SetNotifyRigidBodyCollision(false);
        }
    }
    //return;    
}

// Export UWillowPickup::execStartRigidBodyTimers(FFrame&, void* const)
native simulated function StartRigidBodyTimers();

simulated function MaxRBAwakeTimer()
{
    bForceRBToSleep = true;
    //return;    
}

simulated function CheckForRigidBodySleepState()
{
    local editinline MeshComponent Mesh;

    UnknownLocal_1 = bForceRBToSleep;
    // End:0x74
    if(!UnknownLocal_1)
    {
        Mesh = MeshComponent(CollisionComponent);
        // End:0x74
        if((Mesh != none) && Mesh.RigidBodyIsAwake() == false)
        {
            UnknownLocal_1 = true;
        }
    }
    // End:0xA4
    if(UnknownLocal_1)
    {
        ClearTimer('CheckForRigidBodySleepState');
        ConvertRigidBodyToFixed();
        PickupAtRest();
    }
    //return;    
}

event Landed(Vector HitNormal, Actor FloorActor)
{
    PickupAtRest();
    //return;    
}

function PickupAtRest()
{
    bPickupAtRest = true;
    bForceNetUpdate = true;
    bNetDirty = true;
    NetUpdateFrequency = 3;
    // End:0xC5
    if(!bIsPopulationSystemAwareOfPickup)
    {
        UnknownLocal_1 = class'GearboxGlobals'.static.GetGearboxGlobals().GetPopulationMaster();
        // End:0xAD
        if(UnknownLocal_1 != none)
        {
            UnknownLocal_1.AddExternalActor(self, class'PopulationFactoryWillowInventory');
        }
        bIsPopulationSystemAwareOfPickup = true;
        bKillDuringLevelTransition = false;
    }
    RegisterMissionDirector();
    //return;    
}

function TryToSetInteractParticles(bool bTurnParticlesOn)
{
    // End:0xAB
    if(!bIsMissionDirector)
    {
        // End:0x91
        if(bTurnParticlesOn)
        {
            // End:0x8E
            if((PickupParticles == none) && bPickupable)
            {
                SetInteractParticles(class'WillowGlobals'.static.GetWillowGlobals().GetGlobalsDefinition().PartPickup);
            }            
        }
        else
        {
            // End:0xAB
            if(PickupParticles != none)
            {
                SetInteractParticles(none);
            }
        }
    }
    //return;    
}

function SetInteractParticles(ParticleSystem PSys)
{
    PickupParticles = PSys;
    bNetDirty = true;
    SpawnPickupParticles();
    //return;    
}

// Export UWillowPickup::execGetPickupParticleOffset(FFrame&, void* const)
native final function Vector GetPickupParticleOffset();

// Export UWillowPickup::execSpawnPickupParticles(FFrame&, void* const)
native simulated function SpawnPickupParticles();

// Export UWillowPickup::execDestroyPickupParticles(FFrame&, void* const)
native simulated function DestroyPickupParticles();

function Behavior_ChangeUsability(Engine.ITargetable.EChangeStatus ChangeType, ActorComponent UsedComponent, IUsable.EUsabilityType UsedType)
{
    // End:0x18
    if(!int(UsedType) == int(0))
    {
        return;
    }
    switch(ChangeType)
    {
        // End:0x49
        case 0:
            SetPickupability(!bPickupable);
            // End:0x72
            break;
        // End:0x5C
        case 1:
            SetPickupability(true);
            // End:0x72
            break;
        // End:0x6F
        case 2:
            SetPickupability(false);
            // End:0x72
            break;
        // End:0xFFFF
        default:
            break;
    }
    //return;    
}

function Behavior_ChangeUsabilityCost(Engine.ITargetable.EChangeStatus ChangeType, Engine.WillowInventoryDefinition.ECurrencyType CostType, int CostAmount, IUsable.EUsabilityType UsedType)
{
    // End:0x18
    if(!int(UsedType) == int(0))
    {
        return;
    }
    switch(ChangeType)
    {
        // End:0x45
        case 0:
            UnknownLocal_1 = !bCostsToPickUp;
            // End:0x66
            break;
        // End:0x54
        case 1:
            UnknownLocal_1 = true;
            // End:0x66
            break;
        // End:0x63
        case 2:
            UnknownLocal_1 = false;
            // End:0x66
            break;
        // End:0xFFFF
        default:
            break;
    }
    // End:0x8A
    if(UnknownLocal_1 != bCostsToPickUp)
    {
        bCostsToPickUp = UnknownLocal_1;
    }
    // End:0xB8
    if(int(CostType) != int(CostsToPickUpType))
    {
        CostsToPickUpType = CostType;
    }
    // End:0xE2
    if(CostAmount != CostsToPickUpAmount)
    {
        CostsToPickUpAmount = CostAmount;
    }
    //return;    
}

function SetPickupability(bool bNewPickupability)
{
    bPickupable = bNewPickupability;
    RegisterMissionDirector();
    SetMissionMaterialParameter();
    TryToSetInteractParticles(bPickupable);
    //return;    
}

simulated function SetMissionMaterialParameter()
{
    local LinearColor GlowColor;
    local editinline MeshComponent Mesh;
    local name GlowColorName;

    // End:0x189
    if(bIsMissionItem)
    {
        Mesh = MeshComponent(CollisionComponent);
        // End:0x189
        if(Mesh != none)
        {
            UnknownLocal_1 = 0;
            GlowColorName = class'WillowGlobals'.static.GetWillowGlobals().GetGlobalsDefinition().MissionGlowColorParameter;
            Mesh.Behavior_GetColorParameterValue(UnknownLocal_1, GlowColorName, GlowColor);
            // End:0x131
            if(bPickupable)
            {
                GlowColor.A = 1;
                Mesh.Behavior_SetColorParameterValue(UnknownLocal_1, GlowColorName, GlowColor);                
            }
            else
            {
                GlowColor.A = 0;
                Mesh.Behavior_SetColorParameterValue(UnknownLocal_1, GlowColorName, GlowColor);
            }
        }
    }
    //return;    
}

simulated function Behavior_Destroy()
{
    Destroy();
    //return;    
}

// Export UWillowPickup::execGetSaveRotation(FFrame&, void* const)
native function Rotator GetSaveRotation();

// Export UWillowPickup::execSetSaveRotation(FFrame&, void* const)
native function SetSaveRotation(Rotator NewRotation);

// Export UWillowPickup::execPickupable_IsEnabled(FFrame&, void* const)
native function bool Pickupable_IsEnabled();

simulated function PickupableMeshActor GetPickupableMeshActor()
{
    UnknownLocal_1 = Spawn(class'PickupableMeshActor', self,, Location, GetSaveRotation());
    Inventory.AttachMeshToPickup(UnknownLocal_1);
    return UnknownLocal_1;
    //return ReturnValue;    
}

function AttachPickupToWorldBody(IWorldBody AttachmentBase, name AttachmentPointName)
{
    // End:0x56
    if(NotEqual_InterfaceInterface(AttachmentBase, IWorldBody(none)))
    {
        AttachmentBase.WorldBodyAttachActor(self,,, AttachmentPointName);
        AdjustPickupPhysicsAndCollisionForBeingAttached();
    }
    //return;    
}

function AdjustPickupPhysicsAndCollisionForBeingAttached()
{
    bIsPickupAttachedToSomething = true;
    SetPhysics(0);
    SetCollision(false, false);
    bCollideWorld = false;
    PickupAtRest();
    //return;    
}

function AdjustPickupPhysicsAndCollisionForBeingDropped()
{
    SetPhysics(2);
    SetCollision(true, false);
    bCollideWorld = true;
    bUseRBPhysics = true;
    //return;    
}

function PickupMemento GetMemento()
{
    local PickupMemento Memento;

    Memento.Rotation = GetSaveRotation();
    Memento.bIsAttachedToSomething = bIsPickupAttachedToSomething;
    return Memento;
    //return ReturnValue;    
}

simulated function FailedPickup()
{
    local Vector RandomImpulse, RandomTorque;
    local editinline MeshComponent Mesh;

    // End:0x1A9
    if(!bIsPickupAttachedToSomething)
    {
        ConvertFixedToRigidBody();
        Mesh = MeshComponent(CollisionComponent);
        // End:0x1A9
        if(Mesh != none)
        {
            RandomImpulse.X = -5 + (FRand() * float(10));
            RandomImpulse.Y = -5 + (FRand() * float(10));
            RandomImpulse.Z = 20;
            RandomTorque.X = -2 + (FRand() * float(4));
            RandomTorque.Y = -2 + (FRand() * float(4));
            RandomTorque.Z = -2 + (FRand() * float(4));
            // End:0x1A9
            if(__NFUN_228__(Velocity) < float(1))
            {
                Mesh.AddImpulse(RandomImpulse);
                Mesh.AddTorque(RandomTorque);
            }
        }
    }
    //return;    
}

simulated event ConvertRigidBodyToFixed()
{
    local editinline MeshComponent Mesh;
    local editinline SkeletalMeshComponent SKMesh;

    Mesh = MeshComponent(CollisionComponent);
    // End:0x16D
    if(Mesh != none)
    {
        Mesh.SetNotifyRigidBodyCollision(false);
        Mesh.SetBlockRigidBody(false);
        Mesh.SetActorCollision(false, false);
        SKMesh = SkeletalMeshComponent(Mesh);
        // End:0x137
        if((SKMesh != none) && SKMesh.PhysicsAssetInstance != none)
        {
            SKMesh.PhysicsAssetInstance.SetAllBodiesFixed(true);
            SKMesh.bUpdateKinematicBonesFromAnimation = false;            
        }
        else
        {
            Mesh.GetRootBodyInstance().SetFixed(true);
        }
    }
    //return;    
}

simulated event ConvertFixedToRigidBody()
{
    local editinline MeshComponent Mesh;
    local editinline SkeletalMeshComponent SKMesh;

    NetUpdateFrequency = 8;
    Mesh = MeshComponent(CollisionComponent);
    // End:0x17B
    if(Mesh != none)
    {
        Mesh.SetNotifyRigidBodyCollision(true);
        Mesh.SetBlockRigidBody(true);
        Mesh.SetActorCollision(true, false);
        SKMesh = SkeletalMeshComponent(Mesh);
        // End:0x125
        if((SKMesh != none) && SKMesh.PhysicsAssetInstance != none)
        {
            SKMesh.PhysicsAssetInstance.SetAllBodiesFixed(false);            
        }
        else
        {
            Mesh.GetRootBodyInstance().SetFixed(false);
        }
        Mesh.WakeRigidBody();
    }
    StartRigidBodyTimers();
    //return;    
}

static function WillowPickup CreatePickupFromMemento(PickupMemento Memento, WillowInventory InventoryThisPickupIsFor)
{
    // End:0x112
    if(InventoryThisPickupIsFor != none)
    {
        UnknownLocal_1 = WillowPickup(InventoryThisPickupIsFor.GetPickup(Memento.bIsAttachedToSomething, true));
        // End:0x112
        if(UnknownLocal_1 != none)
        {
            UnknownLocal_1.bIsPopulationSystemAwareOfPickup = true;
            UnknownLocal_1.bKillDuringLevelTransition = false;
            // End:0xDB
            if(Memento.bIsAttachedToSomething)
            {
                UnknownLocal_1.AdjustPickupPhysicsAndCollisionForBeingAttached();
            }
            UnknownLocal_1.SetSaveRotation(Memento.Rotation);
        }
    }
    return UnknownLocal_1;
    //return ReturnValue;    
}

function GiveTo(Pawn P, bool bReady)
{
    local editinline WaypointComponent Waypoint;

    UnknownLocal_1 = WillowVendingMachineBase(Base);
    // End:0x3F
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.NotifyBasedPickupRemoved(self);
    }
    UnknownLocal_3 = WillowItem(Inventory);
    // End:0x7E
    if(UnknownLocal_3 != none)
    {
        UnknownLocal_3.PickupDisassociated(self);
    }
    // End:0xC0
    foreach ComponentList(class'WaypointComponent', Waypoint)
    {
        Waypoint.RemoveWaypoint();
        // End:0xC0
        break;        
    }    
    super.GiveTo(P, bReady);
    //return;    
}

function PickedUpBy(Pawn P)
{
    PickedUpByActor = P;
    super.PickedUpBy(P);
    //return;    
}

event BeginShrinking()
{
    LifeSpan = PickupShrinkDuration;
    ClearTimer('ShrinkPickupBeforeDestruction');
    ShrinkPickupBeforeDestruction();
    //return;    
}

simulated function BeginFocus(Pawn User)
{
    local Vector POVLocation;
    local Rotator POVRotation;

    UnknownLocal_1 = WillowPlayerController(User.Controller);
    // End:0x3C
    if(!UnknownLocal_1 != none)
    {
        return;
    }
    // End:0x71
    if(!EqualEqual_InterfaceInterface(UnknownLocal_1.FocusObject, IFocusable(none)))
    {
        return;
    }
    UnknownLocal_1.GetPlayerViewPoint(POVLocation, POVRotation);
    UnknownLocal_1.FocusObject = IFocusable(self);
    UnknownLocal_1.FocusCamRot = POVRotation;
    UnknownLocal_1.FocusCamLoc = POVLocation;
    UnknownLocal_1.FocusFOVAngle = -1;
    //return;    
}

simulated function EndFocus(Pawn User)
{
    UnknownLocal_1 = WillowPlayerController(User.Controller);
    // End:0x3C
    if(!UnknownLocal_1 != none)
    {
        return;
    }
    // End:0x71
    if(!EqualEqual_InterfaceInterface(UnknownLocal_1.FocusObject, IFocusable(self)))
    {
        return;
    }
    UnknownLocal_1.FocusObject = none;
    UnknownLocal_1.FocusCamReturnTime = WorldInfo.TimeSeconds;
    //return;    
}

// Export UWillowPickup::execGetFocusLocation(FFrame&, void* const)
native function Vector GetFocusLocation();

// Export UWillowPickup::execGetFocusRadius(FFrame&, void* const)
native function float GetFocusRadius();

// Export UWillowPickup::execGetFocusScreenOffset(FFrame&, void* const)
native function Vector GetFocusScreenOffset();

// Export UWillowPickup::execGetAllDirectorData(FFrame&, void* const)
native function int GetAllDirectorData(out array<MissionDirectorData> OutData);

// Export UWillowPickup::execGetMissionDirectorLocation(FFrame&, void* const)
native function Vector GetMissionDirectorLocation();

// Export UWillowPickup::execHasAnyMissionsForPlayer(FFrame&, void* const)
native function bool HasAnyMissionsForPlayer();

simulated function bool CanSplash()
{
    return true;
    //return ReturnValue;    
}

// Export UWillowPickup::execSetInteractionIcon(FFrame&, void* const)
native function SetInteractionIcon(EngineInteractionIconDefinition Icon);

function OnPlayerOpenedMissionUI(WillowPlayerController ThePlayer)
{
    //return;    
}

function OnPlayerClosedMissionUI(WillowPlayerController ThePlayer)
{
    //return;    
}

auto state Pickup
{
    ignores BeginState, EndState;

    simulated function PostRenderFor(PlayerController PC, Canvas Canvas, Vector CameraPosition, Vector CameraDir)
    {
        // End:0x4B
        if(bPickupable)
        {
            WillowHUD(PC.myHUD).DrawDebugFeedbackForPickup(self);
        }
        //return;        
    }
    stop;    
}

defaultproperties
{
    bPickupable=true
    bCanBeSavedAcrossLevelTransition=true
    VeryShortLivedDropLifeSpan=60
    ShortLivedDropLifeSpan=600
    LongLivedDropLifeSpan=1800
    PickupShrinkDuration=15
    MaxRBAwakeTime=15
    AlwaysRelevantDistanceSquared=6.4E+07
    begin object name=MyLightEnvironment class=DynamicLightEnvironmentComponent
        MinTimeBetweenFullUpdates=0.2
        ShadowInterpolationSpeed=0.05
        bCastShadows=false
        bAffectedBySmallDynamicLights=false
        bSynthesizeSHLight=false
    object end
    // Reference: DynamicLightEnvironmentComponent'Default__WillowPickup.MyLightEnvironment'
    DynamicLightEnvironment=MyLightEnvironment
    bUseRBPhysics=true
    Components(0)=none
    Components(1)=CylinderComponent'Default__WillowPickup.CollisionCylinder'
    begin object name=MyLightEnvironment class=DynamicLightEnvironmentComponent
        MinTimeBetweenFullUpdates=0.2
        ShadowInterpolationSpeed=0.05
        bCastShadows=false
        bAffectedBySmallDynamicLights=false
        bSynthesizeSHLight=false
    object end
    // Reference: DynamicLightEnvironmentComponent'Default__WillowPickup.MyLightEnvironment'
    Components(2)=MyLightEnvironment
    bOnlyDirtyReplication=false
    bKillDuringLevelTransition=true
    LifeSpan=0
    CollisionComponent=CylinderComponent'Default__WillowPickup.CollisionCylinder'
}