/*******************************************************************************
 * WillowSeqEvent_CustomEvent generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowSeqEvent_CustomEvent extends SequenceEvent
    native(Sequence)
    forcescriptorder(true)
    hidecategories(Mobile,Object);

var(Event) name EventName;

defaultproperties
{
    bPlayerOnly=false
    ObjName="CustomEvent"
}