/*******************************************************************************
 * WillowShield generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowShield extends WillowEquipAbleItem
    native
    hidecategories(Mobile,Navigation,MovementReplication);

simulated event ReplicatedEvent(name VarName)
{
    // End:0x24
    if(VarName == 'bPrimed')
    {
        ShieldPrimedStateChanged();        
    }
    else
    {
        super(WillowItem).ReplicatedEvent(VarName);
    }
    //return;    
}

simulated function bool ClientInitializeFromItemDefinition()
{
    UnknownLocal_1 = super.ClientInitializeFromItemDefinition();
    ShieldDef = ShieldDefinition(DefinitionData.ItemDefinition);
    return UnknownLocal_1;
    //return ReturnValue;    
}

function ItemEquipped()
{
    super.ItemEquipped();
    UnknownLocal_1 = WillowPlayerPawn(Owner);
    // End:0x49
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.ResetShieldPrimeCachedValues(self);
    }
    //return;    
}

function ItemUnequipped(bool bReplace)
{
    super.ItemUnequipped(bReplace);
    bPrimed = false;
    //return;    
}

// Export UWillowShield::execTryAbsorbingAmmo(FFrame&, void* const)
native function bool TryAbsorbingAmmo(Object DamageSource, WillowDamageTypeDefinition DamageType, out float PercentDamageToAbsorb);

simulated event ShieldPrimedStateChanged()
{
    UnknownLocal_1 = WillowPlayerPawn(Owner);
    // End:0x3F
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.ResetShieldPrimeCachedValues(self);
    }
    // End:0x8C
    if(bPrimed)
    {
        // End:0x8C
        if(ShieldDef != none)
        {
            ShieldDef.OnShieldPrimed(ConsumerHandle, Owner);
        }
    }
    bNetDirty = true;
    //return;    
}

function ShieldTriggered()
{
    ShieldDef.OnEffectTriggered(ConsumerHandle, Owner);
    //return;    
}

event SetDamageResistanceType(WillowDamageTypeDefinition NewType)
{
    // End:0x51
    if(DamageResistanceType != NewType)
    {
        ShieldDef.OnDamageResistanceTypeChanged(ConsumerHandle, Owner, NewType);
    }
    DamageResistanceType = NewType;
    //return;    
}

simulated event WillowDeclarations.EEquipmentLoc GetEquipmentLocation()
{
    return 0;
    //return ReturnValue;    
}

function name GetEquippedStat()
{
    return 'STAT_PLAYER_SHIELD_EQUIPPED';
    //return ReturnValue;    
}

protected function bool ValidateDefinitions()
{
    // End:0x3A
    if(!DefinitionData.ItemDefinition.IsA('ShieldDefinition'))
    {
        return false;
    }
    // End:0x98
    if(!(DefinitionData.AlphaItemPartDefinition == none) || DefinitionData.AlphaItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    // End:0xF6
    if(!(DefinitionData.BetaItemPartDefinition == none) || DefinitionData.BetaItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    // End:0x154
    if(!(DefinitionData.GammaItemPartDefinition == none) || DefinitionData.GammaItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    // End:0x1B2
    if(!(DefinitionData.DeltaItemPartDefinition == none) || DefinitionData.DeltaItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    // End:0x210
    if(!(DefinitionData.EpsilonItemPartDefinition == none) || DefinitionData.EpsilonItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    // End:0x26E
    if(!(DefinitionData.ZetaItemPartDefinition == none) || DefinitionData.ZetaItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    // End:0x2CC
    if(!(DefinitionData.EtaItemPartDefinition == none) || DefinitionData.EtaItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    // End:0x32A
    if(!(DefinitionData.ThetaItemPartDefinition == none) || DefinitionData.ThetaItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    // End:0x388
    if(!(DefinitionData.MaterialItemPartDefinition == none) || DefinitionData.MaterialItemPartDefinition.IsA('ShieldPartDefinition'))
    {
        return false;
    }
    return true;
    //return ReturnValue;    
}

// Export UWillowShield::execCanCompareUIStat(FFrame&, void* const)
native simulated function bool CanCompareUIStat(out AttributeDefinition Attrib, out AttributeDefinition CompareAttrib, out WillowInventory CompareItem);

// Export UWillowShield::execIsSameShieldTypeAs(FFrame&, void* const)
native simulated function bool IsSameShieldTypeAs(out WillowShield CompareShield);

// Export UWillowShield::execGetAttributePresentationOverride(FFrame&, void* const)
native simulated function AttributePresentationListDefinition GetAttributePresentationOverride(AttributeDefinition Attribute);

// Export UWillowShield::execGetItemCardTopSectionString(FFrame&, void* const)
native simulated function GetItemCardTopSectionString(out string Section);

// Export UWillowShield::execGetHolsteredGearLikenessType(FFrame&, void* const)
native simulated function byte GetHolsteredGearLikenessType();
