/*******************************************************************************
 * WillowServerSideProjectile generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowServerSideProjectile extends WillowProjectile
    native
    config(Game)
    hidecategories(Mobile,Navigation,MovementReplication);

var Vector ServerLocation;
var Vector ServerVelocity;
var Vector ServerAcceleration;

replication
{
    // Pos:0x000
     if(bNetDirty && int(Role) == int(ROLE_Authority))
        ServerLocation, ServerVelocity;

    // Pos:0x020
     if(((Definition.SmoothHomingReplication || Definition.bReplicateMovement) && bNetDirty) && int(Role) == int(ROLE_Authority))
        ServerAcceleration;
}

defaultproperties
{
    LightEnvironment=DynamicLightEnvironmentComponent'Default__WillowServerSideProjectile.MyLightEnvironment'
    Components(0)=DynamicLightEnvironmentComponent'Default__WillowServerSideProjectile.MyLightEnvironment'
    bNetTemporary=false
}