/*******************************************************************************
 * WillowSeqAct_DayNightCycle generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowSeqAct_DayNightCycle extends SeqAct_Interp
    native(Sequence)
    config(Engine)
    forcescriptorder(true)
    hidecategories(Mobile,Object);

// Export UWillowSeqAct_DayNightCycle::execSetTimeOfDay(FFrame&, void* const)
native static function SetTimeOfDay(float NewTimeOfDay);

// Export UWillowSeqAct_DayNightCycle::execTogglePauseDayCycle(FFrame&, void* const)
native static function bool TogglePauseDayCycle();

defaultproperties
{
    bLooping=true
    bForceStartPos=true
    ObjName="Day/Night Cycle Matinee"
    ObjCategory="Day/Night Cycle"
}