/*******************************************************************************
 * WillowWaypoint generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowWaypoint extends WillowTrigger
    native
    hidecategories(Mobile,Navigation,MovementReplication)
    implements(IMission);

var private native const noexport Pointer VfTable_IIMission;
var() MissionObjectiveWaypointData WaypointInfo;
var() const int AreaRadius;
var() const bool bUpdateObjectiveOnPlayerTouch;
var bool bEnabled;
var() array<Volume> TouchVolumes;

simulated function PostBeginPlay()
{
    local editinline MissionObjectiveWaypointComponent Waypoint;

    super.PostBeginPlay();
    // End:0x2B2
    if((int(Role) == int(ROLE_Authority)) && bEnabled)
    {
        UnknownLocal_1 = WaypointInfo.LinkedObjective;
        // End:0x5E
        if(!UnknownLocal_1 != none)
        {
            return;
        }
        UnknownLocal_3 = 0;
        J0x65:

        // End:0xF4 [Loop If]
        if(UnknownLocal_3 < WaypointInfo.ObjectiveSetRestrictions.Length)
        {
            UnknownLocal_5 = WaypointInfo.ObjectiveSetRestrictions[UnknownLocal_3];
            // End:0xC3
            if(!UnknownLocal_5 != none)
            {
                return;
            }
            // End:0xEA
            if(!UnknownLocal_5.ContainsObjective(UnknownLocal_1))
            {
                return;
            }
            ++ UnknownLocal_3;
            // [Loop Continue]
            goto J0x65;
        }
        UnknownLocal_7 = WillowGameReplicationInfo(WorldInfo.GRI).MissionTracker;
        // End:0x2B2
        if(int(UnknownLocal_7.GetMissionStatus(UnknownLocal_1.Outer)) != int(4))
        {
            Waypoint = new (self) class'MissionObjectiveWaypointComponent';
            Waypoint.WaypointInfo = WaypointInfo;
            Waypoint.WaypointRadius = AreaRadius;
            AttachComponent(Waypoint);
            WillowGameReplicationInfo(WorldInfo.GRI).MissionTracker.RegisterWaypoint(Waypoint, UnknownLocal_1.Outer);
            // End:0x2B2
            if(bUpdateObjectiveOnPlayerTouch)
            {
                UnknownLocal_7.RegisterMissionObserver(IMission(self), UnknownLocal_1.Outer);
            }
        }
    }
    // End:0x31C
    if(TouchVolumes.Length > 0)
    {
        // End:0x2F2
        foreach TouchVolumes(UnknownLocal_9,)
        {
            UnknownLocal_9.AssociateActor(self);            
        }        
        CylinderComponent.SetCylinderSize(0, 0);
    }
    //return;    
}

event Touch(Actor Other, PrimitiveComponent OtherComp, Vector HitLocation, Vector HitNormal)
{
    // End:0x60
    if((bUpdateObjectiveOnPlayerTouch && Other.IsA('Pawn')) && Other.IsPlayerOwned())
    {
        ProcessPlayerTouch();
    }
    super(Trigger).Touch(Other, OtherComp, HitLocation, HitNormal);
    //return;    
}

function ProcessPlayerTouch()
{
    UnknownLocal_1 = WillowGameReplicationInfo(WorldInfo.GRI).MissionTracker;
    // End:0x145
    if(UnknownLocal_1.IsMissionObjectiveActive(WaypointInfo.LinkedObjective))
    {
        // End:0xFE
        if(WaypointInfo.ObjectiveSetRestrictions.Length > 0)
        {
            UnknownLocal_3 = false;
            // End:0xFA
            foreach WaypointInfo.ObjectiveSetRestrictions(UnknownLocal_5,)
            {
                // End:0xF9
                if(UnknownLocal_1.IsObjectiveSetActive(UnknownLocal_5))
                {
                    UnknownLocal_3 = true;                    
                }
                else
                {                    
                }
            }                        
        }
        else
        {
            UnknownLocal_3 = true;
        }
        // End:0x145
        if(UnknownLocal_3)
        {
            UnknownLocal_1.UpdateObjective(WaypointInfo.LinkedObjective);
        }
    }
    //return;    
}

function ClearWaypoint()
{
    local editinline WaypointComponent Waypoint;

    // End:0x42
    foreach ComponentList(class'WaypointComponent', Waypoint)
    {
        Waypoint.RemoveWaypoint();
        // End:0x42
        break;        
    }    
    bEnabled = false;
    //return;    
}

event MissionReactionStatusChanged(MissionTracker Tracker, MissionDefinition Mission, IMission.EMissionStatus NewStatus)
{
    //return;    
}

event MissionReactionLevelLoad(MissionTracker Tracker, MissionDefinition Mission)
{
    //return;    
}

event MissionReactionObjectiveSetChanged(MissionTracker Tracker, MissionObjectiveSetDefinition NewSet, MissionObjectiveSetDefinition PreviousSet)
{
    // End:0x3C
    foreach Touching(UnknownLocal_1,)
    {
        // End:0x3B
        if(UnknownLocal_1.IsPlayerOwned())
        {
            ProcessPlayerTouch();
        }        
    }    
    //return;    
}

event MissionReactionObjectiveUpdated(MissionTracker Tracker, MissionObjectiveDefinition UpdatedObjective)
{
    //return;    
}

event MissionReactionObjectiveCleared(MissionTracker Tracker, MissionObjectiveDefinition ClearedObjective)
{
    //return;    
}

event MissionReactionObjectiveComplete(MissionTracker Tracker, MissionObjectiveDefinition CompletedObjective)
{
    //return;    
}

defaultproperties
{
    bEnabled=true
    TriggerSprite=none
    begin object name=CollisionCylinder class=CylinderComponent
        CollisionHeight=0
        CollisionRadius=0
    object end
    // Reference: CylinderComponent'Default__WillowWaypoint.CollisionCylinder'
    CylinderComponent=CollisionCylinder
    Components(0)=none
    begin object name=CollisionCylinder class=CylinderComponent
        CollisionHeight=0
        CollisionRadius=0
    object end
    // Reference: CylinderComponent'Default__WillowWaypoint.CollisionCylinder'
    Components(1)=CollisionCylinder
    Components(2)=none
    begin object name=CollisionCylinder class=CylinderComponent
        CollisionHeight=0
        CollisionRadius=0
    object end
    // Reference: CylinderComponent'Default__WillowWaypoint.CollisionCylinder'
    CollisionComponent=CollisionCylinder
}