/*******************************************************************************
 * WillowWeaponPawn generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowWeaponPawn extends WillowVehicleBase
    native
    nativereplication
    config(Game)
    hidecategories(Mobile,Navigation,MovementReplication);

var repnotify WillowVehicleWeapon MyVehicleWeapon;
var repnotify WillowVehicle MyVehicle;
var repnotify int MySeatIndex;
var private bool DriverIsAttached;
var private bool SeatIndexReceived;
var private transient bool bInDriverLeave;
var private transient float FixViewTime;

replication
{
    // Pos:0x000
     if(int(Role) == int(ROLE_Authority))
        MySeatIndex, MyVehicle, 
        MyVehicleWeapon;
}

simulated event ReplicatedEvent(name VarName)
{
    // End:0x168
    if(((VarName == 'MyVehicle') || VarName == 'MyVehicleWeapon') || VarName == 'MySeatIndex')
    {
        // End:0x142
        if(((MySeatIndex > 0) && MyVehicle != none) && MySeatIndex < MyVehicle.Seats.Length)
        {
            MyVehicle.Seats[MySeatIndex].SeatPawn = self;
            MyVehicle.Seats[MySeatIndex].Gun = MyVehicleWeapon;
            MyVehicle.SetupSeatPawnViewLimits(MySeatIndex);
        }
        // End:0x165
        if(VarName == 'MySeatIndex')
        {
            SeatIndexReceived = true;
        }        
    }
    else
    {
        super(Vehicle).ReplicatedEvent(VarName);
    }
    //return;    
}

// Export UWillowWeaponPawn::execGetDriverController(FFrame&, void* const)
native simulated function Controller GetDriverController();

// Export UWillowWeaponPawn::execIsAttachedRiderSeat(FFrame&, void* const)
native simulated function bool IsAttachedRiderSeat();

function SetVehicleData(WillowVehicle InMyVehicle, WillowVehicleWeapon InVehicleWeapon, int InSeatIndex)
{
    MyVehicle = InMyVehicle;
    MyVehicleWeapon = InVehicleWeapon;
    MySeatIndex = InSeatIndex;
    SeatIndexReceived = true;
    //return;    
}

// Export UWillowWeaponPawn::execCalcCamera(FFrame&, void* const)
native simulated function bool CalcCamera(float fDeltaTime, out Vector out_CamLoc, out Rotator out_CamRot, out float out_FOV);

// Export UWillowWeaponPawn::execGetWeaponFacingDir(FFrame&, void* const)
native simulated function GetWeaponFacingDir(out Vector OutFacingDir);

simulated function IncrementFlashCount(Weapon Who, byte FireModeNum)
{
    // End:0x11
    if(MyVehicle == none)
    {
        return;
    }
    MyVehicle.IncrementFlashCount(Who, FireModeNum);
    //return;    
}

simulated function ClearFlashCount(Weapon Who)
{
    // End:0x11
    if(MyVehicle == none)
    {
        return;
    }
    MyVehicle.ClearFlashCount(Who);
    //return;    
}

// Export UWillowWeaponPawn::execSetFlashLocation(FFrame&, void* const)
native function SetFlashLocation(Weapon Who, byte FireModeNum, Vector NewLoc);

simulated function ClearFlashLocation(Weapon Who)
{
    // End:0x11
    if(MyVehicle == none)
    {
        return;
    }
    MyVehicle.ClearFlashLocation(Who);
    //return;    
}

function PossessedBy(Controller C, bool bVehicleTransition)
{
    super(Vehicle).PossessedBy(C, bVehicleTransition);
    // End:0x4D
    if(MyVehicleWeapon != none)
    {
        MyVehicleWeapon.ClientWeaponSet(false);
    }
    SetBaseEyeheight();
    EyeHeight = BaseEyeHeight;
    //return;    
}

function bool DriverEnter(Pawn P, optional bool SkipAnim = false)
{
    ExitAnimationInUse
    none
    UnknownLocal_1 = WillowPawn(P);
    // End:0x4E
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.RemoveAllStatusEffects();
    }
    // End:0x99
    if(P.IsA('WillowPlayerPawn'))
    {
        WillowPlayerPawn(P).OutOfDuelBounds();
    }
    // End:0x133
    if((P.Controller != none) && P.Controller.bIsHumanPlayer)
    {
        WillowPlayerController(P.Controller).EnsureWeaponsUp();
    }
    UnknownLocal_3 = MyVehicle.GetSeatDefinition(MySeatIndex);
    // End:0x18D
    if(UnknownLocal_3 != none)
    {
        UnknownLocal_5 = UnknownLocal_3.IsAttachedRiderSeat;
    }
    UnknownLocal_7 = P.Controller;
    Driver = P;
    Driver.StartDriving(self, SkipAnim);
    // End:0x21F
    if(!Driver.IsAliveAndWell())
    {
        Driver = none;
        return false;
    }
    SetDriving(true);
    // End:0x39B
    if(!UnknownLocal_5 || !SkipAnim)
    {
        UnknownLocal_7.UnPossess();
        Driver.SetOwner(self);
        // End:0x2BE
        if(UnknownLocal_7.IsA('WillowPlayerController'))
        {
            WillowPlayerController(UnknownLocal_7).bSuspendHUDReInitOnPossession = true;
        }
        UnknownLocal_7.Possess(self, true);
        // End:0x320
        if(UnknownLocal_7.IsA('WillowPlayerController'))
        {
            WillowPlayerController(UnknownLocal_7).bSuspendHUDReInitOnPossession = false;
        }
        // End:0x39B
        if((PlayerController(UnknownLocal_7) != none) && !UnknownLocal_7.IsChildState(UnknownLocal_7.GetStateName(), LandMovementState))
        {
            PlayerController(UnknownLocal_7).GotoState(LandMovementState);
        }
    }
    WorldInfo.Game.DriverEnteredVehicle(self, P);
    return true;
    //return ReturnValue;    
}

simulated function DriverLeft()
{
    super(Vehicle).DriverLeft();
    MyVehicle.PassengerLeave(MySeatIndex);
    //return;    
}

function ServerPossessAttachedRiderOnEntry(Controller C)
{
    local name SeatAnchor;

    UnknownLocal_1 = WillowPawn(Driver);
    // End:0x36
    if((UnknownLocal_1 == none) || C == none)
    {
        return;
    }
    // End:0x238
    if(int(Role) == int(ROLE_Authority))
    {
        MyVehicle.bSuspendBaseRestrictions = true;
        DoAttachedRiderSetup(C);
        UnknownLocal_1.SetPhysics(0);
        Driver = UnknownLocal_1;
        UnknownLocal_1.DrivenVehicle = self;
        MyVehicle.Seats[MySeatIndex].StoragePawn = UnknownLocal_1;
        UnknownLocal_1.SetWeaponVisibility(true);
        UnknownLocal_3 = MyVehicle.GetSeatDefinition(MySeatIndex);
        SeatAnchor = ((UnknownLocal_3 != none) ? UnknownLocal_3.SeatAnchor : 'None');
        MyVehicle.WorldBodyAttachActor(UnknownLocal_1, -UnknownLocal_1.Mesh.Translation,, SeatAnchor);
        UnknownLocal_1.SetCollision(true, false);
        UnknownLocal_1.bCollideWorld = false;
        MyVehicle.bSuspendBaseRestrictions = false;
    }
    //return;    
}

simulated function ClientPossessAttachedRiderOnEntry(Pawn RiderPawn)
{
    UnknownLocal_1 = RiderPawn.Controller;
    // End:0x3F
    if(UnknownLocal_1 == none)
    {
        UnknownLocal_1 = GetDriverController();
    }
    // End:0xED
    if((RiderPawn != none) && UnknownLocal_1 != none)
    {
        ServerPossessAttachedRiderOnEntry(UnknownLocal_1);
        // End:0xED
        if(UnknownLocal_1.IsA('WillowPlayerController'))
        {
            UnknownLocal_3 = WillowPlayerController(UnknownLocal_1);
            UnknownLocal_3.GotoState('PlayerDriving');
            UnknownLocal_3.GetHUDMovie().InitCachedValues();
        }
    }
    Controller = none;
    //return;    
}

function PossessWeaponPawnForAttachedRiderExit()
{
    // End:0x15E
    if(Driver != none)
    {
        Controller = none;
        // End:0x91
        if(Driver.Controller.IsA('WillowPlayerController'))
        {
            WillowPlayerController(Driver.Controller).bSuspendHUDReInitOnPossession = true;
        }
        Driver.Controller.Possess(self, true);
        // End:0x13E
        if(Driver.Controller.IsA('WillowPlayerController'))
        {
            WillowPlayerController(Driver.Controller).bSuspendHUDReInitOnPossession = false;
        }
        Driver.DrivenVehicle = self;
    }
    //return;    
}

event bool DriverLeave(bool bForceLeave, optional bool SkipPawnPlacement)
{
    local Vector FinalRand;
    local Rotator RotYaw;

    bInDriverLeave
    return false;
    goto J0x28;
    bInDriverLeave = bForceLeave;
    J0x28:

    // End:0x56
    if(!bForceLeave && !DriverAllowedToLeave())
    {
        bInDriverLeave = false;
        return false;
    }
    UnknownLocal_1 = MyVehicle.GetSeatDefinition(MySeatIndex);
    UnknownLocal_3 = ((UnknownLocal_1 != none) ? UnknownLocal_1.IsAttachedRiderSeat : false);
    // End:0xF9
    if(UnknownLocal_3)
    {
        UnknownLocal_5 = WillowPawn(Driver);
        // End:0xF9
        if(UnknownLocal_5 != none)
        {
            UnknownLocal_5.ClientStopWeaponFiring();
        }
    }
    // End:0x157
    if((UnknownLocal_3 && !bForceLeave) && Driver.Controller.Pawn != self)
    {
        PossessWeaponPawnForAttachedRiderExit();
    }
    StopFireTurret();
    // End:0x21B
    if(MyVehicleWeapon != none)
    {
        MyVehicleWeapon.Instigator = ((MyVehicle.Driver != none) ? MyVehicle : none);
        MyVehicleWeapon.CrosshairOwner = MyVehicleWeapon.Instigator;
        MyVehicleWeapon.RefreshCrosshairForPlayer();
    }
    // End:0x2C7
    if(!bForceLeave)
    {
        UnknownLocal_5 = WillowPawn(Driver);
        // End:0x2C7
        if(UnknownLocal_5 != none)
        {
            MyVehicle.UnsitDriver(UnknownLocal_5, self, MySeatIndex);
            WorldInfo.Game.DriverLeftVehicle(self, Driver);
            bInDriverLeave = false;
            return false;
        }
    }
    UnknownLocal_7 = Driver;
    UnknownLocal_9 = super.DriverLeave(bForceLeave, SkipPawnPlacement);
    UnknownLocal_5 = WillowPawn(UnknownLocal_7);
    // End:0x574
    if(UnknownLocal_5 != none)
    {
        // End:0x399
        if(MyVehicle.Seats[MySeatIndex].bDontStopAnimOnExit)
        {
            MyVehicle.Seats[MySeatIndex].bDontStopAnimOnExit = false;            
        }
        else
        {
            UnknownLocal_5.SMComponent.StopAny();
        }
        UnknownLocal_11 = WillowVehicle(Base);
        // End:0x50B
        if(((UnknownLocal_11 != none) && !UnknownLocal_11.IsAliveAndWell()) && UnknownLocal_11.VehicleDef != none)
        {
            FinalRand = UnknownLocal_11.VehicleDef.GetEjectionVelocity(MySeatIndex);
            RotYaw.Yaw = UnknownLocal_11.Rotation.Yaw;
            UnknownLocal_5.Velocity = UnknownLocal_11.Velocity + (FinalRand >> RotYaw);
        }
        UnknownLocal_13 = WillowPlayerController(UnknownLocal_5.Controller);
        // End:0x574
        if(UnknownLocal_13 != none)
        {
            UnknownLocal_13.SetFOV(UnknownLocal_13.DefaultFOV);
        }
    }
    WorldInfo.Game.DriverLeftVehicle(self, UnknownLocal_7);
    bInDriverLeave = false;
    return UnknownLocal_9;
    //return ReturnValue;    
}

function DoAttachedRiderSetup(Controller C)
{
    UnknownLocal_1 = Driver;
    bLookingBack = false;
    SetDriving(false);
    C.UnPossess();
    Controller = none;
    Driver.SetOwner(C);
    // End:0xBE
    if(C.IsA('WillowPlayerController'))
    {
        WillowPlayerController(C).bSuspendHUDReInitOnPossession = true;
    }
    C.Possess(Driver, true);
    // End:0x134
    if(C.IsA('WillowPlayerController'))
    {
        WillowPlayerController(C).bSuspendHUDReInitOnPossession = false;
    }
    Driver.StopDriving(self);
    Driver = none;
    UnknownLocal_3 = WillowPawn(UnknownLocal_1);
    // End:0x219
    if(UnknownLocal_3 != none)
    {
        UnknownLocal_3.SMComponent.StopAny();
        UnknownLocal_5 = WillowPlayerController(UnknownLocal_3.Controller);
        // End:0x219
        if(UnknownLocal_5 != none)
        {
            UnknownLocal_5.SetFOV(UnknownLocal_5.DefaultFOV);
        }
    }
    //return;    
}

function bool IsOccupantAllowedToTakeDamage(WillowPawn Occupant, optional int OccupantSeatNdx = -1)
{
    MyVehicle != none;
    return MyVehicle.IsOccupantAllowedToTakeDamage(Occupant, MySeatIndex);
    return true;
    //return ReturnValue;    
}

simulated function SwitchSeats()
{
    UnknownLocal_1 = GetDriverController();
    UnknownLocal_3 = WillowPlayerController(UnknownLocal_1);
    // End:0x51
    if((UnknownLocal_3 != none) && UnknownLocal_3.TrySeatSwapClient())
    {
        return;
    }
    // End:0x128
    if(MyVehicle != none)
    {
        // End:0x128
        if(!MyVehicle.bDisableSeatSwap)
        {
            UnknownLocal_5 = MyVehicle.GetSeatIndexForController(UnknownLocal_1);
            UnknownLocal_7 = MyVehicle.GetAdjacentSeatIndex(1, UnknownLocal_1);
            // End:0x128
            if(UnknownLocal_7 != UnknownLocal_5)
            {
                UnknownLocal_3.RouteCallToServerChangeSeat(MyVehicle.GetAdjacentSeatIndex(1, UnknownLocal_1));
            }
        }
    }
    //return;    
}

reliable server function ServerChangeSeat(int RequestedSeat)
{
    local array<WillowPlayerController> Players;

    UnknownLocal_1 = GetDriverController();
    // End:0x3C1
    if((((MyVehicle != none) && WorldInfo.TimeSeconds >= MyVehicle.Seats[MySeatIndex].SeatLockTime) && WorldInfo.TimeSeconds >= MyVehicle.Seats[RequestedSeat].SeatLockTime) && !WillowGameInfo(WorldInfo.Game).TravelCountdownInProcess())
    {
        // End:0x265
        if((((WillowPlayerController(UnknownLocal_1) == none) || MyVehicle.Seats[RequestedSeat].SeatPawn == none) || MyVehicle.Seats[RequestedSeat].SeatPawn.GetDriverController() == none) || WillowPlayerController(MyVehicle.Seats[RequestedSeat].SeatPawn.GetDriverController()) == none)
        {
            MyVehicle.ChangeSeat(UnknownLocal_1, RequestedSeat);            
        }
        else
        {
            UnknownLocal_3 = WillowGameInfo(WorldInfo.Game).GetPlayerInteractionManager();
            Players.AddItem(WillowPlayerController(UnknownLocal_1);
            Players.AddItem(WillowPlayerController(MyVehicle.Seats[RequestedSeat].SeatPawn.GetDriverController());
            UnknownLocal_5 = new (UnknownLocal_3) class'VehicleSeatSwap_PlayerInteractionServer';
            UnknownLocal_5.PlayerVehicle = MyVehicle;
            UnknownLocal_5.RequestedSeat = RequestedSeat;
            UnknownLocal_3.StartInteraction(UnknownLocal_5, Players, WillowPlayerController(UnknownLocal_1));
        }
    }
    //return;    
}

function DropToGround()
{
    return;
    //return;    
}

function AddVelocity(Vector NewVelocity, Vector HitLocation, class<DamageType> DamageType, DamageTypeDefinition DamageTypeDefinition, optional TraceHitInfo HitInfo)
{
    //return;    
}

function JumpOffPawn()
{
    return;
    //return;    
}

singular event BaseChange()
{
    return;
    //return;    
}

function SetMovementPhysics()
{
    return;
    //return;    
}

function bool DoJump(bool bUpdating)
{
    return false;
    //return ReturnValue;    
}

simulated function float GetCollisionRadius()
{
    // End:0x32
    if(MyVehicle != none)
    {
        return MyVehicle.GetCollisionRadius();        
    }
    else
    {
        return super(Pawn).GetCollisionRadius();
    }
    //return ReturnValue;    
}

simulated function Vector GetTargetLocation(optional Actor RequestedBy, optional bool bRequestAlternateLoc)
{
    MyVehicle != none;
    return MyVehicle.GetTargetLocation(RequestedBy, bRequestAlternateLoc);
    // End:0x73
    if(Mesh != none)
    {
        return Mesh.GetPosition();
    }
    return CylinderComponent.GetPosition();
    //return ReturnValue;    
}

simulated function SetBaseEyeheight()
{
    BaseEyeHeight = 0;
    //return;    
}

simulated function WaitingForReplicatedData()
{
    ClearTimer('WaitingForReplicatedData');
    // End:0x8D
    if((SeatIndexReceived && MyVehicle != none) && Driver != none)
    {
        // End:0x8A
        if(!DriverIsAttached && MyVehicle.bAttachDriver)
        {
            AttachDriver(Driver);
        }        
    }
    else
    {
        SetTimer(0.1, false, 'WaitingForReplicatedData');
    }
    //return;    
}

simulated function AttachDriver(Pawn P, optional bool SkipAnim = false)
{
    local ChassisDefinition.EVehicleSide Side;

    DriverIsAttached
    DetachDriver(Driver);
    // End:0x7F
    if((!SeatIndexReceived || MyVehicle == none) || Driver == none)
    {
        ClearTimer('WaitingForReplicatedData');
        SetTimer(0.1, false, 'WaitingForReplicatedData');
        return;
    }
    Side = MyVehicle.GetSide(P.Location, MySeatIndex);
    // End:0xF5
    if(!MyVehicle.bAttachDriver)
    {
        return;
    }
    UnknownLocal_1 = WillowPawn(P);
    // End:0x2A7
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_3 = MyVehicle.GetSeatDefinition(MySeatIndex);
        // End:0x193
        if(UnknownLocal_3 != none)
        {
            UnknownLocal_5 = UnknownLocal_3.IsAttachedRiderSeat;
            UnknownLocal_7 = UnknownLocal_3.ForceOccupantCrouch;
        }
        // End:0x1BE
        if(UnknownLocal_5)
        {
            // End:0x1BE
            if(UnknownLocal_7)
            {
                UnknownLocal_1.ForceCrouch();
            }
        }
        UnknownLocal_1.SetCollision(false, false);
        UnknownLocal_1.bCollideWorld = false;
        UnknownLocal_1.SetHardAttach(true);
        UnknownLocal_1.SetLocation(Location);
        UnknownLocal_1.SetPhysics(0);
        MyVehicle.SitDriver(UnknownLocal_1, MySeatIndex, Side, SkipAnim);
        // End:0x2A7
        if(UnknownLocal_5 && SkipAnim)
        {
            ClientPossessAttachedRiderOnEntry(UnknownLocal_1);
        }
    }
    MyVehicle.bSuspendBaseRestrictions = true;
    super.AttachDriver(P, SkipAnim);
    MyVehicle.bSuspendBaseRestrictions = false;
    DriverIsAttached = true;
    //return;    
}

simulated function DetachDriver(Pawn P)
{
    UnknownLocal_1 = WillowPawn(P);
    // End:0x44
    if(UnknownLocal_1 != none)
    {
        UnknownLocal_1.EnableHandIK(-1, false);
    }
    ClearTimer('ClientCheckForSitAnimFinished');
    DriverIsAttached = false;
    super(Vehicle).DetachDriver(P);
    //return;    
}

simulated function bool IndependentVehicle()
{
    return false;
    //return ReturnValue;    
}

simulated function Vector GetWeaponStartTraceLocation(optional Weapon CurrentWeapon)
{
    local Vector SocketLocation;

    SocketLocation
    MyVehicleWeapon.InstantFireStartTrace();
    return SocketLocation;
    //return ReturnValue;    
}

simulated function ClientCheckForSitAnimFinished()
{
    UnknownLocal_1 = WillowPawn(Driver);
    // End:0x18B
    if(((UnknownLocal_1 != none) && MyVehicle != none) && MySeatIndex > 0)
    {
        UnknownLocal_3 = MyVehicle.GetSeatDefinition(MySeatIndex);
        // End:0xBF
        if(UnknownLocal_3 != none)
        {
            UnknownLocal_5 = UnknownLocal_3.IsAttachedRiderSeat;
            UnknownLocal_7 = UnknownLocal_3.Anim_Idle;
        }
        // End:0x126
        if(((UnknownLocal_5 && UnknownLocal_1.DrivenVehicle == self) && Controller == none) && UnknownLocal_1.Controller != none)
        {
            UnknownLocal_9 = true;            
        }
        else
        {
            // End:0x165
            if(UnknownLocal_1.SMComponent.IsPlaying(UnknownLocal_7))
            {
                UnknownLocal_9 = true;
            }
        }
        // End:0x18B
        if(UnknownLocal_9)
        {
            ClearTimer('ClientCheckForSitAnimFinished');
            SitAnimFinished();
        }
    }
    //return;    
}

simulated function SitAnimFinished()
{
    UnknownLocal_1 = MyVehicle.GetSeatDefinition(MySeatIndex);
    UnknownLocal_3 = WillowPawn(Driver);
    // End:0x105
    if(UnknownLocal_3 != none)
    {
        // End:0xD8
        if(int(Role) == int(ROLE_Authority))
        {
            UnknownLocal_5 = ((UnknownLocal_1 != none) ? UnknownLocal_1.Anim_Idle : none);
            // End:0xD8
            if(UnknownLocal_5 != none)
            {
                UnknownLocal_3.SMComponent.Play(UnknownLocal_5);
            }
        }
        MyVehicle.SetupHandIKForPawn(UnknownLocal_3, MySeatIndex);
    }
    UnknownLocal_7 = ((UnknownLocal_1 != none) ? UnknownLocal_1.bHideOccupant : false);
    // End:0x18E
    if(UnknownLocal_7)
    {
        MyVehicle.Seats[MySeatIndex].StoragePawn.SetHidden(true);
    }
    UnknownLocal_9 = ((UnknownLocal_1 != none) ? UnknownLocal_1.IsAttachedRiderSeat : false);
    // End:0x1D4
    if(UnknownLocal_9)
    {
        ClientPossessAttachedRiderOnEntry(UnknownLocal_3);
    }
    // End:0x25F
    if(MyVehicleWeapon != none)
    {
        MyVehicleWeapon.Instigator = self;
        MyVehicleWeapon.CrosshairOwner = MyVehicleWeapon.Instigator;
        MyVehicleWeapon.RefreshCrosshairForPlayer();
    }
    //return;    
}

simulated event TakeDamage(float RawDamage, Controller InstigatedBy, Vector HitLocation, Vector Momentum, class<DamageType> DamageType, optional TraceHitInfo HitInfo, optional IDamageCauser DamageCauser, optional DamagePipeline Pipeline)
{
    MyVehicle != none;
    MyVehicle.TakeDamage(RawDamage, InstigatedBy, HitLocation, Momentum, DamageType, HitInfo, DamageCauser, Pipeline);
    //return;    
}

// Export UWillowWeaponPawn::execIsDead(FFrame&, void* const)
native simulated function bool IsDead();

// Export UWillowWeaponPawn::execGetAllBarInfo(FFrame&, void* const)
native simulated function GetAllBarInfo(out array<InfoBarData> BarData);

// Export UWillowWeaponPawn::execDisplayParentInfo(FFrame&, void* const)
native simulated function bool DisplayParentInfo();

// Export UWillowWeaponPawn::execGetExpInfo(FFrame&, void* const)
native simulated function GetExpInfo(out int ExpLevelValue);

simulated function VehicleAdjustInput(out float aTurn, out float aLookUp, out float aForward, out float aStrafe)
{
    UnknownLocal_1 = MyVehicle.GetSeatDefinition(MySeatIndex);
    UnknownLocal_3 = ((UnknownLocal_1 != none) ? UnknownLocal_1.CameraDef : none);
    // End:0xC2
    if((MyVehicle != none) && UnknownLocal_3 != none)
    {
        aTurn *= UnknownLocal_3.RotationRateYaw;
        aLookUp *= UnknownLocal_3.RotationRatePitch;
    }
    //return;    
}

simulated function ProcessViewRotation(float DeltaTime, out Rotator out_ViewRotation, out Rotator out_DeltaRot)
{
    local Rotator VehicleRotation;

    // End:0xC4
    if(MyVehicle != none)
    {
        UnknownLocal_1 = MyVehicle.GetSeatDefinition(MySeatIndex);
        VehicleRotation = MyVehicle.Rotation;
        UnknownLocal_3 = ((UnknownLocal_1 != none) ? UnknownLocal_1.CameraDef : none);
        UnknownLocal_5 = ((UnknownLocal_1 != none) ? UnknownLocal_1.CameraDef : none);        
    }
    else
    {
        VehicleRotation = Rotation;
    }
    // End:0x281
    if(true)
    {
        // End:0x112
        if(Controller != none)
        {
            FixViewTime = WorldInfo.TimeSeconds;
        }
        // End:0x1CE
        if((Controller == none) && (WorldInfo.TimeSeconds - FixViewTime) < 0.1)
        {
            // End:0x1CB
            if(UnknownLocal_5 != none)
            {
                // End:0x1CB
                if(int(UnknownLocal_5.CameraBehaviorOnEntry) == int(2))
                {
                    out_ViewRotation = MyVehicle.Rotation + UnknownLocal_5.ForcedCameraRotation;
                }
            }            
        }
        else
        {
            // End:0x20B
            if(Controller == none)
            {
                ProcessViewRotationForAttachedRiders(DeltaTime, out_ViewRotation);
                FixViewTime = -1;                
            }
            else
            {
                ProcessViewRotationInVehicle(UnknownLocal_3, VehicleRotation, DeltaTime, out_ViewRotation, out_DeltaRot);
            }
        }
        // End:0x27E
        if(out_ViewRotation.Roll != 0)
        {
            out_ViewRotation.Roll = 0;
        }        
    }
    else
    {
        ProcessViewRotationInVehicle(UnknownLocal_3, VehicleRotation, DeltaTime, out_ViewRotation, out_DeltaRot);
    }
    //return;    
}

// Export UWillowWeaponPawn::execProcessViewRotationForAttachedRiders(FFrame&, void* const)
native final function ProcessViewRotationForAttachedRiders(float DeltaTime, out Rotator out_ViewRotation);

function Pawn GetPawnToTeleport()
{
    // End:0xE6
    if(MyVehicle.Driver == none)
    {
        UnknownLocal_1 = 1;
        J0x2B:

        // End:0xE6 [Loop If]
        if(UnknownLocal_1 < MyVehicle.Seats.Length)
        {
            UnknownLocal_3 = MyVehicle.Seats[UnknownLocal_1].SeatPawn;
            // End:0xDC
            if(UnknownLocal_3 != none)
            {
                // End:0xB9
                if(UnknownLocal_3 == self)
                {
                    UnknownLocal_5 = MyVehicle;
                    // [Explicit Break]
                    goto J0xE6;
                }
                // End:0xDC
                if(UnknownLocal_3.Driver != none)
                {
                    // [Explicit Break]
                    goto J0xE6;
                }
            }
            ++ UnknownLocal_1;
            // [Loop Continue]
            goto J0x2B;
        }
    }
    J0xE6:

    return UnknownLocal_5;
    //return ReturnValue;    
}

exec function StartFireTurret()
{
    UnknownLocal_1 = WillowPlayerController(Controller);
    // End:0x62
    if((UnknownLocal_1 != none) && !UnknownLocal_1.IsInTransitionalVehicleState())
    {
        UnknownLocal_1.StartFire();
    }
    //return;    
}

exec function StopFireTurret()
{
    // End:0x41
    if(PlayerController(Controller) != none)
    {
        PlayerController(Controller).StopFire();
    }
    //return;    
}

reliable server function ServerNotifyTargetLockSuccessful(Actor NewLockOnTarget)
{
    // End:0x37
    if(MyVehicleWeapon != none)
    {
        MyVehicleWeapon.ServerNotifyTargetLockSuccessful(NewLockOnTarget);
    }
    //return;    
}

reliable server function ServerNotifyAltFireTriggered()
{
    // End:0x2E
    if(MyVehicleWeapon != none)
    {
        MyVehicleWeapon.ServerOnAltFireTriggered();
    }
    //return;    
}

// Export UWillowWeaponPawn::execGetVehicleAndSeatIndex(FFrame&, void* const)
native function bool GetVehicleAndSeatIndex(out WillowVehicle WVehicle, out int SeatIndex);

reliable client simulated function ClientUnsitDriver(WillowPawn WillowP, int SeatIndex)
{
    // End:0x46
    if(int(Role) < int(ROLE_Authority))
    {
        MyVehicle.UnsitDriver(WillowP, self, SeatIndex);
    }
    //return;    
}

simulated function WillowVehicle GetWillowVehicle()
{
    return MyVehicle;
    //return ReturnValue;    
}

simulated event FellOutOfWorld(class<DamageType> dmgType)
{
    //return;    
}

simulated event bool OutsideWorldBounds()
{
    return false;
    //return ReturnValue;    
}

// Export UWillowWeaponPawn::execSetAllegiance(FFrame&, void* const)
native function SetAllegiance(PawnAllegiance NewAllegiance);

// Export UWillowWeaponPawn::execGetPivotPoint(FFrame&, void* const)
native function Vector GetPivotPoint();

// Export UWillowWeaponPawn::execGetAimDirection(FFrame&, void* const)
native function Vector GetAimDirection();

defaultproperties
{
    StayUprightConstraintSetup=RB_StayUprightSetup'Default__WillowWeaponPawn.MyStayUprightSetup'
    StayUprightConstraintInstance=RB_ConstraintInstance'Default__WillowWeaponPawn.MyStayUprightConstraintInstance'
    bTurnInPlace=true
    bFollowLookDir=true
    bStationary=true
    BaseEyeHeight=180
    EyeHeight=180
    Mesh=SkeletalMeshComponent'Default__WillowWeaponPawn.SVehicleMesh'
    InventoryManagerClass='WillowInventoryManager'
    Components(0)=SkeletalMeshComponent'Default__WillowWeaponPawn.SVehicleMesh'
    Physics=EPhysics.PHYS_None
    CollisionType=ECollisionType.COLLIDE_CustomDefault
    bIgnoreBaseRotation=true
    BlockRigidBody=false
    bCollideActors=false
    bCollideWorld=false
    bProjTarget=false
    CollisionComponent=SkeletalMeshComponent'Default__WillowWeaponPawn.SVehicleMesh'
}