/*******************************************************************************
 * WillowSeqEvent_StartNewGameCinematics generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowSeqEvent_StartNewGameCinematics extends SequenceEvent
    forcescriptorder(true)
    hidecategories(Mobile,Object);

defaultproperties
{
    bPlayerOnly=false
    ObjName="Start New Game Cinematics"
    ObjCategory="Cinematic"
}