/*******************************************************************************
 * WillowAIComponent generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WillowAIComponent extends AIComponent
    native(AI)
    hidecategories(Mobile,Object);

enum TargetExposure
{
    Exposure_None,
    Exposure_Half,
    Exposure_Full,
    Exposure_MAX
};

enum EThreatLevel
{
    ETL_NoThreat,
    ETL_InThreatRadius,
    ETL_SeenInThreatRadius,
    ETL_Provoked,
    ETL_MAX
};

enum ECombatPointLOS
{
    CPLOS_Ignore,
    CPLOS_UseLOS,
    CPLOS_AvoidLOS,
    CPLOS_MAX
};

struct native CombatZone
{
    var int Index;
    var Box Bounds;

    structdefaultproperties
    {
        Index=0
        Bounds=(Min=(X=0,Y=0,Z=0),Max=(X=0,Y=0,Z=0),IsValid=0)
    }
};

struct native CoverExposureData
{
    var bool bExposedUp;
    var bool bExposedLeft;
    var bool bExposedRight;

    structdefaultproperties
    {
        bExposedUp=false
        bExposedLeft=false
        bExposedRight=false
    }
};

struct native CombatZoneSearchData
{
    var() const float ZoneMoveDist;
    var() const AIRange ZoneTimeLimit;
    var() const AIRange TargetRange;
    var() const float MinHeight;
    var() const bool bCanFail;
    var() const WillowAIComponent.ECombatPointLOS LineOfSight;
    var() const AIRange LineOfSightTimeLimit;

    structdefaultproperties
    {
        ZoneMoveDist=0
        ZoneTimeLimit=(MinVal=0,MaxVal=0)
        TargetRange=(MinVal=1000,MaxVal=2000)
        MinHeight=-1
        bCanFail=true
        LineOfSight=ECombatPointLOS.CPLOS_UseLOS
        LineOfSightTimeLimit=(MinVal=0,MaxVal=0)
    }
};

struct native CombatPointSearchData extends CombatZoneSearchData
{
    var() bool bUseCover;
    var() float PointRadius;

    structdefaultproperties
    {
        bUseCover=true
        PointRadius=256
    }
};

struct native CombatPointData
{
    var() editconst int Slot;
    var() editconst Vector Location;
    var() editconst ActorReference Actor;
    var() editconst GearboxFramework.PopulationPoint.EPopPointContraintType ConstraintType;
    var() editconst array<editconst PopulationSpawnedActorTagDefinition> ConstraintTags;
    var transient bool bClaimed;

    structdefaultproperties
    {
        Slot=0
        Location=(X=0,Y=0,Z=0)
        Actor=/*ERROR: System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at UELib.Core.UDefaultProperty.DeserializeTagUE3()
   at UELib.Core.UDefaultProperty.Deserialize()
   at UELib.Core.UDefaultProperty.DeserializeDefaultPropertyValue(PropertyType type, DeserializeFlags& deserializeFlags)
   at UELib.Core.UDefaultProperty.TryDeserializeDefaultPropertyValue(PropertyType type, DeserializeFlags& deserializeFlags)*/
        ConstraintType=EPopPointContraintType.POPOINTCONSTRAINT_None
        ConstraintTags=none
        bClaimed=false
    }
};

struct native CombatPointDebugData
{
    var bool bBest;
    var float Score;
    var Vector Location;

    structdefaultproperties
    {
        bBest=false
        Score=0
        Location=(X=0,Y=0,Z=0)
    }
};

var transient WillowMind MyWillowMind;
var transient PopulationOpportunityDen MyDen;
var export editinline transient WillowAIBlackboardComponent MyBlackboard;
var transient IAIInterface TargetLeader;
var transient IAIInterface FormationLeader;
var transient array<int> InvalidCombatZones;
var const transient array<int> ClaimedCombatZones;
var const transient float ZoneTime;
var const transient CombatZone LastZone;
var const transient CombatZone CurrentZone;
var const transient CombatZone ClaimedZone;
var transient Volume CombatVolume;
var transient bool bCombatVolumeOnlyLimitsRangedAttacks;
var transient bool bCanUseCover;
var transient CoverInfo DesiredCover;
var transient float LastHurtTime;
var transient float LastAttackedTime;
var transient Actor LastAttacker;
var protected transient array<AIHoldData> HeadLookHolds;
var protected transient array<AIHoldData> PhaseLockHolds;
var transient float LastTickTime;
var transient float TickThrottleTime;

// Export UWillowAIComponent::execClearState(FFrame&, void* const)
native function ClearState();

// Export UWillowAIComponent::execNotifyAttackedBy(FFrame&, void* const)
native function NotifyAttackedBy(Actor Attacker);

// Export UWillowAIComponent::execGetTargets(FFrame&, void* const)
protected native function GetTargets();

// Export UWillowAIComponent::execGetTargetsFromParents(FFrame&, void* const)
protected native function GetTargetsFromParents();

// Export UWillowAIComponent::execAddDenTargets(FFrame&, void* const)
native function AddDenTargets(PopulationOpportunityDen Den);

// Export UWillowAIComponent::execValidTarget(FFrame&, void* const)
native function bool ValidTarget(Actor Target);

// Export UWillowAIComponent::execValidCurrentTarget(FFrame&, void* const)
native function bool ValidCurrentTarget(MindTargetInfo TargetRec);

// Export UWillowAIComponent::execTargetRemoved(FFrame&, void* const)
native function TargetRemoved(MindTargetInfo TargetRec);

// Export UWillowAIComponent::execInitializeTargetRecord(FFrame&, void* const)
native function InitializeTargetRecord(MindTargetInfo TargetRec);

// Export UWillowAIComponent::execTargetChanged(FFrame&, void* const)
protected native function TargetChanged(Actor OldTarget, Actor NewTarget);

// Export UWillowAIComponent::execHold(FFrame&, void* const)
native function Hold(name HoldName, Object Tag);

// Export UWillowAIComponent::execRelease(FFrame&, void* const)
native function Release(name HoldName, Object Tag);

// Export UWillowAIComponent::execHasForcedTarget(FFrame&, void* const)
native function bool HasForcedTarget();

// Export UWillowAIComponent::execGetForcedTarget(FFrame&, void* const)
native final function Actor GetForcedTarget();

// Export UWillowAIComponent::execGetTargetLeader(FFrame&, void* const)
native final function IAIInterface GetTargetLeader();

// Export UWillowAIComponent::execSetTargetLeader(FFrame&, void* const)
native function SetTargetLeader(IAIInterface NewLeader, optional bool bOverride = false);

// Export UWillowAIComponent::execGetFormationLeader(FFrame&, void* const)
native final function IAIInterface GetFormationLeader();

// Export UWillowAIComponent::execSetFormationLeader(FFrame&, void* const)
native function SetFormationLeader(IAIInterface NewLeader, optional bool bOverride = false);

// Export UWillowAIComponent::execGetFormation(FFrame&, void* const)
native final function WillowFormationComponent GetFormation(WillowFormationComponent Current, name Tag, WillowPawn LeaderPawn);

function float DistToFormationLeader()
{
    local Vector MyLoc, LeaderLoc;
    local IAIInterface MyAI, LeaderAI;

    MyAI = IAIInterface(Owner);
    LeaderAI = GetFormationLeader();
    // End:0x78
    if(EqualEqual_InterfaceInterface(MyAI, IAIInterface(none)) || EqualEqual_InterfaceInterface(LeaderAI, IAIInterface(none)))
    {
        return -1;
    }
    MyLoc = MyAI.GetAILocation();
    LeaderLoc = LeaderAI.GetAILocation();
    return VSize(MyLoc - LeaderLoc);
    //return ReturnValue;    
}

// Export UWillowAIComponent::execClaimCombatZone(FFrame&, void* const)
native function ClaimCombatZone(const out CombatZone Zone);

// Export UWillowAIComponent::execUnclaimCombatZone(FFrame&, void* const)
native function UnclaimCombatZone(const out CombatZone Zone);

// Export UWillowAIComponent::execCombatZoneAvailable(FFrame&, void* const)
native function bool CombatZoneAvailable(const out CombatZone Zone);

// Export UWillowAIComponent::execGetCombatZoneByLocation(FFrame&, void* const)
native static function CombatZone GetCombatZoneByLocation(const out Vector TestLoc);

// Export UWillowAIComponent::execMarkCurrentCombatZone(FFrame&, void* const)
native final function MarkCurrentCombatZone();

// Export UWillowAIComponent::execInvalidateCombatZone(FFrame&, void* const)
native final function InvalidateCombatZone(optional int ZoneIndex = -1);

// Export UWillowAIComponent::execGetLocationScore(FFrame&, void* const)
native final function int GetLocationScore(const out Vector TestLoc, const out array<AttackLocation> Limits, bool bZoneCheck);

// Export UWillowAIComponent::execIsLocationValid(FFrame&, void* const)
native final function bool IsLocationValid(const out Vector TestLoc, const out array<AttackLocation> Limits, bool bZoneCheck, optional bool bAllowPartial);

// Export UWillowAIComponent::execTryExitCover(FFrame&, void* const)
native final function TryExitCover();

// Export UWillowAIComponent::execTryEnterCover(FFrame&, void* const)
native final function TryEnterCover();

// Export UWillowAIComponent::execGetCoverExposure(FFrame&, void* const)
native function CoverExposureData GetCoverExposure(const out CoverInfo Cover);

// Export UWillowAIComponent::execGetHighestThreatLevel(FFrame&, void* const)
native final function WillowAIComponent.EThreatLevel GetHighestThreatLevel();

// Export UWillowAIComponent::execGetThreatLevel(FFrame&, void* const)
native final function WillowAIComponent.EThreatLevel GetThreatLevel(Actor Target);

// Export UWillowAIComponent::execSetThreatLevel(FFrame&, void* const)
native function SetThreatLevel(Actor Target, WillowAIComponent.EThreatLevel NewThreat);

function float GetTimeSinceHurt()
{
    // End:0x19
    if(LastHurtTime == 0)
    {
        return 9999;
    }
    return Owner.WorldInfo.TimeSeconds - LastHurtTime;
    //return ReturnValue;    
}

function float GetTimeSinceAttacked()
{
    // End:0x19
    if(LastAttackedTime == 0)
    {
        return 9999;
    }
    return Owner.WorldInfo.TimeSeconds - LastAttackedTime;
    //return ReturnValue;    
}

// Export UWillowAIComponent::execOnHold(FFrame&, void* const)
native function bool OnHold();

// Export UWillowAIComponent::execHeadLookOnHold(FFrame&, void* const)
native function bool HeadLookOnHold();

// Export UWillowAIComponent::execHoldHeadLook(FFrame&, void* const)
native function HoldHeadLook(name HoldName, Object Tag);

// Export UWillowAIComponent::execReleaseHeadLook(FFrame&, void* const)
native function ReleaseHeadLook(name HoldName, Object Tag);

// Export UWillowAIComponent::execPhaseLockOnHold(FFrame&, void* const)
native function bool PhaseLockOnHold();

// Export UWillowAIComponent::execHoldPhaseLock(FFrame&, void* const)
native function HoldPhaseLock(name HoldName, Object Tag);

// Export UWillowAIComponent::execReleasePhaseLock(FFrame&, void* const)
native function ReleasePhaseLock(name HoldName, Object Tag);

function bool CanPhaseLock()
{
    return !PhaseLockOnHold();
    //return ReturnValue;    
}

// Export UWillowAIComponent::execClaimNearbyVehicle(FFrame&, void* const)
native function WillowVehicle ClaimNearbyVehicle();

// Export UWillowAIComponent::execDrawAttackDebug(FFrame&, void* const)
native function DrawAttackDebug();

// Export UWillowAIComponent::execToggleAttackDebug(FFrame&, void* const)
native static function ToggleAttackDebug();

// Export UWillowAIComponent::execIsAttackDebugEnabled(FFrame&, void* const)
native static function bool IsAttackDebugEnabled();

// Export UWillowAIComponent::execIsAIThrottled(FFrame&, void* const)
native function bool IsAIThrottled();

defaultproperties
{
    LastZone=(Index=-1,Bounds=(Min=(X=0,Y=0,Z=0),Max=(X=0,Y=0,Z=0),IsValid=0))
    CurrentZone=(Index=-1,Bounds=(Min=(X=0,Y=0,Z=0),Max=(X=0,Y=0,Z=0),IsValid=0))
    ClaimedZone=(Index=-1,Bounds=(Min=(X=0,Y=0,Z=0),Max=(X=0,Y=0,Z=0),IsValid=0))
    MindTargetInfoClass='WillowMindTargetInfo'
}